# DQN PER

## Pruebas

In [ ]:
import sys
import importlib

import numpy as np

sys.path.append("../src")

import replay_buffer
importlib.reload(replay_buffer)

from replay_buffer import SumTree

arbol_prueba = SumTree(capacidad=4)

prioridades = [1.0, 2.0, 3.0, 4.0]

for indice, prioridad in enumerate(prioridades):
    arbol_prueba.actualizar(
        indice_dato=indice,
        prioridad=prioridad,
    )

print(
    f"Prioridad total esperada: "
    f"{sum(prioridades):.2f}"
)
print(
    f"Prioridad total obtenida: "
    f"{arbol_prueba.prioridad_total:.2f}"
)

print("\nMUESTREO POR VALOR ACUMULADO")

valores_prueba = [0.5, 1.5, 4.5, 8.0]

for valor in valores_prueba:
    indice, prioridad = arbol_prueba.obtener(valor)

    print(
        f"Valor {valor:>4.1f} -> "
        f"índice {indice}, "
        f"prioridad {prioridad:.1f}"
    )

arbol_prueba.actualizar(
    indice_dato=0,
    prioridad=5.0,
)

print(
    "\nPrioridad total después de cambiar "
    f"la prioridad 0 de 1 a 5: "
    f"{arbol_prueba.prioridad_total:.2f}"
)

assert np.isclose(
    arbol_prueba.prioridad_total,
    14.0,
)

print("\nEl SumTree funciona correctamente.")

Prioridad total esperada: 10.00
Prioridad total obtenida: 10.00

MUESTREO POR VALOR ACUMULADO
Valor  0.5 -> índice 0, prioridad 1.0
Valor  1.5 -> índice 1, prioridad 2.0
Valor  4.5 -> índice 2, prioridad 3.0
Valor  8.0 -> índice 3, prioridad 4.0

Prioridad total después de cambiar la prioridad 0 de 1 a 5: 14.00

El SumTree funciona correctamente.

In [ ]:
import torch

importlib.reload(replay_buffer)

from replay_buffer import (
    SumTree,
    PrioritizedReplayBuffer,
)

buffer_per_prueba = PrioritizedReplayBuffer(
    capacidad=8,
    forma_observacion=(4, 84, 84),
    seed=42,
    alpha=0.6,
    epsilon_per=1e-6,
)

for indice in range(8):
    observacion = np.full(
        (4, 84, 84),
        fill_value=indice,
        dtype=np.uint8,
    )

    siguiente_observacion = np.full(
        (4, 84, 84),
        fill_value=indice + 1,
        dtype=np.uint8,
    )

    buffer_per_prueba.agregar(
        observacion=observacion,
        accion=indice % 6,
        recompensa=float(indice),
        siguiente_observacion=siguiente_observacion,
        finalizado=False,
    )

errores_td = np.array(
    [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 10.0],
    dtype=np.float32,
)

buffer_per_prueba.actualizar_prioridades(
    indices=np.arange(8),
    errores_td=errores_td,
)

conteos = np.zeros(8, dtype=np.int64)

for _ in range(500):
    (
        observaciones,
        acciones,
        recompensas,
        siguientes_observaciones,
        finalizados,
        indices,
        pesos,
    ) = buffer_per_prueba.muestrear(
        batch_size=4,
        device=torch.device("cpu"),
        beta=0.4,
    )

    for indice in indices:
        conteos[indice] += 1

print("FRECUENCIA DE MUESTREO")

for indice, conteo in enumerate(conteos):
    print(
        f"Experiencia {indice}: "
        f"{conteo} apariciones"
    )

print(
    "\nPrioridad total: "
    f"{buffer_per_prueba.arbol_prioridades.prioridad_total:.4f}"
)

print(
    "Forma de los pesos: "
    f"{pesos.shape}"
)

print(
    "Rango de los pesos: "
    f"{pesos.min().item():.4f} - "
    f"{pesos.max().item():.4f}"
)

assert len(buffer_per_prueba) == 8
assert pesos.shape == (4,)
assert torch.isfinite(pesos).all()
assert pesos.max() <= 1.0 + 1e-6

assert conteos[7] > conteos[:7].max()

print(
    "\nLa experiencia con mayor error TD fue "
    "muestreada con mayor frecuencia."
)

FRECUENCIA DE MUESTREO
Experiencia 0: 97 apariciones
Experiencia 1: 89 apariciones
Experiencia 2: 80 apariciones
Experiencia 3: 85 apariciones
Experiencia 4: 90 apariciones
Experiencia 5: 79 apariciones
Experiencia 6: 79 apariciones
Experiencia 7: 1401 apariciones

Prioridad total: 5.7394
Forma de los pesos: torch.Size([4])
Rango de los pesos: 0.3311 - 1.0000

La experiencia con mayor error TD fue muestreada con mayor frecuencia.

In [ ]:
from copy import deepcopy

import models
import train

importlib.reload(models)
importlib.reload(train)

from models import DQN
from train import (
    ConfigDQN,
    actualizar_modelo,
)

device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "mps" if torch.backends.mps.is_available()
    else "cpu"
)

config_prueba_per = ConfigDQN(
    batch_size=32,
    capacidad_buffer=64,
    usar_per=True,
    per_alpha=0.6,
    per_beta_inicial=0.4,
    per_beta_final=1.0,
    per_pasos_beta=1_000,
)

modelo_online_prueba = DQN(
    n_acciones=6
).to(device)

modelo_target_prueba = deepcopy(
    modelo_online_prueba
).to(device)

modelo_target_prueba.eval()

optimizador_prueba = torch.optim.Adam(
    modelo_online_prueba.parameters(),
    lr=config_prueba_per.learning_rate,
)

buffer_actualizacion_per = PrioritizedReplayBuffer(
    capacidad=64,
    forma_observacion=(4, 84, 84),
    seed=42,
    alpha=config_prueba_per.per_alpha,
    epsilon_per=config_prueba_per.per_epsilon,
)

rng_prueba = np.random.default_rng(42)

for _ in range(64):
    observacion = rng_prueba.integers(
        0,
        256,
        size=(4, 84, 84),
        dtype=np.uint8,
    )

    siguiente_observacion = rng_prueba.integers(
        0,
        256,
        size=(4, 84, 84),
        dtype=np.uint8,
    )

    buffer_actualizacion_per.agregar(
        observacion=observacion,
        accion=int(rng_prueba.integers(6)),
        recompensa=float(
            rng_prueba.choice([-1.0, 0.0, 1.0])
        ),
        siguiente_observacion=siguiente_observacion,
        finalizado=bool(
            rng_prueba.random() < 0.1
        ),
    )

inicio_hojas = (
    buffer_actualizacion_per.capacidad - 1
)

prioridades_antes = (
    buffer_actualizacion_per
    .arbol_prioridades
    .arbol[
        inicio_hojas:
        inicio_hojas + len(buffer_actualizacion_per)
    ]
    .copy()
)

metricas_prueba_per = actualizar_modelo(
    modelo_online=modelo_online_prueba,
    modelo_target=modelo_target_prueba,
    replay_buffer=buffer_actualizacion_per,
    optimizador=optimizador_prueba,
    config=config_prueba_per,
    device=device,
    usar_double_dqn=False,
    paso_global=500,
)

prioridades_despues = (
    buffer_actualizacion_per
    .arbol_prioridades
    .arbol[
        inicio_hojas:
        inicio_hojas + len(buffer_actualizacion_per)
    ]
    .copy()
)

prioridades_modificadas = np.count_nonzero(
    ~np.isclose(
        prioridades_antes,
        prioridades_despues,
    )
)

print(f"Dispositivo: {device}")
print(
    f"Loss: "
    f"{metricas_prueba_per['loss']:.6f}"
)
print(
    f"Error TD promedio: "
    f"{metricas_prueba_per['error_td_promedio']:.6f}"
)
print(
    f"Beta utilizado: "
    f"{metricas_prueba_per['beta_per']:.3f}"
)
print(
    f"Peso de importancia promedio: "
    f"{metricas_prueba_per['peso_importancia_promedio']:.3f}"
)
print(
    f"Prioridades modificadas: "
    f"{prioridades_modificadas}"
)

assert np.isfinite(
    metricas_prueba_per["loss"]
)

assert prioridades_modificadas > 0

assert np.isclose(
    metricas_prueba_per["beta_per"],
    0.7,
)

print(
    "\nLa actualización con PER funciona correctamente."
)

Dispositivo: mps
Loss: 0.214474
Error TD promedio: 0.449528
Beta utilizado: 0.700
Peso de importancia promedio: 1.000
Prioridades modificadas: 32

La actualización con PER funciona correctamente.

In [4]:
import gc
import pandas as pd
from pathlib import Path

importlib.reload(train)

from train import (
    ConfigDQN,
    entrenar_dqn,
)

objetos_temporales = [
    "buffer_per_prueba",
    "buffer_actualizacion_per",
    "modelo_online_prueba",
    "modelo_target_prueba",
    "optimizador_prueba",
]

for nombre in objetos_temporales:
    globals().pop(nombre, None)

gc.collect()

if device.type == "mps":
    torch.mps.empty_cache()

config_smoke_per = ConfigDQN(
    nombre_experimento="smoke_test_dqn_per",
    total_pasos=2_000,

    usar_per=True,
    per_alpha=0.6,
    per_beta_inicial=0.4,
    per_beta_final=1.0,
    per_pasos_beta=2_000,
    per_epsilon=1e-6,

    capacidad_buffer=2_000,
    inicio_entrenamiento=200,
    batch_size=32,
    frecuencia_entrenamiento=4,
    frecuencia_actualizacion_target=500,

    epsilon_inicial=1.0,
    epsilon_final=0.1,
    pasos_decay_epsilon=1_000,

    frecuencia_log=250,
    frecuencia_evaluacion=2_000,
    episodios_evaluacion=1,
)

resultado_smoke_per = entrenar_dqn(
    config=config_smoke_per,
    clase_modelo=DQN,
    device=device,
    usar_double_dqn=False,
)

print("\nSMOKE TEST DQN + PER FINALIZADO")
print(
    "Mejor promedio de evaluación: "
    f"{resultado_smoke_per['mejor_promedio_evaluacion']:.2f}"
)

ruta_updates_smoke = Path(
    "../logs/entrenamientos/"
    "smoke_test_dqn_per/actualizaciones.csv"
)

df_updates_smoke = pd.read_csv(
    ruta_updates_smoke
)

display(
    df_updates_smoke[
        [
            "paso_global",
            "loss",
            "error_td_promedio",
            "beta_per",
            "peso_importancia_promedio",
            "tamano_buffer",
        ]
    ]
)

A.L.E: Arcade Learning Environment (version 0.10.1+6a7e0ae)
[Powered by Stella]

Replay buffer: priorizado | alpha=0.6 | beta inicial=0.4
Paso 250/2,000 | episodio=1 | epsilon=0.775 | loss=0.0054 | Q=0.071
Paso 500/2,000 | episodio=2 | epsilon=0.550 | loss=0.0133 | Q=0.103
Paso 750/2,000 | episodio=3 | epsilon=0.325 | loss=0.0021 | Q=0.185
Paso 1,000/2,000 | episodio=5 | epsilon=0.100 | loss=0.0039 | Q=0.177
Paso 1,250/2,000 | episodio=6 | epsilon=0.100 | loss=0.0104 | Q=0.297
Paso 1,500/2,000 | episodio=7 | epsilon=0.100 | loss=0.0026 | Q=0.246
Paso 1,750/2,000 | episodio=9 | epsilon=0.100 | loss=0.0049 | Q=0.373
Paso 2,000/2,000 | episodio=10 | epsilon=0.100 | loss=0.0013 | Q=0.336

EVALUACIÓN | paso=2,000 | promedio=80.00 | mediana=80.00 | máximo=80.00


SMOKE TEST DQN + PER FINALIZADO
Mejor promedio de evaluación: 80.00

,paso_global,loss,error_td_promedio,beta_per,peso_importancia_promedio,tamano_buffer
0,250,0.005354,0.083589,0.4744,0.453879,250
1,500,0.013343,0.214829,0.5500,0.373648,500
2,750,0.002121,0.115667,0.6244,0.180380,750
3,1000,0.003941,0.129842,0.7000,0.312108,1000
4,1250,0.010394,0.227189,0.7744,0.377781,1250
5,1500,0.002597,0.148887,0.8500,0.194636,1500
6,1750,0.004911,0.191007,0.9244,0.289631,1750
7,2000,0.001277,0.171572,1.0000,0.159696,2000

## Entrenamiento DQN + PER

In [6]:
# Liberar objetos del smoke test
objetos_temporales = [
    "resultado_smoke_per",
    "df_updates_smoke",
]

for nombre in objetos_temporales:
    globals().pop(nombre, None)

gc.collect()

if device.type == "mps":
    torch.mps.empty_cache()

config_dqn_per = ConfigDQN(
    nombre_experimento="v5_dqn_per",
    total_pasos=1_000_000,

    gamma=0.99,
    learning_rate=1e-4,
    batch_size=32,
    frecuencia_entrenamiento=4,

    capacidad_buffer=20_000,
    inicio_entrenamiento=10_000,
    frecuencia_actualizacion_target=10_000,
    gradient_clip=10.0,

    epsilon_inicial=1.0,
    epsilon_final=0.1,
    pasos_decay_epsilon=250_000,

    # Configuración de PER
    usar_per=True,
    per_alpha=0.6,
    per_beta_inicial=0.4,
    per_beta_final=1.0,
    per_pasos_beta=500_000,
    per_epsilon=1e-6,

    frecuencia_evaluacion=50_000,
    episodios_evaluacion=5,
    seed_evaluacion=1_000,
    frecuencia_log=1_000,

    terminal_on_life_loss=True,
    clip_reward=True,
)

resultado_dqn_per = entrenar_dqn(
    config=config_dqn_per,
    clase_modelo=DQN,
    device=device,
    usar_double_dqn=False,
)

print("\nENTRENAMIENTO DQN + PER FINALIZADO")
print(
    "Mejor promedio de evaluación: "
    f"{resultado_dqn_per['mejor_promedio_evaluacion']:.2f}"
)

Replay buffer: priorizado | alpha=0.6 | beta inicial=0.4
Paso 10,000/1,000,000 | episodio=49 | epsilon=0.964 | loss=0.0328 | Q=0.005
Paso 11,000/1,000,000 | episodio=52 | epsilon=0.960 | loss=0.0051 | Q=0.111
Paso 12,000/1,000,000 | episodio=58 | epsilon=0.957 | loss=0.0440 | Q=0.117
Paso 13,000/1,000,000 | episodio=63 | epsilon=0.953 | loss=0.0303 | Q=0.159
Paso 14,000/1,000,000 | episodio=68 | epsilon=0.950 | loss=0.0087 | Q=0.136
Paso 15,000/1,000,000 | episodio=72 | epsilon=0.946 | loss=0.0126 | Q=0.144
Paso 16,000/1,000,000 | episodio=78 | epsilon=0.942 | loss=0.0237 | Q=0.106
Paso 17,000/1,000,000 | episodio=83 | epsilon=0.939 | loss=0.0010 | Q=0.113
Paso 18,000/1,000,000 | episodio=88 | epsilon=0.935 | loss=0.0114 | Q=0.106
Paso 19,000/1,000,000 | episodio=93 | epsilon=0.932 | loss=0.0035 | Q=0.132
Paso 20,000/1,000,000 | episodio=99 | epsilon=0.928 | loss=0.0092 | Q=0.167
Paso 21,000/1,000,000 | episodio=102 | epsilon=0.924 | loss=0.0167 | Q=0.306
Paso 22,000/1,000,000 | episodio=107 | epsilon=0.921 | loss=0.0210 | Q=0.206
Paso 23,000/1,000,000 | episodio=111 | epsilon=0.917 | loss=0.0110 | Q=0.172
Paso 24,000/1,000,000 | episodio=116 | epsilon=0.914 | loss=0.0205 | Q=0.245
Paso 25,000/1,000,000 | episodio=121 | epsilon=0.910 | loss=0.0064 | Q=0.286
Paso 26,000/1,000,000 | episodio=125 | epsilon=0.906 | loss=0.0119 | Q=0.250
Paso 27,000/1,000,000 | episodio=129 | epsilon=0.903 | loss=0.0041 | Q=0.218
Paso 28,000/1,000,000 | episodio=135 | epsilon=0.899 | loss=0.0087 | Q=0.245
Paso 29,000/1,000,000 | episodio=141 | epsilon=0.896 | loss=0.0120 | Q=0.240
Paso 30,000/1,000,000 | episodio=145 | epsilon=0.892 | loss=0.0009 | Q=0.173
Paso 31,000/1,000,000 | episodio=148 | epsilon=0.888 | loss=0.0100 | Q=0.335
Paso 32,000/1,000,000 | episodio=153 | epsilon=0.885 | loss=0.0047 | Q=0.223
Paso 33,000/1,000,000 | episodio=157 | epsilon=0.881 | loss=0.0107 | Q=0.307
Paso 34,000/1,000,000 | episodio=163 | epsilon=0.878 | loss=0.0083 | Q=0.218
Paso 35,000/1,000,000 | episodio=169 | epsilon=0.874 | loss=0.0066 | Q=0.284
Paso 36,000/1,000,000 | episodio=174 | epsilon=0.870 | loss=0.0099 | Q=0.234
Paso 37,000/1,000,000 | episodio=179 | epsilon=0.867 | loss=0.0147 | Q=0.336
Paso 38,000/1,000,000 | episodio=185 | epsilon=0.863 | loss=0.0048 | Q=0.232
Paso 39,000/1,000,000 | episodio=190 | epsilon=0.860 | loss=0.0037 | Q=0.228
Paso 40,000/1,000,000 | episodio=196 | epsilon=0.856 | loss=0.0043 | Q=0.209
Paso 41,000/1,000,000 | episodio=202 | epsilon=0.852 | loss=0.0125 | Q=0.322
Paso 42,000/1,000,000 | episodio=209 | epsilon=0.849 | loss=0.0039 | Q=0.263
Paso 43,000/1,000,000 | episodio=214 | epsilon=0.845 | loss=0.0080 | Q=0.189
Paso 44,000/1,000,000 | episodio=217 | epsilon=0.842 | loss=0.0110 | Q=0.254
Paso 45,000/1,000,000 | episodio=222 | epsilon=0.838 | loss=0.0061 | Q=0.266
Paso 46,000/1,000,000 | episodio=225 | epsilon=0.834 | loss=0.0079 | Q=0.235
Paso 47,000/1,000,000 | episodio=229 | epsilon=0.831 | loss=0.0081 | Q=0.355
Paso 48,000/1,000,000 | episodio=235 | epsilon=0.827 | loss=0.0035 | Q=0.309
Paso 49,000/1,000,000 | episodio=241 | epsilon=0.824 | loss=0.0104 | Q=0.356
Paso 50,000/1,000,000 | episodio=247 | epsilon=0.820 | loss=0.0097 | Q=0.247

EVALUACIÓN | paso=50,000 | promedio=121.00 | mediana=60.00 | máximo=380.00

Paso 51,000/1,000,000 | episodio=253 | epsilon=0.816 | loss=0.0121 | Q=0.397
Paso 52,000/1,000,000 | episodio=258 | epsilon=0.813 | loss=0.0078 | Q=0.389
Paso 53,000/1,000,000 | episodio=262 | epsilon=0.809 | loss=0.0133 | Q=0.313
Paso 54,000/1,000,000 | episodio=266 | epsilon=0.806 | loss=0.0063 | Q=0.318
Paso 55,000/1,000,000 | episodio=270 | epsilon=0.802 | loss=0.0117 | Q=0.386
Paso 56,000/1,000,000 | episodio=274 | epsilon=0.798 | loss=0.0057 | Q=0.312
Paso 57,000/1,000,000 | episodio=280 | epsilon=0.795 | loss=0.0110 | Q=0.320
Paso 58,000/1,000,000 | episodio=287 | epsilon=0.791 | loss=0.0084 | Q=0.345
Paso 59,000/1,000,000 | episodio=293 | epsilon=0.788 | loss=0.0030 | Q=0.267
Paso 60,000/1,000,000 | episodio=300 | epsilon=0.784 | loss=0.0032 | Q=0.307
Paso 61,000/1,000,000 | episodio=306 | epsilon=0.780 | loss=0.0112 | Q=0.493
Paso 62,000/1,000,000 | episodio=312 | epsilon=0.777 | loss=0.0034 | Q=0.406
Paso 63,000/1,000,000 | episodio=316 | epsilon=0.773 | loss=0.0139 | Q=0.390
Paso 64,000/1,000,000 | episodio=321 | epsilon=0.770 | loss=0.0033 | Q=0.403
Paso 65,000/1,000,000 | episodio=326 | epsilon=0.766 | loss=0.0088 | Q=0.428
Paso 66,000/1,000,000 | episodio=333 | epsilon=0.762 | loss=0.0027 | Q=0.318
Paso 67,000/1,000,000 | episodio=336 | epsilon=0.759 | loss=0.0056 | Q=0.406
Paso 68,000/1,000,000 | episodio=342 | epsilon=0.755 | loss=0.0034 | Q=0.436
Paso 69,000/1,000,000 | episodio=345 | epsilon=0.752 | loss=0.0103 | Q=0.488
Paso 70,000/1,000,000 | episodio=351 | epsilon=0.748 | loss=0.0030 | Q=0.394
Paso 71,000/1,000,000 | episodio=355 | epsilon=0.744 | loss=0.0080 | Q=0.516
Paso 72,000/1,000,000 | episodio=360 | epsilon=0.741 | loss=0.0053 | Q=0.524
Paso 73,000/1,000,000 | episodio=364 | epsilon=0.737 | loss=0.0078 | Q=0.542
Paso 74,000/1,000,000 | episodio=369 | epsilon=0.734 | loss=0.0063 | Q=0.487
Paso 75,000/1,000,000 | episodio=373 | epsilon=0.730 | loss=0.0052 | Q=0.435
Paso 76,000/1,000,000 | episodio=377 | epsilon=0.726 | loss=0.0054 | Q=0.533
Paso 77,000/1,000,000 | episodio=383 | epsilon=0.723 | loss=0.0036 | Q=0.577
Paso 78,000/1,000,000 | episodio=389 | epsilon=0.719 | loss=0.0062 | Q=0.566
Paso 79,000/1,000,000 | episodio=394 | epsilon=0.716 | loss=0.0052 | Q=0.622
Paso 80,000/1,000,000 | episodio=398 | epsilon=0.712 | loss=0.0113 | Q=0.560
Paso 81,000/1,000,000 | episodio=404 | epsilon=0.708 | loss=0.0106 | Q=0.595
Paso 82,000/1,000,000 | episodio=409 | epsilon=0.705 | loss=0.0092 | Q=0.553
Paso 83,000/1,000,000 | episodio=414 | epsilon=0.701 | loss=0.0052 | Q=0.609
Paso 84,000/1,000,000 | episodio=419 | epsilon=0.698 | loss=0.0056 | Q=0.578
Paso 85,000/1,000,000 | episodio=425 | epsilon=0.694 | loss=0.0028 | Q=0.601
Paso 86,000/1,000,000 | episodio=431 | epsilon=0.690 | loss=0.0039 | Q=0.614
Paso 87,000/1,000,000 | episodio=437 | epsilon=0.687 | loss=0.0058 | Q=0.754
Paso 88,000/1,000,000 | episodio=443 | epsilon=0.683 | loss=0.0044 | Q=0.637
Paso 89,000/1,000,000 | episodio=450 | epsilon=0.680 | loss=0.0064 | Q=0.432
Paso 90,000/1,000,000 | episodio=457 | epsilon=0.676 | loss=0.0051 | Q=0.468
Paso 91,000/1,000,000 | episodio=461 | epsilon=0.672 | loss=0.0060 | Q=0.497
Paso 92,000/1,000,000 | episodio=466 | epsilon=0.669 | loss=0.0026 | Q=0.452
Paso 93,000/1,000,000 | episodio=470 | epsilon=0.665 | loss=0.0053 | Q=0.717
Paso 94,000/1,000,000 | episodio=476 | epsilon=0.662 | loss=0.0048 | Q=0.577
Paso 95,000/1,000,000 | episodio=481 | epsilon=0.658 | loss=0.0037 | Q=0.594
Paso 96,000/1,000,000 | episodio=487 | epsilon=0.654 | loss=0.0053 | Q=0.793
Paso 97,000/1,000,000 | episodio=491 | epsilon=0.651 | loss=0.0064 | Q=0.563
Paso 98,000/1,000,000 | episodio=498 | epsilon=0.647 | loss=0.0126 | Q=0.703
Paso 99,000/1,000,000 | episodio=504 | epsilon=0.644 | loss=0.0048 | Q=0.528
Paso 100,000/1,000,000 | episodio=511 | epsilon=0.640 | loss=0.0009 | Q=0.528

EVALUACIÓN | paso=100,000 | promedio=142.00 | mediana=100.00 | máximo=375.00

Paso 101,000/1,000,000 | episodio=517 | epsilon=0.636 | loss=0.0020 | Q=0.457
Paso 102,000/1,000,000 | episodio=521 | epsilon=0.633 | loss=0.0048 | Q=0.617
Paso 103,000/1,000,000 | episodio=527 | epsilon=0.629 | loss=0.0067 | Q=0.598
Paso 104,000/1,000,000 | episodio=533 | epsilon=0.626 | loss=0.0046 | Q=0.468
Paso 105,000/1,000,000 | episodio=538 | epsilon=0.622 | loss=0.0128 | Q=0.634
Paso 106,000/1,000,000 | episodio=542 | epsilon=0.618 | loss=0.0029 | Q=0.559
Paso 107,000/1,000,000 | episodio=548 | epsilon=0.615 | loss=0.0033 | Q=0.586
Paso 108,000/1,000,000 | episodio=553 | epsilon=0.611 | loss=0.0057 | Q=0.591
Paso 109,000/1,000,000 | episodio=559 | epsilon=0.608 | loss=0.0024 | Q=0.552
Paso 110,000/1,000,000 | episodio=566 | epsilon=0.604 | loss=0.0024 | Q=0.574
Paso 111,000/1,000,000 | episodio=571 | epsilon=0.600 | loss=0.0068 | Q=0.600
Paso 112,000/1,000,000 | episodio=576 | epsilon=0.597 | loss=0.0057 | Q=0.689
Paso 113,000/1,000,000 | episodio=582 | epsilon=0.593 | loss=0.0029 | Q=0.632
Paso 114,000/1,000,000 | episodio=586 | epsilon=0.590 | loss=0.0050 | Q=0.727
Paso 115,000/1,000,000 | episodio=591 | epsilon=0.586 | loss=0.0048 | Q=0.813
Paso 116,000/1,000,000 | episodio=598 | epsilon=0.582 | loss=0.0065 | Q=0.594
Paso 117,000/1,000,000 | episodio=601 | epsilon=0.579 | loss=0.0083 | Q=0.816
Paso 118,000/1,000,000 | episodio=604 | epsilon=0.575 | loss=0.0048 | Q=0.734
Paso 119,000/1,000,000 | episodio=609 | epsilon=0.572 | loss=0.0171 | Q=0.777
Paso 120,000/1,000,000 | episodio=615 | epsilon=0.568 | loss=0.0071 | Q=0.701
Paso 121,000/1,000,000 | episodio=620 | epsilon=0.564 | loss=0.0049 | Q=0.791
Paso 122,000/1,000,000 | episodio=625 | epsilon=0.561 | loss=0.0071 | Q=0.845
Paso 123,000/1,000,000 | episodio=628 | epsilon=0.557 | loss=0.0028 | Q=0.709
Paso 124,000/1,000,000 | episodio=635 | epsilon=0.554 | loss=0.0088 | Q=0.824
Paso 125,000/1,000,000 | episodio=640 | epsilon=0.550 | loss=0.0132 | Q=0.820
Paso 126,000/1,000,000 | episodio=646 | epsilon=0.546 | loss=0.0141 | Q=0.866
Paso 127,000/1,000,000 | episodio=651 | epsilon=0.543 | loss=0.0064 | Q=0.719
Paso 128,000/1,000,000 | episodio=656 | epsilon=0.539 | loss=0.0069 | Q=0.648
Paso 129,000/1,000,000 | episodio=660 | epsilon=0.536 | loss=0.0030 | Q=0.709
Paso 130,000/1,000,000 | episodio=663 | epsilon=0.532 | loss=0.0093 | Q=0.827
Paso 131,000/1,000,000 | episodio=667 | epsilon=0.528 | loss=0.0085 | Q=1.032
Paso 132,000/1,000,000 | episodio=671 | epsilon=0.525 | loss=0.0040 | Q=0.966
Paso 133,000/1,000,000 | episodio=675 | epsilon=0.521 | loss=0.0022 | Q=1.053
Paso 134,000/1,000,000 | episodio=680 | epsilon=0.518 | loss=0.0094 | Q=0.815
Paso 135,000/1,000,000 | episodio=685 | epsilon=0.514 | loss=0.0087 | Q=0.732
Paso 136,000/1,000,000 | episodio=689 | epsilon=0.510 | loss=0.0073 | Q=0.807
Paso 137,000/1,000,000 | episodio=694 | epsilon=0.507 | loss=0.0042 | Q=1.007
Paso 138,000/1,000,000 | episodio=700 | epsilon=0.503 | loss=0.0057 | Q=0.829
Paso 139,000/1,000,000 | episodio=706 | epsilon=0.500 | loss=0.0060 | Q=0.882
Paso 140,000/1,000,000 | episodio=713 | epsilon=0.496 | loss=0.0040 | Q=0.857
Paso 141,000/1,000,000 | episodio=719 | epsilon=0.492 | loss=0.0041 | Q=0.911
Paso 142,000/1,000,000 | episodio=725 | epsilon=0.489 | loss=0.0048 | Q=1.063
Paso 143,000/1,000,000 | episodio=731 | epsilon=0.485 | loss=0.0037 | Q=0.899
Paso 144,000/1,000,000 | episodio=735 | epsilon=0.482 | loss=0.0043 | Q=0.844
Paso 145,000/1,000,000 | episodio=737 | epsilon=0.478 | loss=0.0096 | Q=1.013
Paso 146,000/1,000,000 | episodio=743 | epsilon=0.474 | loss=0.0045 | Q=0.858
Paso 147,000/1,000,000 | episodio=750 | epsilon=0.471 | loss=0.0048 | Q=0.906
Paso 148,000/1,000,000 | episodio=754 | epsilon=0.467 | loss=0.0009 | Q=0.858
Paso 149,000/1,000,000 | episodio=759 | epsilon=0.464 | loss=0.0059 | Q=1.149
Paso 150,000/1,000,000 | episodio=763 | epsilon=0.460 | loss=0.0071 | Q=1.131

EVALUACIÓN | paso=150,000 | promedio=160.00 | mediana=155.00 | máximo=215.00

Paso 151,000/1,000,000 | episodio=766 | epsilon=0.456 | loss=0.0057 | Q=0.958
Paso 152,000/1,000,000 | episodio=770 | epsilon=0.453 | loss=0.0023 | Q=0.941
Paso 153,000/1,000,000 | episodio=774 | epsilon=0.449 | loss=0.0063 | Q=0.819
Paso 154,000/1,000,000 | episodio=779 | epsilon=0.446 | loss=0.0044 | Q=1.137
Paso 155,000/1,000,000 | episodio=785 | epsilon=0.442 | loss=0.0056 | Q=0.865
Paso 156,000/1,000,000 | episodio=791 | epsilon=0.438 | loss=0.0045 | Q=1.085
Paso 157,000/1,000,000 | episodio=796 | epsilon=0.435 | loss=0.0103 | Q=0.892
Paso 158,000/1,000,000 | episodio=799 | epsilon=0.431 | loss=0.0049 | Q=1.134
Paso 159,000/1,000,000 | episodio=805 | epsilon=0.428 | loss=0.0070 | Q=1.122
Paso 160,000/1,000,000 | episodio=806 | epsilon=0.424 | loss=0.0069 | Q=1.056
Paso 161,000/1,000,000 | episodio=811 | epsilon=0.420 | loss=0.0064 | Q=1.004
Paso 162,000/1,000,000 | episodio=818 | epsilon=0.417 | loss=0.0137 | Q=1.165
Paso 163,000/1,000,000 | episodio=824 | epsilon=0.413 | loss=0.0053 | Q=1.055
Paso 164,000/1,000,000 | episodio=830 | epsilon=0.410 | loss=0.0034 | Q=1.057
Paso 165,000/1,000,000 | episodio=836 | epsilon=0.406 | loss=0.0065 | Q=1.231
Paso 166,000/1,000,000 | episodio=841 | epsilon=0.402 | loss=0.0139 | Q=0.921
Paso 167,000/1,000,000 | episodio=847 | epsilon=0.399 | loss=0.0130 | Q=1.156
Paso 168,000/1,000,000 | episodio=851 | epsilon=0.395 | loss=0.0053 | Q=1.111
Paso 169,000/1,000,000 | episodio=855 | epsilon=0.392 | loss=0.0103 | Q=0.906
Paso 170,000/1,000,000 | episodio=861 | epsilon=0.388 | loss=0.0065 | Q=1.062
Paso 171,000/1,000,000 | episodio=865 | epsilon=0.384 | loss=0.0161 | Q=1.231
Paso 172,000/1,000,000 | episodio=870 | epsilon=0.381 | loss=0.0078 | Q=1.206
Paso 173,000/1,000,000 | episodio=875 | epsilon=0.377 | loss=0.0052 | Q=1.209
Paso 174,000/1,000,000 | episodio=880 | epsilon=0.374 | loss=0.0058 | Q=0.968
Paso 175,000/1,000,000 | episodio=886 | epsilon=0.370 | loss=0.0054 | Q=1.054
Paso 176,000/1,000,000 | episodio=889 | epsilon=0.366 | loss=0.0029 | Q=1.221
Paso 177,000/1,000,000 | episodio=894 | epsilon=0.363 | loss=0.0192 | Q=1.052
Paso 178,000/1,000,000 | episodio=899 | epsilon=0.359 | loss=0.0040 | Q=1.048
Paso 179,000/1,000,000 | episodio=905 | epsilon=0.356 | loss=0.0041 | Q=1.083
Paso 180,000/1,000,000 | episodio=910 | epsilon=0.352 | loss=0.0067 | Q=0.926
Paso 181,000/1,000,000 | episodio=914 | epsilon=0.348 | loss=0.0071 | Q=1.462
Paso 182,000/1,000,000 | episodio=918 | epsilon=0.345 | loss=0.0080 | Q=1.203
Paso 183,000/1,000,000 | episodio=925 | epsilon=0.341 | loss=0.0110 | Q=1.256
Paso 184,000/1,000,000 | episodio=929 | epsilon=0.338 | loss=0.0131 | Q=1.265
Paso 185,000/1,000,000 | episodio=932 | epsilon=0.334 | loss=0.0114 | Q=1.017
Paso 186,000/1,000,000 | episodio=936 | epsilon=0.330 | loss=0.0039 | Q=1.353
Paso 187,000/1,000,000 | episodio=941 | epsilon=0.327 | loss=0.0181 | Q=1.335
Paso 188,000/1,000,000 | episodio=946 | epsilon=0.323 | loss=0.0035 | Q=1.187
Paso 189,000/1,000,000 | episodio=950 | epsilon=0.320 | loss=0.0070 | Q=1.539
Paso 190,000/1,000,000 | episodio=955 | epsilon=0.316 | loss=0.0040 | Q=1.271
Paso 191,000/1,000,000 | episodio=958 | epsilon=0.312 | loss=0.0050 | Q=1.270
Paso 192,000/1,000,000 | episodio=964 | epsilon=0.309 | loss=0.0077 | Q=1.340
Paso 193,000/1,000,000 | episodio=967 | epsilon=0.305 | loss=0.0108 | Q=1.426
Paso 194,000/1,000,000 | episodio=970 | epsilon=0.302 | loss=0.0116 | Q=1.398
Paso 195,000/1,000,000 | episodio=974 | epsilon=0.298 | loss=0.0064 | Q=1.322
Paso 196,000/1,000,000 | episodio=978 | epsilon=0.294 | loss=0.0033 | Q=1.155
Paso 197,000/1,000,000 | episodio=981 | epsilon=0.291 | loss=0.0093 | Q=1.334
Paso 198,000/1,000,000 | episodio=985 | epsilon=0.287 | loss=0.0038 | Q=1.306
Paso 199,000/1,000,000 | episodio=990 | epsilon=0.284 | loss=0.0051 | Q=1.396
Paso 200,000/1,000,000 | episodio=995 | epsilon=0.280 | loss=0.0021 | Q=1.372

EVALUACIÓN | paso=200,000 | promedio=282.00 | mediana=215.00 | máximo=480.00

Paso 201,000/1,000,000 | episodio=999 | epsilon=0.276 | loss=0.0136 | Q=1.452
Paso 202,000/1,000,000 | episodio=1002 | epsilon=0.273 | loss=0.0071 | Q=1.561
Paso 203,000/1,000,000 | episodio=1006 | epsilon=0.269 | loss=0.0084 | Q=1.228
Paso 204,000/1,000,000 | episodio=1012 | epsilon=0.266 | loss=0.0197 | Q=1.431
Paso 205,000/1,000,000 | episodio=1016 | epsilon=0.262 | loss=0.0061 | Q=1.415
Paso 206,000/1,000,000 | episodio=1021 | epsilon=0.258 | loss=0.0120 | Q=1.251
Paso 207,000/1,000,000 | episodio=1025 | epsilon=0.255 | loss=0.0062 | Q=1.560
Paso 208,000/1,000,000 | episodio=1027 | epsilon=0.251 | loss=0.0111 | Q=1.360
Paso 209,000/1,000,000 | episodio=1031 | epsilon=0.248 | loss=0.0025 | Q=1.378
Paso 210,000/1,000,000 | episodio=1036 | epsilon=0.244 | loss=0.0164 | Q=1.569
Paso 211,000/1,000,000 | episodio=1039 | epsilon=0.240 | loss=0.0099 | Q=1.452
Paso 212,000/1,000,000 | episodio=1043 | epsilon=0.237 | loss=0.0191 | Q=1.355
Paso 213,000/1,000,000 | episodio=1048 | epsilon=0.233 | loss=0.0065 | Q=1.687
Paso 214,000/1,000,000 | episodio=1053 | epsilon=0.230 | loss=0.0140 | Q=1.534
Paso 215,000/1,000,000 | episodio=1058 | epsilon=0.226 | loss=0.0054 | Q=1.498
Paso 216,000/1,000,000 | episodio=1063 | epsilon=0.222 | loss=0.0030 | Q=1.386
Paso 217,000/1,000,000 | episodio=1067 | epsilon=0.219 | loss=0.0176 | Q=1.415
Paso 218,000/1,000,000 | episodio=1070 | epsilon=0.215 | loss=0.0056 | Q=1.370
Paso 219,000/1,000,000 | episodio=1074 | epsilon=0.212 | loss=0.0009 | Q=1.439
Paso 220,000/1,000,000 | episodio=1077 | epsilon=0.208 | loss=0.0040 | Q=1.465
Paso 221,000/1,000,000 | episodio=1081 | epsilon=0.204 | loss=0.0103 | Q=1.486
Paso 222,000/1,000,000 | episodio=1084 | epsilon=0.201 | loss=0.0066 | Q=1.546
Paso 223,000/1,000,000 | episodio=1088 | epsilon=0.197 | loss=0.0081 | Q=1.418
Paso 224,000/1,000,000 | episodio=1090 | epsilon=0.194 | loss=0.0074 | Q=1.445
Paso 225,000/1,000,000 | episodio=1093 | epsilon=0.190 | loss=0.0083 | Q=1.492
Paso 226,000/1,000,000 | episodio=1096 | epsilon=0.186 | loss=0.0132 | Q=1.568
Paso 227,000/1,000,000 | episodio=1099 | epsilon=0.183 | loss=0.0068 | Q=1.399
Paso 228,000/1,000,000 | episodio=1104 | epsilon=0.179 | loss=0.0042 | Q=1.535
Paso 229,000/1,000,000 | episodio=1107 | epsilon=0.176 | loss=0.0025 | Q=1.599
Paso 230,000/1,000,000 | episodio=1109 | epsilon=0.172 | loss=0.0057 | Q=1.504
Paso 231,000/1,000,000 | episodio=1112 | epsilon=0.168 | loss=0.0036 | Q=1.715
Paso 232,000/1,000,000 | episodio=1117 | epsilon=0.165 | loss=0.0053 | Q=1.761
Paso 233,000/1,000,000 | episodio=1122 | epsilon=0.161 | loss=0.0303 | Q=1.734
Paso 234,000/1,000,000 | episodio=1125 | epsilon=0.158 | loss=0.0019 | Q=1.513
Paso 235,000/1,000,000 | episodio=1128 | epsilon=0.154 | loss=0.0077 | Q=1.580
Paso 236,000/1,000,000 | episodio=1131 | epsilon=0.150 | loss=0.0080 | Q=1.542
Paso 237,000/1,000,000 | episodio=1135 | epsilon=0.147 | loss=0.0079 | Q=1.829
Paso 238,000/1,000,000 | episodio=1138 | epsilon=0.143 | loss=0.0152 | Q=1.593
Paso 239,000/1,000,000 | episodio=1143 | epsilon=0.140 | loss=0.0067 | Q=1.690
Paso 240,000/1,000,000 | episodio=1146 | epsilon=0.136 | loss=0.0082 | Q=1.530
Paso 241,000/1,000,000 | episodio=1151 | epsilon=0.132 | loss=0.0049 | Q=1.619
Paso 242,000/1,000,000 | episodio=1155 | epsilon=0.129 | loss=0.0144 | Q=1.670
Paso 243,000/1,000,000 | episodio=1159 | epsilon=0.125 | loss=0.0025 | Q=1.758
Paso 244,000/1,000,000 | episodio=1164 | epsilon=0.122 | loss=0.0095 | Q=1.538
Paso 245,000/1,000,000 | episodio=1170 | epsilon=0.118 | loss=0.0218 | Q=1.572
Paso 246,000/1,000,000 | episodio=1172 | epsilon=0.114 | loss=0.0113 | Q=1.985
Paso 247,000/1,000,000 | episodio=1177 | epsilon=0.111 | loss=0.0066 | Q=1.740
Paso 248,000/1,000,000 | episodio=1182 | epsilon=0.107 | loss=0.0066 | Q=1.635
Paso 249,000/1,000,000 | episodio=1187 | epsilon=0.104 | loss=0.0098 | Q=1.586
Paso 250,000/1,000,000 | episodio=1191 | epsilon=0.100 | loss=0.0036 | Q=1.563

EVALUACIÓN | paso=250,000 | promedio=250.00 | mediana=270.00 | máximo=370.00

Paso 251,000/1,000,000 | episodio=1194 | epsilon=0.100 | loss=0.0086 | Q=1.661
Paso 252,000/1,000,000 | episodio=1197 | epsilon=0.100 | loss=0.0125 | Q=1.691
Paso 253,000/1,000,000 | episodio=1201 | epsilon=0.100 | loss=0.0192 | Q=1.748
Paso 254,000/1,000,000 | episodio=1205 | epsilon=0.100 | loss=0.0048 | Q=1.705
Paso 255,000/1,000,000 | episodio=1211 | epsilon=0.100 | loss=0.0036 | Q=1.722
Paso 256,000/1,000,000 | episodio=1216 | epsilon=0.100 | loss=0.0082 | Q=1.689
Paso 257,000/1,000,000 | episodio=1220 | epsilon=0.100 | loss=0.0080 | Q=1.671
Paso 258,000/1,000,000 | episodio=1223 | epsilon=0.100 | loss=0.0104 | Q=1.775
Paso 259,000/1,000,000 | episodio=1227 | epsilon=0.100 | loss=0.0073 | Q=1.790
Paso 260,000/1,000,000 | episodio=1230 | epsilon=0.100 | loss=0.0034 | Q=1.413

## Evaluaciones

In [7]:
ruta_evaluaciones_per = Path(
    "../logs/entrenamientos/v5_dqn_per/evaluaciones.csv"
)

df_evaluaciones_per = pd.read_csv(
    ruta_evaluaciones_per
)

df_evaluaciones_per = (
    df_evaluaciones_per
    .sort_values("paso_global")
    .reset_index(drop=True)
)

display(df_evaluaciones_per)

mejor_evaluacion_per = df_evaluaciones_per.loc[
    df_evaluaciones_per["promedio"].idxmax()
]

print("\nMEJOR EVALUACIÓN DE DQN + PER")
print(
    f"Paso: "
    f"{int(mejor_evaluacion_per['paso_global']):,}"
)
print(
    f"Promedio: "
    f"{mejor_evaluacion_per['promedio']:.2f}"
)
print(
    f"Mediana: "
    f"{mejor_evaluacion_per['mediana']:.2f}"
)
print(
    f"Desviación: "
    f"{mejor_evaluacion_per['desviacion']:.2f}"
)
print(
    f"Mínimo: "
    f"{mejor_evaluacion_per['minimo']:.2f}"
)
print(
    f"Máximo: "
    f"{mejor_evaluacion_per['maximo']:.2f}"
)

ruta_mejor_per = Path(
    "../models/v5_dqn_per/mejor_modelo.pt"
)

print(
    "\nCheckpoint del mejor modelo: "
    f"{'OK' if ruta_mejor_per.exists() else 'NO ENCONTRADO'}"
)

    paso_global  promedio  mediana  desviacion  minimo  maximo
0         50000     121.0     60.0  130.015384    40.0   380.0
1        100000     142.0    100.0  119.021007    55.0   375.0
2        150000     160.0    155.0   30.659419   120.0   215.0
3        200000     282.0    215.0  135.889661   130.0   480.0
4        250000     250.0    270.0   84.616783   140.0   370.0
5        300000     295.0    325.0   71.763500   210.0   395.0
6        350000     334.0    270.0  120.764233   240.0   570.0
7        400000     302.0    215.0  139.985714   155.0   525.0
8        450000     329.0    335.0   48.928519   245.0   395.0
9        500000     320.0    300.0  138.419652   120.0   550.0
10       550000     249.0    285.0   93.936149   115.0   365.0
11       600000     320.0    335.0   82.219219   210.0   455.0
12       650000     242.0    195.0  158.795466    60.0   495.0
13       700000     344.0    405.0  138.686697   170.0   515.0
14       750000     330.0    355.0   44.045431   265.0   375.0
15       800000     275.0    275.0   87.578536   145.0   420.0
16       850000     289.0    300.0  136.469777   100.0   495.0
17       900000     158.0    140.0   87.212384    40.0   305.0
18       950000     318.0    260.0  173.280120   170.0   640.0
19      1000000     217.0    265.0  100.677704    65.0   335.0

MEJOR EVALUACIÓN DE DQN + PER
Paso: 700,000
Promedio: 344.00
Mediana: 405.00
Desviación: 138.69
Mínimo: 170.00
Máximo: 515.00

Checkpoint del mejor modelo: OK

In [9]:
import evaluation
importlib.reload(evaluation)

from evaluation import evaluar_modelo

In [10]:
N_EPISODIOS_EVALUACION = 30
SEMILLA_BASE_EVALUACION = 42

checkpoint_per = torch.load(
    ruta_mejor_per,
    map_location=device,
    weights_only=True,
)

mejor_dqn_per = DQN(
    n_acciones=6
).to(device)

mejor_dqn_per.load_state_dict(
    checkpoint_per["modelo_online_state_dict"]
)

mejor_dqn_per.eval()

print(
    f"Checkpoint cargado desde el paso: "
    f"{checkpoint_per['paso']:,}"
)

print(
    "Total de pasos registrado en la configuración: "
    f"{checkpoint_per['config']['total_pasos']:,}"
)

print(
    f"\nEvaluando DQN + PER durante "
    f"{N_EPISODIOS_EVALUACION} episodios...\n"
)

resultados_dqn_per, resumen_dqn_per = evaluar_modelo(
    modelo=mejor_dqn_per,
    config=config_dqn_per,
    device=device,
    n_episodios=N_EPISODIOS_EVALUACION,
    seed_base=SEMILLA_BASE_EVALUACION,
)

df_dqn_per = pd.DataFrame(
    resultados_dqn_per
)

df_dqn_per["agente"] = "DQN + PER"

df_dqn_per = df_dqn_per[
    [
        "agente",
        "episodio",
        "seed",
        "recompensa_total",
        "pasos",
        "terminated",
        "truncated",
    ]
]

print("RESUMEN DE 30 EPISODIOS")

for metrica, valor in resumen_dqn_per.items():
    print(f"{metrica}: {valor:.2f}")

display(df_dqn_per.head(10))

Checkpoint cargado desde el paso: 700,000
Total de pasos registrado en la configuración: 1,000,000

Evaluando DQN + PER durante 30 episodios...

RESUMEN DE 30 EPISODIOS
promedio: 282.00
mediana: 282.50
desviacion: 92.95
minimo: 155.00
maximo: 540.00

      agente  episodio  seed  recompensa_total  pasos  terminated  truncated
0  DQN + PER         0    42             295.0    711        True      False
1  DQN + PER         1    43             280.0    509        True      False
2  DQN + PER         2    44             315.0    618        True      False
3  DQN + PER         3    45             240.0    555        True      False
4  DQN + PER         4    46             245.0    534        True      False
5  DQN + PER         5    47             230.0    528        True      False
6  DQN + PER         6    48             165.0    367        True      False
7  DQN + PER         7    49             400.0    569        True      False
8  DQN + PER         8    50             250.0    522        True      False
9  DQN + PER         9    51             325.0    740        True      False

## Guardar y Comparar

In [11]:
ruta_resultados_per = Path(
    "../logs/evaluacion_dqn_per.csv"
)

df_dqn_per.to_csv(
    ruta_resultados_per,
    index=False,
)

df_dqn_vanilla = pd.read_csv(
    "../logs/evaluacion_dqn_vanilla.csv"
)

df_double_dqn = pd.read_csv(
    "../logs/evaluacion_double_dqn.csv"
)

df_dueling_dqn = pd.read_csv(
    "../logs/evaluacion_dueling_double_dqn.csv"
)

df_modelos_per = pd.concat(
    [
        df_dqn_vanilla,
        df_double_dqn,
        df_dueling_dqn,
        df_dqn_per,
    ],
    ignore_index=True,
)

resumen_modelos_per = (
    df_modelos_per
    .groupby("agente")
    .agg(
        episodios=("recompensa_total", "count"),
        promedio=("recompensa_total", "mean"),
        mediana=("recompensa_total", "median"),
        desviacion=("recompensa_total", "std"),
        minimo=("recompensa_total", "min"),
        maximo=("recompensa_total", "max"),
        pasos_promedio=("pasos", "mean"),
    )
    .round(2)
    .reset_index()
)

display(resumen_modelos_per)

comparacion_per = (
    pd.concat(
        [
            df_dqn_vanilla,
            df_dqn_per,
        ],
        ignore_index=True,
    )
    .pivot(
        index="seed",
        columns="agente",
        values="recompensa_total",
    )
    .dropna()
)

diferencia = (
    comparacion_per["DQN + PER"]
    - comparacion_per["DQN vanilla"]
)

print(
    "Victorias DQN vanilla:",
    (diferencia < 0).sum(),
)

print(
    "Victorias DQN + PER:",
    (diferencia > 0).sum(),
)

print(
    "Empates:",
    (diferencia == 0).sum(),
)

print(
    f"\nResultados guardados en: "
    f"{ruta_resultados_per}"
)

,agente,episodios,promedio,mediana,desviacion,minimo,maximo,pasos_promedio
0,DQN + PER,30,282.00,282.5,94.54,155.0,540.0,569.20
1,DQN vanilla,30,406.67,377.5,139.11,215.0,670.0,705.80
2,Double DQN,30,283.33,262.5,154.85,105.0,925.0,614.73
3,Dueling Double DQN,30,263.33,215.0,112.84,155.0,580.0,597.50

Victorias DQN vanilla: 22
Victorias DQN + PER: 8
Empates: 0

Resultados guardados en: ../logs/evaluacion_dqn_per.csv

## Prueba acumulador n-step

In [12]:
importlib.reload(replay_buffer)

from replay_buffer import NStepAccumulator

acumulador_prueba = NStepAccumulator(
    n_step=3,
    gamma=0.9,
)

transiciones_generadas = []

for paso in range(4):
    observacion = np.array(
        [paso],
        dtype=np.uint8,
    )

    siguiente_observacion = np.array(
        [paso + 1],
        dtype=np.uint8,
    )

    finalizado = paso == 3

    nuevas_transiciones = acumulador_prueba.agregar(
        observacion=observacion,
        accion=paso,
        recompensa=1.0,
        siguiente_observacion=siguiente_observacion,
        finalizado=finalizado,
    )

    transiciones_generadas.extend(
        nuevas_transiciones
    )

print(
    f"Transiciones generadas: "
    f"{len(transiciones_generadas)}"
)

for indice, transicion in enumerate(
    transiciones_generadas
):
    (
        observacion,
        accion,
        recompensa,
        siguiente_observacion,
        finalizado,
    ) = transicion

    print(
        f"{indice}: "
        f"obs={observacion.item()} | "
        f"acción={accion} | "
        f"recompensa={recompensa:.3f} | "
        f"siguiente={siguiente_observacion.item()} | "
        f"finalizado={finalizado}"
    )

recompensas_obtenidas = np.array(
    [
        transicion[2]
        for transicion in transiciones_generadas
    ]
)

recompensas_esperadas = np.array(
    [
        1 + 0.9 + 0.9**2,
        1 + 0.9 + 0.9**2,
        1 + 0.9,
        1.0,
    ]
)

assert len(transiciones_generadas) == 4

assert np.allclose(
    recompensas_obtenidas,
    recompensas_esperadas,
)

assert len(acumulador_prueba) == 0

print(
    "\nEl acumulador n-step funciona correctamente."
)

Transiciones generadas: 4
0: obs=0 | acción=0 | recompensa=2.710 | siguiente=3 | finalizado=False
1: obs=1 | acción=1 | recompensa=2.710 | siguiente=4 | finalizado=True
2: obs=2 | acción=2 | recompensa=1.900 | siguiente=4 | finalizado=True
3: obs=3 | acción=3 | recompensa=1.000 | siguiente=4 | finalizado=True

El acumulador n-step funciona correctamente.

In [13]:
import gc
import importlib
import torch

import replay_buffer
import train
import models

importlib.reload(replay_buffer)
importlib.reload(train)
importlib.reload(models)

from models import DQN
from train import ConfigDQN, entrenar_dqn

device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "mps" if torch.backends.mps.is_available()
    else "cpu"
)

gc.collect()

if device.type == "mps":
    torch.mps.empty_cache()

config_smoke_n_step = ConfigDQN(
    nombre_experimento="smoke_test_dqn_per_3step",
    total_pasos=2_000,

    gamma=0.99,
    n_step=3,

    usar_per=True,
    per_alpha=0.6,
    per_beta_inicial=0.4,
    per_beta_final=1.0,
    per_pasos_beta=2_000,
    per_epsilon=1e-6,

    capacidad_buffer=2_000,
    inicio_entrenamiento=200,
    batch_size=32,
    frecuencia_entrenamiento=4,
    frecuencia_actualizacion_target=500,

    epsilon_inicial=1.0,
    epsilon_final=0.1,
    pasos_decay_epsilon=1_000,

    frecuencia_log=250,
    frecuencia_evaluacion=2_000,
    episodios_evaluacion=1,
)

resultado_smoke_n_step = entrenar_dqn(
    config=config_smoke_n_step,
    clase_modelo=DQN,
    device=device,
    usar_double_dqn=False,
)

print("\nSMOKE TEST PER + 3-STEP FINALIZADO")
print(
    "Mejor promedio de evaluación: "
    f"{resultado_smoke_n_step['mejor_promedio_evaluacion']:.2f}"
)

Replay buffer: priorizado | alpha=0.6 | beta inicial=0.4
Retorno utilizado: 3-step
Paso 250/2,000 | episodio=1 | epsilon=0.775 | loss=0.0093 | Q=0.062
Paso 500/2,000 | episodio=1 | epsilon=0.550 | loss=0.0222 | Q=0.154
Paso 750/2,000 | episodio=2 | epsilon=0.325 | loss=0.0065 | Q=0.288
Paso 1,000/2,000 | episodio=3 | epsilon=0.100 | loss=0.0168 | Q=0.367
Paso 1,250/2,000 | episodio=4 | epsilon=0.100 | loss=0.0094 | Q=0.480
Paso 1,500/2,000 | episodio=6 | epsilon=0.100 | loss=0.0045 | Q=0.507
Paso 1,750/2,000 | episodio=7 | epsilon=0.100 | loss=0.0057 | Q=0.572
Paso 2,000/2,000 | episodio=8 | epsilon=0.100 | loss=0.0049 | Q=0.557

EVALUACIÓN | paso=2,000 | promedio=75.00 | mediana=75.00 | máximo=75.00


SMOKE TEST PER + 3-STEP FINALIZADO
Mejor promedio de evaluación: 75.00

## Entrenamiento de DQN + PER + 3-step

In [14]:
globals().pop(
    "resultado_smoke_n_step",
    None,
)

gc.collect()

if device.type == "mps":
    torch.mps.empty_cache()

config_dqn_per_3step = ConfigDQN(
    nombre_experimento="v6_dqn_per_3step",
    total_pasos=1_000_000,

    gamma=0.99,
    n_step=3,
    learning_rate=1e-4,
    batch_size=32,
    frecuencia_entrenamiento=4,

    capacidad_buffer=20_000,
    inicio_entrenamiento=10_000,
    frecuencia_actualizacion_target=10_000,
    gradient_clip=10.0,

    epsilon_inicial=1.0,
    epsilon_final=0.1,
    pasos_decay_epsilon=250_000,

    usar_per=True,
    per_alpha=0.6,
    per_beta_inicial=0.4,
    per_beta_final=1.0,
    per_pasos_beta=500_000,
    per_epsilon=1e-6,

    frecuencia_evaluacion=50_000,
    episodios_evaluacion=5,
    seed_evaluacion=1_000,
    frecuencia_log=1_000,

    terminal_on_life_loss=True,
    clip_reward=True,
)

resultado_dqn_per_3step = entrenar_dqn(
    config=config_dqn_per_3step,
    clase_modelo=DQN,
    device=device,
    usar_double_dqn=False,
)

print(
    "\nENTRENAMIENTO DQN + PER + 3-STEP FINALIZADO"
)

print(
    "Mejor promedio de evaluación: "
    f"{resultado_dqn_per_3step['mejor_promedio_evaluacion']:.2f}"
)

Replay buffer: priorizado | alpha=0.6 | beta inicial=0.4
Retorno utilizado: 3-step
Paso 10,000/1,000,000 | episodio=49 | epsilon=0.964 | loss=0.0550 | Q=0.006
Paso 11,000/1,000,000 | episodio=53 | epsilon=0.960 | loss=0.0135 | Q=0.106
Paso 12,000/1,000,000 | episodio=59 | epsilon=0.957 | loss=0.0399 | Q=0.167
Paso 13,000/1,000,000 | episodio=66 | epsilon=0.953 | loss=0.0353 | Q=0.174
Paso 14,000/1,000,000 | episodio=71 | epsilon=0.950 | loss=0.0331 | Q=0.178
Paso 15,000/1,000,000 | episodio=77 | epsilon=0.946 | loss=0.0496 | Q=0.188
Paso 16,000/1,000,000 | episodio=82 | epsilon=0.942 | loss=0.0328 | Q=0.127
Paso 17,000/1,000,000 | episodio=86 | epsilon=0.939 | loss=0.0157 | Q=0.164
Paso 18,000/1,000,000 | episodio=92 | epsilon=0.935 | loss=0.0289 | Q=0.230
Paso 19,000/1,000,000 | episodio=98 | epsilon=0.932 | loss=0.0225 | Q=0.171
Paso 20,000/1,000,000 | episodio=103 | epsilon=0.928 | loss=0.0220 | Q=0.208
Paso 21,000/1,000,000 | episodio=108 | epsilon=0.924 | loss=0.0228 | Q=0.422
Paso 22,000/1,000,000 | episodio=114 | epsilon=0.921 | loss=0.0272 | Q=0.435
Paso 23,000/1,000,000 | episodio=119 | epsilon=0.917 | loss=0.0207 | Q=0.321
Paso 24,000/1,000,000 | episodio=125 | epsilon=0.914 | loss=0.0238 | Q=0.294
Paso 25,000/1,000,000 | episodio=130 | epsilon=0.910 | loss=0.0236 | Q=0.361
Paso 26,000/1,000,000 | episodio=134 | epsilon=0.906 | loss=0.0212 | Q=0.398
Paso 27,000/1,000,000 | episodio=139 | epsilon=0.903 | loss=0.0144 | Q=0.350
Paso 28,000/1,000,000 | episodio=144 | epsilon=0.899 | loss=0.0162 | Q=0.310
Paso 29,000/1,000,000 | episodio=149 | epsilon=0.896 | loss=0.0135 | Q=0.394
Paso 30,000/1,000,000 | episodio=154 | epsilon=0.892 | loss=0.0068 | Q=0.349
Paso 31,000/1,000,000 | episodio=159 | epsilon=0.888 | loss=0.0065 | Q=0.436
Paso 32,000/1,000,000 | episodio=165 | epsilon=0.885 | loss=0.0307 | Q=0.525
Paso 33,000/1,000,000 | episodio=169 | epsilon=0.881 | loss=0.0187 | Q=0.518
Paso 34,000/1,000,000 | episodio=174 | epsilon=0.878 | loss=0.0248 | Q=0.519
Paso 35,000/1,000,000 | episodio=179 | epsilon=0.874 | loss=0.0123 | Q=0.515
Paso 36,000/1,000,000 | episodio=183 | epsilon=0.870 | loss=0.0221 | Q=0.423
Paso 37,000/1,000,000 | episodio=190 | epsilon=0.867 | loss=0.0128 | Q=0.410
Paso 38,000/1,000,000 | episodio=194 | epsilon=0.863 | loss=0.0185 | Q=0.518
Paso 39,000/1,000,000 | episodio=199 | epsilon=0.860 | loss=0.0154 | Q=0.473
Paso 40,000/1,000,000 | episodio=205 | epsilon=0.856 | loss=0.0151 | Q=0.473
Paso 41,000/1,000,000 | episodio=211 | epsilon=0.852 | loss=0.0257 | Q=0.636
Paso 42,000/1,000,000 | episodio=215 | epsilon=0.849 | loss=0.0231 | Q=0.605
Paso 43,000/1,000,000 | episodio=220 | epsilon=0.845 | loss=0.0388 | Q=0.530
Paso 44,000/1,000,000 | episodio=224 | epsilon=0.842 | loss=0.0063 | Q=0.591
Paso 45,000/1,000,000 | episodio=227 | epsilon=0.838 | loss=0.0207 | Q=0.551
Paso 46,000/1,000,000 | episodio=231 | epsilon=0.834 | loss=0.0133 | Q=0.610
Paso 47,000/1,000,000 | episodio=237 | epsilon=0.831 | loss=0.0200 | Q=0.665
Paso 48,000/1,000,000 | episodio=243 | epsilon=0.827 | loss=0.0127 | Q=0.680
Paso 49,000/1,000,000 | episodio=247 | epsilon=0.824 | loss=0.0095 | Q=0.547
Paso 50,000/1,000,000 | episodio=252 | epsilon=0.820 | loss=0.0228 | Q=0.690

EVALUACIÓN | paso=50,000 | promedio=224.00 | mediana=215.00 | máximo=250.00

Paso 51,000/1,000,000 | episodio=257 | epsilon=0.816 | loss=0.0131 | Q=0.836
Paso 52,000/1,000,000 | episodio=262 | epsilon=0.813 | loss=0.0167 | Q=0.687
Paso 53,000/1,000,000 | episodio=268 | epsilon=0.809 | loss=0.0133 | Q=0.710
Paso 54,000/1,000,000 | episodio=274 | epsilon=0.806 | loss=0.0353 | Q=0.732
Paso 55,000/1,000,000 | episodio=278 | epsilon=0.802 | loss=0.0171 | Q=0.886
Paso 56,000/1,000,000 | episodio=285 | epsilon=0.798 | loss=0.0205 | Q=0.795
Paso 57,000/1,000,000 | episodio=289 | epsilon=0.795 | loss=0.0118 | Q=0.695
Paso 58,000/1,000,000 | episodio=293 | epsilon=0.791 | loss=0.0193 | Q=0.737
Paso 59,000/1,000,000 | episodio=297 | epsilon=0.788 | loss=0.0175 | Q=0.581
Paso 60,000/1,000,000 | episodio=301 | epsilon=0.784 | loss=0.0099 | Q=0.576
Paso 61,000/1,000,000 | episodio=307 | epsilon=0.780 | loss=0.0206 | Q=0.854
Paso 62,000/1,000,000 | episodio=311 | epsilon=0.777 | loss=0.0221 | Q=0.855
Paso 63,000/1,000,000 | episodio=316 | epsilon=0.773 | loss=0.0191 | Q=0.841
Paso 64,000/1,000,000 | episodio=320 | epsilon=0.770 | loss=0.0186 | Q=0.865
Paso 65,000/1,000,000 | episodio=326 | epsilon=0.766 | loss=0.0138 | Q=0.777
Paso 66,000/1,000,000 | episodio=333 | epsilon=0.762 | loss=0.0161 | Q=0.857
Paso 67,000/1,000,000 | episodio=340 | epsilon=0.759 | loss=0.0185 | Q=0.795
Paso 68,000/1,000,000 | episodio=344 | epsilon=0.755 | loss=0.0183 | Q=0.856
Paso 69,000/1,000,000 | episodio=350 | epsilon=0.752 | loss=0.0262 | Q=0.743
Paso 70,000/1,000,000 | episodio=355 | epsilon=0.748 | loss=0.0080 | Q=0.685
Paso 71,000/1,000,000 | episodio=359 | epsilon=0.744 | loss=0.0157 | Q=0.802
Paso 72,000/1,000,000 | episodio=364 | epsilon=0.741 | loss=0.0230 | Q=0.995
Paso 73,000/1,000,000 | episodio=370 | epsilon=0.737 | loss=0.0103 | Q=0.811
Paso 74,000/1,000,000 | episodio=376 | epsilon=0.734 | loss=0.0222 | Q=0.856
Paso 75,000/1,000,000 | episodio=382 | epsilon=0.730 | loss=0.0279 | Q=0.797
Paso 76,000/1,000,000 | episodio=388 | epsilon=0.726 | loss=0.0176 | Q=0.753
Paso 77,000/1,000,000 | episodio=395 | epsilon=0.723 | loss=0.0172 | Q=0.804
Paso 78,000/1,000,000 | episodio=400 | epsilon=0.719 | loss=0.0219 | Q=0.994
Paso 79,000/1,000,000 | episodio=406 | epsilon=0.716 | loss=0.0129 | Q=0.863
Paso 80,000/1,000,000 | episodio=411 | epsilon=0.712 | loss=0.0111 | Q=0.722
Paso 81,000/1,000,000 | episodio=416 | epsilon=0.708 | loss=0.0174 | Q=1.032
Paso 82,000/1,000,000 | episodio=421 | epsilon=0.705 | loss=0.0112 | Q=0.882
Paso 83,000/1,000,000 | episodio=426 | epsilon=0.701 | loss=0.0182 | Q=1.057
Paso 84,000/1,000,000 | episodio=430 | epsilon=0.698 | loss=0.0148 | Q=0.928
Paso 85,000/1,000,000 | episodio=435 | epsilon=0.694 | loss=0.0101 | Q=1.007
Paso 86,000/1,000,000 | episodio=441 | epsilon=0.690 | loss=0.0141 | Q=0.772
Paso 87,000/1,000,000 | episodio=446 | epsilon=0.687 | loss=0.0092 | Q=1.023
Paso 88,000/1,000,000 | episodio=452 | epsilon=0.683 | loss=0.0201 | Q=0.929
Paso 89,000/1,000,000 | episodio=457 | epsilon=0.680 | loss=0.0097 | Q=1.098
Paso 90,000/1,000,000 | episodio=462 | epsilon=0.676 | loss=0.0243 | Q=0.915
Paso 91,000/1,000,000 | episodio=466 | epsilon=0.672 | loss=0.0207 | Q=0.992
Paso 92,000/1,000,000 | episodio=472 | epsilon=0.669 | loss=0.0109 | Q=1.168
Paso 93,000/1,000,000 | episodio=476 | epsilon=0.665 | loss=0.0174 | Q=1.150
Paso 94,000/1,000,000 | episodio=482 | epsilon=0.662 | loss=0.0190 | Q=1.006
Paso 95,000/1,000,000 | episodio=487 | epsilon=0.658 | loss=0.0322 | Q=1.004
Paso 96,000/1,000,000 | episodio=492 | epsilon=0.654 | loss=0.0341 | Q=0.905
Paso 97,000/1,000,000 | episodio=496 | epsilon=0.651 | loss=0.0127 | Q=0.893
Paso 98,000/1,000,000 | episodio=501 | epsilon=0.647 | loss=0.0277 | Q=1.040
Paso 99,000/1,000,000 | episodio=506 | epsilon=0.644 | loss=0.0074 | Q=1.040
Paso 100,000/1,000,000 | episodio=509 | epsilon=0.640 | loss=0.0182 | Q=1.354

EVALUACIÓN | paso=100,000 | promedio=138.00 | mediana=135.00 | máximo=195.00

Paso 101,000/1,000,000 | episodio=515 | epsilon=0.636 | loss=0.0163 | Q=1.059
Paso 102,000/1,000,000 | episodio=519 | epsilon=0.633 | loss=0.0128 | Q=1.062
Paso 103,000/1,000,000 | episodio=523 | epsilon=0.629 | loss=0.0222 | Q=1.300
Paso 104,000/1,000,000 | episodio=526 | epsilon=0.626 | loss=0.0073 | Q=1.075
Paso 105,000/1,000,000 | episodio=530 | epsilon=0.622 | loss=0.0205 | Q=1.077
Paso 106,000/1,000,000 | episodio=537 | epsilon=0.618 | loss=0.0274 | Q=0.996
Paso 107,000/1,000,000 | episodio=543 | epsilon=0.615 | loss=0.0112 | Q=1.206
Paso 108,000/1,000,000 | episodio=549 | epsilon=0.611 | loss=0.0137 | Q=1.230
Paso 109,000/1,000,000 | episodio=552 | epsilon=0.608 | loss=0.0124 | Q=1.099
Paso 110,000/1,000,000 | episodio=554 | epsilon=0.604 | loss=0.0161 | Q=1.198
Paso 111,000/1,000,000 | episodio=557 | epsilon=0.600 | loss=0.0174 | Q=1.352
Paso 112,000/1,000,000 | episodio=562 | epsilon=0.597 | loss=0.0111 | Q=1.270
Paso 113,000/1,000,000 | episodio=566 | epsilon=0.593 | loss=0.0161 | Q=1.213
Paso 114,000/1,000,000 | episodio=572 | epsilon=0.590 | loss=0.0204 | Q=1.062
Paso 115,000/1,000,000 | episodio=577 | epsilon=0.586 | loss=0.0100 | Q=1.120
Paso 116,000/1,000,000 | episodio=581 | epsilon=0.582 | loss=0.0241 | Q=1.214
Paso 117,000/1,000,000 | episodio=586 | epsilon=0.579 | loss=0.0177 | Q=1.389
Paso 118,000/1,000,000 | episodio=591 | epsilon=0.575 | loss=0.0128 | Q=1.330
Paso 119,000/1,000,000 | episodio=596 | epsilon=0.572 | loss=0.0094 | Q=1.254
Paso 120,000/1,000,000 | episodio=600 | epsilon=0.568 | loss=0.0088 | Q=1.106
Paso 121,000/1,000,000 | episodio=604 | epsilon=0.564 | loss=0.0043 | Q=1.365
Paso 122,000/1,000,000 | episodio=609 | epsilon=0.561 | loss=0.0137 | Q=1.179
Paso 123,000/1,000,000 | episodio=613 | epsilon=0.557 | loss=0.0080 | Q=1.611
Paso 124,000/1,000,000 | episodio=617 | epsilon=0.554 | loss=0.0156 | Q=1.255
Paso 125,000/1,000,000 | episodio=621 | epsilon=0.550 | loss=0.0142 | Q=1.374
Paso 126,000/1,000,000 | episodio=627 | epsilon=0.546 | loss=0.0106 | Q=1.544
Paso 127,000/1,000,000 | episodio=633 | epsilon=0.543 | loss=0.0196 | Q=1.393
Paso 128,000/1,000,000 | episodio=637 | epsilon=0.539 | loss=0.0143 | Q=1.332
Paso 129,000/1,000,000 | episodio=641 | epsilon=0.536 | loss=0.0233 | Q=1.524
Paso 130,000/1,000,000 | episodio=645 | epsilon=0.532 | loss=0.0098 | Q=1.385
Paso 131,000/1,000,000 | episodio=649 | epsilon=0.528 | loss=0.0108 | Q=1.516
Paso 132,000/1,000,000 | episodio=653 | epsilon=0.525 | loss=0.0125 | Q=1.343
Paso 133,000/1,000,000 | episodio=658 | epsilon=0.521 | loss=0.0097 | Q=1.454
Paso 134,000/1,000,000 | episodio=662 | epsilon=0.518 | loss=0.0203 | Q=1.667
Paso 135,000/1,000,000 | episodio=666 | epsilon=0.514 | loss=0.0147 | Q=1.373
Paso 136,000/1,000,000 | episodio=671 | epsilon=0.510 | loss=0.0183 | Q=1.602
Paso 137,000/1,000,000 | episodio=676 | epsilon=0.507 | loss=0.0082 | Q=1.491
Paso 138,000/1,000,000 | episodio=681 | epsilon=0.503 | loss=0.0080 | Q=1.120
Paso 139,000/1,000,000 | episodio=684 | epsilon=0.500 | loss=0.0119 | Q=1.476
Paso 140,000/1,000,000 | episodio=687 | epsilon=0.496 | loss=0.0131 | Q=1.281
Paso 141,000/1,000,000 | episodio=691 | epsilon=0.492 | loss=0.0137 | Q=1.462
Paso 142,000/1,000,000 | episodio=695 | epsilon=0.489 | loss=0.0183 | Q=1.439
Paso 143,000/1,000,000 | episodio=697 | epsilon=0.485 | loss=0.0248 | Q=1.575
Paso 144,000/1,000,000 | episodio=699 | epsilon=0.482 | loss=0.0061 | Q=1.551
Paso 145,000/1,000,000 | episodio=704 | epsilon=0.478 | loss=0.0115 | Q=1.552
Paso 146,000/1,000,000 | episodio=708 | epsilon=0.474 | loss=0.0109 | Q=1.758
Paso 147,000/1,000,000 | episodio=712 | epsilon=0.471 | loss=0.0153 | Q=1.577
Paso 148,000/1,000,000 | episodio=715 | epsilon=0.467 | loss=0.0132 | Q=1.469
Paso 149,000/1,000,000 | episodio=719 | epsilon=0.464 | loss=0.0068 | Q=1.545
Paso 150,000/1,000,000 | episodio=722 | epsilon=0.460 | loss=0.0106 | Q=1.511

EVALUACIÓN | paso=150,000 | promedio=248.00 | mediana=270.00 | máximo=285.00

Paso 151,000/1,000,000 | episodio=724 | epsilon=0.456 | loss=0.0112 | Q=1.521
Paso 152,000/1,000,000 | episodio=728 | epsilon=0.453 | loss=0.0114 | Q=1.556
Paso 153,000/1,000,000 | episodio=732 | epsilon=0.449 | loss=0.0213 | Q=1.781
Paso 154,000/1,000,000 | episodio=736 | epsilon=0.446 | loss=0.0099 | Q=1.590
Paso 155,000/1,000,000 | episodio=739 | epsilon=0.442 | loss=0.0147 | Q=1.498
Paso 156,000/1,000,000 | episodio=742 | epsilon=0.438 | loss=0.0207 | Q=1.638
Paso 157,000/1,000,000 | episodio=746 | epsilon=0.435 | loss=0.0176 | Q=1.592
Paso 158,000/1,000,000 | episodio=750 | epsilon=0.431 | loss=0.0136 | Q=1.692
Paso 159,000/1,000,000 | episodio=755 | epsilon=0.428 | loss=0.0107 | Q=1.293
Paso 160,000/1,000,000 | episodio=760 | epsilon=0.424 | loss=0.0078 | Q=1.974
Paso 161,000/1,000,000 | episodio=764 | epsilon=0.420 | loss=0.0146 | Q=1.575
Paso 162,000/1,000,000 | episodio=768 | epsilon=0.417 | loss=0.0163 | Q=1.853
Paso 163,000/1,000,000 | episodio=771 | epsilon=0.413 | loss=0.0149 | Q=1.746
Paso 164,000/1,000,000 | episodio=772 | epsilon=0.410 | loss=0.0200 | Q=1.527
Paso 165,000/1,000,000 | episodio=775 | epsilon=0.406 | loss=0.0151 | Q=1.790
Paso 166,000/1,000,000 | episodio=779 | epsilon=0.402 | loss=0.0105 | Q=1.690
Paso 167,000/1,000,000 | episodio=781 | epsilon=0.399 | loss=0.0116 | Q=1.720
Paso 168,000/1,000,000 | episodio=787 | epsilon=0.395 | loss=0.0078 | Q=1.757
Paso 169,000/1,000,000 | episodio=790 | epsilon=0.392 | loss=0.0094 | Q=1.712
Paso 170,000/1,000,000 | episodio=793 | epsilon=0.388 | loss=0.0100 | Q=1.755
Paso 171,000/1,000,000 | episodio=797 | epsilon=0.384 | loss=0.0246 | Q=1.826
Paso 172,000/1,000,000 | episodio=800 | epsilon=0.381 | loss=0.0191 | Q=1.779
Paso 173,000/1,000,000 | episodio=804 | epsilon=0.377 | loss=0.0190 | Q=1.880
Paso 174,000/1,000,000 | episodio=808 | epsilon=0.374 | loss=0.0165 | Q=1.974
Paso 175,000/1,000,000 | episodio=813 | epsilon=0.370 | loss=0.0153 | Q=1.553
Paso 176,000/1,000,000 | episodio=818 | epsilon=0.366 | loss=0.0031 | Q=1.513
Paso 177,000/1,000,000 | episodio=823 | epsilon=0.363 | loss=0.0064 | Q=1.720
Paso 178,000/1,000,000 | episodio=826 | epsilon=0.359 | loss=0.0116 | Q=1.911
Paso 179,000/1,000,000 | episodio=831 | epsilon=0.356 | loss=0.0132 | Q=1.553
Paso 180,000/1,000,000 | episodio=833 | epsilon=0.352 | loss=0.0111 | Q=1.791
Paso 181,000/1,000,000 | episodio=836 | epsilon=0.348 | loss=0.0215 | Q=1.826
Paso 182,000/1,000,000 | episodio=841 | epsilon=0.345 | loss=0.0147 | Q=1.740
Paso 183,000/1,000,000 | episodio=844 | epsilon=0.341 | loss=0.0211 | Q=1.541
Paso 184,000/1,000,000 | episodio=848 | epsilon=0.338 | loss=0.0162 | Q=1.993
Paso 185,000/1,000,000 | episodio=850 | epsilon=0.334 | loss=0.0249 | Q=1.960
Paso 186,000/1,000,000 | episodio=852 | epsilon=0.330 | loss=0.0107 | Q=2.036
Paso 187,000/1,000,000 | episodio=856 | epsilon=0.327 | loss=0.0267 | Q=2.089
Paso 188,000/1,000,000 | episodio=861 | epsilon=0.323 | loss=0.0168 | Q=1.829
Paso 189,000/1,000,000 | episodio=865 | epsilon=0.320 | loss=0.0087 | Q=2.016
Paso 190,000/1,000,000 | episodio=871 | epsilon=0.316 | loss=0.0095 | Q=1.657
Paso 191,000/1,000,000 | episodio=873 | epsilon=0.312 | loss=0.0128 | Q=1.890
Paso 192,000/1,000,000 | episodio=877 | epsilon=0.309 | loss=0.0193 | Q=1.765
Paso 193,000/1,000,000 | episodio=881 | epsilon=0.305 | loss=0.0174 | Q=2.142
Paso 194,000/1,000,000 | episodio=885 | epsilon=0.302 | loss=0.0118 | Q=2.160
Paso 195,000/1,000,000 | episodio=890 | epsilon=0.298 | loss=0.0320 | Q=2.147
Paso 196,000/1,000,000 | episodio=894 | epsilon=0.294 | loss=0.0173 | Q=2.126
Paso 197,000/1,000,000 | episodio=898 | epsilon=0.291 | loss=0.0123 | Q=1.945
Paso 198,000/1,000,000 | episodio=902 | epsilon=0.287 | loss=0.0214 | Q=2.034
Paso 199,000/1,000,000 | episodio=906 | epsilon=0.284 | loss=0.0102 | Q=1.895
Paso 200,000/1,000,000 | episodio=910 | epsilon=0.280 | loss=0.0088 | Q=2.008

EVALUACIÓN | paso=200,000 | promedio=314.00 | mediana=250.00 | máximo=640.00

Paso 201,000/1,000,000 | episodio=913 | epsilon=0.276 | loss=0.0150 | Q=2.118
Paso 202,000/1,000,000 | episodio=916 | epsilon=0.273 | loss=0.0089 | Q=2.163
Paso 203,000/1,000,000 | episodio=920 | epsilon=0.269 | loss=0.0113 | Q=1.801
Paso 204,000/1,000,000 | episodio=923 | epsilon=0.266 | loss=0.0164 | Q=1.985
Paso 205,000/1,000,000 | episodio=926 | epsilon=0.262 | loss=0.0083 | Q=1.857
Paso 206,000/1,000,000 | episodio=929 | epsilon=0.258 | loss=0.0139 | Q=1.620
Paso 207,000/1,000,000 | episodio=932 | epsilon=0.255 | loss=0.0144 | Q=2.019
Paso 208,000/1,000,000 | episodio=934 | epsilon=0.251 | loss=0.0077 | Q=2.124
Paso 209,000/1,000,000 | episodio=937 | epsilon=0.248 | loss=0.0115 | Q=1.768
Paso 210,000/1,000,000 | episodio=940 | epsilon=0.244 | loss=0.0249 | Q=1.996
Paso 211,000/1,000,000 | episodio=943 | epsilon=0.240 | loss=0.0238 | Q=2.145
Paso 212,000/1,000,000 | episodio=945 | epsilon=0.237 | loss=0.0316 | Q=1.979
Paso 213,000/1,000,000 | episodio=948 | epsilon=0.233 | loss=0.0117 | Q=2.145
Paso 214,000/1,000,000 | episodio=951 | epsilon=0.230 | loss=0.0200 | Q=1.749
Paso 215,000/1,000,000 | episodio=954 | epsilon=0.226 | loss=0.0308 | Q=1.933
Paso 216,000/1,000,000 | episodio=957 | epsilon=0.222 | loss=0.0084 | Q=1.787
Paso 217,000/1,000,000 | episodio=959 | epsilon=0.219 | loss=0.0196 | Q=2.099
Paso 218,000/1,000,000 | episodio=963 | epsilon=0.215 | loss=0.0068 | Q=2.242
Paso 219,000/1,000,000 | episodio=966 | epsilon=0.212 | loss=0.0041 | Q=2.024
Paso 220,000/1,000,000 | episodio=968 | epsilon=0.208 | loss=0.0146 | Q=1.832
Paso 221,000/1,000,000 | episodio=971 | epsilon=0.204 | loss=0.0276 | Q=2.160
Paso 222,000/1,000,000 | episodio=976 | epsilon=0.201 | loss=0.0100 | Q=1.960
Paso 223,000/1,000,000 | episodio=978 | epsilon=0.197 | loss=0.0223 | Q=2.071
Paso 224,000/1,000,000 | episodio=983 | epsilon=0.194 | loss=0.0074 | Q=1.963
Paso 225,000/1,000,000 | episodio=986 | epsilon=0.190 | loss=0.0033 | Q=1.855
Paso 226,000/1,000,000 | episodio=991 | epsilon=0.186 | loss=0.0216 | Q=2.356
Paso 227,000/1,000,000 | episodio=992 | epsilon=0.183 | loss=0.0147 | Q=1.978
Paso 228,000/1,000,000 | episodio=997 | epsilon=0.179 | loss=0.0164 | Q=2.180
Paso 229,000/1,000,000 | episodio=1001 | epsilon=0.176 | loss=0.0229 | Q=2.034
Paso 230,000/1,000,000 | episodio=1004 | epsilon=0.172 | loss=0.0158 | Q=2.082
Paso 231,000/1,000,000 | episodio=1008 | epsilon=0.168 | loss=0.0201 | Q=2.006
Paso 232,000/1,000,000 | episodio=1011 | epsilon=0.165 | loss=0.0185 | Q=2.274
Paso 233,000/1,000,000 | episodio=1015 | epsilon=0.161 | loss=0.0194 | Q=2.127
Paso 234,000/1,000,000 | episodio=1017 | epsilon=0.158 | loss=0.0153 | Q=2.216
Paso 235,000/1,000,000 | episodio=1021 | epsilon=0.154 | loss=0.0204 | Q=2.115
Paso 236,000/1,000,000 | episodio=1024 | epsilon=0.150 | loss=0.0228 | Q=2.322
Paso 237,000/1,000,000 | episodio=1027 | epsilon=0.147 | loss=0.0136 | Q=2.124
Paso 238,000/1,000,000 | episodio=1031 | epsilon=0.143 | loss=0.0087 | Q=2.255
Paso 239,000/1,000,000 | episodio=1035 | epsilon=0.140 | loss=0.0164 | Q=2.442
Paso 240,000/1,000,000 | episodio=1039 | epsilon=0.136 | loss=0.0103 | Q=2.273
Paso 241,000/1,000,000 | episodio=1041 | epsilon=0.132 | loss=0.0132 | Q=2.419
Paso 242,000/1,000,000 | episodio=1045 | epsilon=0.129 | loss=0.0238 | Q=2.090
Paso 243,000/1,000,000 | episodio=1047 | epsilon=0.125 | loss=0.0135 | Q=1.961
Paso 244,000/1,000,000 | episodio=1050 | epsilon=0.122 | loss=0.0133 | Q=2.632
Paso 245,000/1,000,000 | episodio=1051 | epsilon=0.118 | loss=0.0145 | Q=2.142
Paso 246,000/1,000,000 | episodio=1054 | epsilon=0.114 | loss=0.0042 | Q=2.247
Paso 247,000/1,000,000 | episodio=1057 | epsilon=0.111 | loss=0.0127 | Q=2.162
Paso 248,000/1,000,000 | episodio=1061 | epsilon=0.107 | loss=0.0301 | Q=2.195
Paso 249,000/1,000,000 | episodio=1064 | epsilon=0.104 | loss=0.0238 | Q=2.322
Paso 250,000/1,000,000 | episodio=1067 | epsilon=0.100 | loss=0.0171 | Q=2.401

EVALUACIÓN | paso=250,000 | promedio=333.00 | mediana=300.00 | máximo=545.00

Paso 251,000/1,000,000 | episodio=1070 | epsilon=0.100 | loss=0.0357 | Q=2.473
Paso 252,000/1,000,000 | episodio=1074 | epsilon=0.100 | loss=0.0260 | Q=2.563
Paso 253,000/1,000,000 | episodio=1077 | epsilon=0.100 | loss=0.0251 | Q=2.541
Paso 254,000/1,000,000 | episodio=1079 | epsilon=0.100 | loss=0.0144 | Q=2.572
Paso 255,000/1,000,000 | episodio=1083 | epsilon=0.100 | loss=0.0171 | Q=2.158
Paso 256,000/1,000,000 | episodio=1085 | epsilon=0.100 | loss=0.0134 | Q=2.116
Paso 257,000/1,000,000 | episodio=1087 | epsilon=0.100 | loss=0.0388 | Q=2.169
Paso 258,000/1,000,000 | episodio=1091 | epsilon=0.100 | loss=0.0289 | Q=2.206
Paso 259,000/1,000,000 | episodio=1095 | epsilon=0.100 | loss=0.0119 | Q=2.358
Paso 260,000/1,000,000 | episodio=1099 | epsilon=0.100 | loss=0.0120 | Q=2.514

In [15]:
from pathlib import Path
import pandas as pd

ruta_evaluaciones_3step = Path(
    "../logs/entrenamientos/"
    "v6_dqn_per_3step/evaluaciones.csv"
)

df_evaluaciones_3step = pd.read_csv(
    ruta_evaluaciones_3step
)

df_evaluaciones_3step = (
    df_evaluaciones_3step
    .sort_values("paso_global")
    .reset_index(drop=True)
)

display(df_evaluaciones_3step)

mejor_evaluacion_3step = (
    df_evaluaciones_3step.loc[
        df_evaluaciones_3step["promedio"].idxmax()
    ]
)

print("\nMEJOR EVALUACIÓN DE DQN + PER + 3-STEP")
print(
    f"Paso: "
    f"{int(mejor_evaluacion_3step['paso_global']):,}"
)
print(
    f"Promedio: "
    f"{mejor_evaluacion_3step['promedio']:.2f}"
)
print(
    f"Mediana: "
    f"{mejor_evaluacion_3step['mediana']:.2f}"
)
print(
    f"Desviación: "
    f"{mejor_evaluacion_3step['desviacion']:.2f}"
)
print(
    f"Mínimo: "
    f"{mejor_evaluacion_3step['minimo']:.2f}"
)
print(
    f"Máximo: "
    f"{mejor_evaluacion_3step['maximo']:.2f}"
)

ruta_mejor_3step = Path(
    "../models/v6_dqn_per_3step/mejor_modelo.pt"
)

print(
    "\nCheckpoint del mejor modelo: "
    f"{'OK' if ruta_mejor_3step.exists() else 'NO ENCONTRADO'}"
)

    paso_global  promedio  mediana  desviacion  minimo  maximo
0         50000     224.0    215.0   19.849433   200.0   250.0
1        100000     138.0    135.0   41.904654    70.0   195.0
2        150000     248.0    270.0   38.807216   180.0   285.0
3        200000     314.0    250.0  165.571737   190.0   640.0
4        250000     333.0    300.0  115.697882   195.0   545.0
5        300000     404.0    285.0  206.746221   225.0   770.0
6        350000     254.0    265.0   51.029403   170.0   325.0
7        400000     431.0    330.0  177.380946   320.0   780.0
8        450000     412.0    435.0   70.327804   320.0   500.0
9        500000     347.0    280.0  118.473626   235.0   510.0
10       550000     378.0    400.0   78.012819   235.0   470.0
11       600000     355.0    360.0   78.930349   240.0   485.0
12       650000     392.0    415.0   78.204859   255.0   480.0
13       700000     475.0    510.0  123.935467   280.0   610.0
14       750000     376.0    325.0   97.077289   265.0   495.0
15       800000     444.0    450.0   92.919320   305.0   555.0
16       850000     402.0    380.0  105.952820   285.0   600.0
17       900000     433.0    415.0   67.424031   365.0   550.0
18       950000     431.0    420.0   88.283634   315.0   575.0
19      1000000     381.0    385.0  114.166545   220.0   515.0

MEJOR EVALUACIÓN DE DQN + PER + 3-STEP
Paso: 700,000
Promedio: 475.00
Mediana: 510.00
Desviación: 123.94
Mínimo: 280.00
Máximo: 610.00

Checkpoint del mejor modelo: OK