In [1]:
import sys
import gc
import importlib
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt
import seaborn as sns

sys.path.append("../src")

import models
import replay_buffer
import train
import evaluation

importlib.reload(models)
importlib.reload(replay_buffer)
importlib.reload(train)
importlib.reload(evaluation)

from models import DQN
from train import ConfigDQN, entrenar_dqn
from evaluation import evaluar_modelo

device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "mps" if torch.backends.mps.is_available()
    else "cpu"
)

print(f"Dispositivo: {device}")

Dispositivo: mps

# Ajuste de hiperparámetros de DQN + PER + n-step

En este notebook se analiza el efecto de dos hiperparámetros:

- El grado de priorización del replay buffer, controlado por `per_alpha`.
- El número de pasos utilizados para acumular recompensas, controlado por `n_step`.

Los demás hiperparámetros se mantendrán constantes para realizar una comparación controlada.

In [2]:
import gc

# Liberar modelos grandes que ya no necesitamos en memoria
objetos_temporales = [
    "resultado_dqn_per_3step",
    "mejor_dqn_per_3step",
    "checkpoint_3step",
]

for nombre in objetos_temporales:
    globals().pop(nombre, None)

gc.collect()

if device.type == "mps":
    torch.mps.empty_cache()

config_per_alpha04_3step = ConfigDQN(
    nombre_experimento="v7_dqn_per_a04_3step",
    total_pasos=1_000_000,

    seed=42,
    gamma=0.99,
    n_step=3,
    learning_rate=1e-4,
    batch_size=32,
    frecuencia_entrenamiento=4,

    capacidad_buffer=20_000,
    inicio_entrenamiento=10_000,
    frecuencia_actualizacion_target=10_000,
    gradient_clip=10.0,

    epsilon_inicial=1.0,
    epsilon_final=0.1,
    pasos_decay_epsilon=250_000,

    usar_per=True,
    per_alpha=0.4,
    per_beta_inicial=0.4,
    per_beta_final=1.0,
    per_pasos_beta=500_000,
    per_epsilon=1e-6,

    frecuencia_evaluacion=50_000,
    episodios_evaluacion=5,
    seed_evaluacion=1_000,
    frecuencia_log=1_000,

    terminal_on_life_loss=True,
    clip_reward=True,
)

resultado_per_alpha04_3step = entrenar_dqn(
    config=config_per_alpha04_3step,
    clase_modelo=DQN,
    device=device,
    usar_double_dqn=False,
)

print(
    "\nENTRENAMIENTO V7 FINALIZADO"
)

print(
    "Mejor promedio de evaluación: "
    f"{resultado_per_alpha04_3step['mejor_promedio_evaluacion']:.2f}"
)

A.L.E: Arcade Learning Environment (version 0.10.1+6a7e0ae)
[Powered by Stella]

Replay buffer: priorizado | alpha=0.4 | beta inicial=0.4
Retorno utilizado: 3-step
Paso 10,000/1,000,000 | episodio=49 | epsilon=0.964 | loss=0.0550 | Q=0.006
Paso 11,000/1,000,000 | episodio=53 | epsilon=0.960 | loss=0.0331 | Q=0.128
Paso 12,000/1,000,000 | episodio=59 | epsilon=0.957 | loss=0.0270 | Q=0.138
Paso 13,000/1,000,000 | episodio=62 | epsilon=0.953 | loss=0.0308 | Q=0.126
Paso 14,000/1,000,000 | episodio=67 | epsilon=0.950 | loss=0.0261 | Q=0.158
Paso 15,000/1,000,000 | episodio=71 | epsilon=0.946 | loss=0.0160 | Q=0.170
Paso 16,000/1,000,000 | episodio=77 | epsilon=0.942 | loss=0.0417 | Q=0.188
Paso 17,000/1,000,000 | episodio=81 | epsilon=0.939 | loss=0.0172 | Q=0.149
Paso 18,000/1,000,000 | episodio=84 | epsilon=0.935 | loss=0.0445 | Q=0.160
Paso 19,000/1,000,000 | episodio=88 | epsilon=0.932 | loss=0.0268 | Q=0.192
Paso 20,000/1,000,000 | episodio=92 | epsilon=0.928 | loss=0.0418 | Q=0.218
Paso 21,000/1,000,000 | episodio=97 | epsilon=0.924 | loss=0.0049 | Q=0.253
Paso 22,000/1,000,000 | episodio=102 | epsilon=0.921 | loss=0.0358 | Q=0.399
Paso 23,000/1,000,000 | episodio=108 | epsilon=0.917 | loss=0.0173 | Q=0.325
Paso 24,000/1,000,000 | episodio=113 | epsilon=0.914 | loss=0.0204 | Q=0.282
Paso 25,000/1,000,000 | episodio=118 | epsilon=0.910 | loss=0.0256 | Q=0.310
Paso 26,000/1,000,000 | episodio=124 | epsilon=0.906 | loss=0.0194 | Q=0.279
Paso 27,000/1,000,000 | episodio=130 | epsilon=0.903 | loss=0.0196 | Q=0.237
Paso 28,000/1,000,000 | episodio=135 | epsilon=0.899 | loss=0.0125 | Q=0.297
Paso 29,000/1,000,000 | episodio=140 | epsilon=0.896 | loss=0.0133 | Q=0.291
Paso 30,000/1,000,000 | episodio=144 | epsilon=0.892 | loss=0.0105 | Q=0.288
Paso 31,000/1,000,000 | episodio=150 | epsilon=0.888 | loss=0.0364 | Q=0.367
Paso 32,000/1,000,000 | episodio=156 | epsilon=0.885 | loss=0.0219 | Q=0.566
Paso 33,000/1,000,000 | episodio=161 | epsilon=0.881 | loss=0.0098 | Q=0.346
Paso 34,000/1,000,000 | episodio=168 | epsilon=0.878 | loss=0.0218 | Q=0.396
Paso 35,000/1,000,000 | episodio=172 | epsilon=0.874 | loss=0.0120 | Q=0.396
Paso 36,000/1,000,000 | episodio=178 | epsilon=0.870 | loss=0.0151 | Q=0.351
Paso 37,000/1,000,000 | episodio=183 | epsilon=0.867 | loss=0.0210 | Q=0.363
Paso 38,000/1,000,000 | episodio=188 | epsilon=0.863 | loss=0.0346 | Q=0.368
Paso 39,000/1,000,000 | episodio=192 | epsilon=0.860 | loss=0.0169 | Q=0.377
Paso 40,000/1,000,000 | episodio=197 | epsilon=0.856 | loss=0.0089 | Q=0.429
Paso 41,000/1,000,000 | episodio=202 | epsilon=0.852 | loss=0.0108 | Q=0.477
Paso 42,000/1,000,000 | episodio=208 | epsilon=0.849 | loss=0.0163 | Q=0.432
Paso 43,000/1,000,000 | episodio=214 | epsilon=0.845 | loss=0.0195 | Q=0.510
Paso 44,000/1,000,000 | episodio=221 | epsilon=0.842 | loss=0.0092 | Q=0.404
Paso 45,000/1,000,000 | episodio=225 | epsilon=0.838 | loss=0.0213 | Q=0.495
Paso 46,000/1,000,000 | episodio=230 | epsilon=0.834 | loss=0.0212 | Q=0.514
Paso 47,000/1,000,000 | episodio=235 | epsilon=0.831 | loss=0.0311 | Q=0.708
Paso 48,000/1,000,000 | episodio=241 | epsilon=0.827 | loss=0.0196 | Q=0.497
Paso 49,000/1,000,000 | episodio=244 | epsilon=0.824 | loss=0.0097 | Q=0.450
Paso 50,000/1,000,000 | episodio=251 | epsilon=0.820 | loss=0.0138 | Q=0.519

EVALUACIÓN | paso=50,000 | promedio=149.00 | mediana=135.00 | máximo=240.00

Paso 51,000/1,000,000 | episodio=257 | epsilon=0.816 | loss=0.0241 | Q=0.673
Paso 52,000/1,000,000 | episodio=261 | epsilon=0.813 | loss=0.0132 | Q=0.589
Paso 53,000/1,000,000 | episodio=267 | epsilon=0.809 | loss=0.0348 | Q=0.601
Paso 54,000/1,000,000 | episodio=269 | epsilon=0.806 | loss=0.0169 | Q=0.752
Paso 55,000/1,000,000 | episodio=274 | epsilon=0.802 | loss=0.0061 | Q=0.544
Paso 56,000/1,000,000 | episodio=280 | epsilon=0.798 | loss=0.0316 | Q=0.575
Paso 57,000/1,000,000 | episodio=286 | epsilon=0.795 | loss=0.0141 | Q=0.621
Paso 58,000/1,000,000 | episodio=293 | epsilon=0.791 | loss=0.0111 | Q=0.542
Paso 59,000/1,000,000 | episodio=296 | epsilon=0.788 | loss=0.0174 | Q=0.521
Paso 60,000/1,000,000 | episodio=301 | epsilon=0.784 | loss=0.0148 | Q=0.733
Paso 61,000/1,000,000 | episodio=307 | epsilon=0.780 | loss=0.0231 | Q=0.728
Paso 62,000/1,000,000 | episodio=314 | epsilon=0.777 | loss=0.0173 | Q=0.783
Paso 63,000/1,000,000 | episodio=320 | epsilon=0.773 | loss=0.0092 | Q=0.778
Paso 64,000/1,000,000 | episodio=325 | epsilon=0.770 | loss=0.0131 | Q=0.700
Paso 65,000/1,000,000 | episodio=331 | epsilon=0.766 | loss=0.0223 | Q=0.598
Paso 66,000/1,000,000 | episodio=337 | epsilon=0.762 | loss=0.0147 | Q=0.637
Paso 67,000/1,000,000 | episodio=344 | epsilon=0.759 | loss=0.0207 | Q=0.619
Paso 68,000/1,000,000 | episodio=349 | epsilon=0.755 | loss=0.0116 | Q=0.725
Paso 69,000/1,000,000 | episodio=354 | epsilon=0.752 | loss=0.0131 | Q=0.632
Paso 70,000/1,000,000 | episodio=359 | epsilon=0.748 | loss=0.0140 | Q=0.717
Paso 71,000/1,000,000 | episodio=365 | epsilon=0.744 | loss=0.0144 | Q=0.759
Paso 72,000/1,000,000 | episodio=372 | epsilon=0.741 | loss=0.0216 | Q=0.696
Paso 73,000/1,000,000 | episodio=378 | epsilon=0.737 | loss=0.0242 | Q=0.809
Paso 74,000/1,000,000 | episodio=386 | epsilon=0.734 | loss=0.0134 | Q=0.739
Paso 75,000/1,000,000 | episodio=391 | epsilon=0.730 | loss=0.0178 | Q=0.741
Paso 76,000/1,000,000 | episodio=398 | epsilon=0.726 | loss=0.0418 | Q=0.711
Paso 77,000/1,000,000 | episodio=405 | epsilon=0.723 | loss=0.0089 | Q=0.670
Paso 78,000/1,000,000 | episodio=412 | epsilon=0.719 | loss=0.0279 | Q=0.741
Paso 79,000/1,000,000 | episodio=419 | epsilon=0.716 | loss=0.0132 | Q=0.612
Paso 80,000/1,000,000 | episodio=426 | epsilon=0.712 | loss=0.0058 | Q=0.695
Paso 81,000/1,000,000 | episodio=431 | epsilon=0.708 | loss=0.0158 | Q=0.851
Paso 82,000/1,000,000 | episodio=435 | epsilon=0.705 | loss=0.0228 | Q=0.890
Paso 83,000/1,000,000 | episodio=442 | epsilon=0.701 | loss=0.0105 | Q=0.903
Paso 84,000/1,000,000 | episodio=446 | epsilon=0.698 | loss=0.0173 | Q=0.878
Paso 85,000/1,000,000 | episodio=449 | epsilon=0.694 | loss=0.0082 | Q=0.880
Paso 86,000/1,000,000 | episodio=454 | epsilon=0.690 | loss=0.0285 | Q=0.864
Paso 87,000/1,000,000 | episodio=457 | epsilon=0.687 | loss=0.0268 | Q=0.816
Paso 88,000/1,000,000 | episodio=462 | epsilon=0.683 | loss=0.0105 | Q=0.806
Paso 89,000/1,000,000 | episodio=467 | epsilon=0.680 | loss=0.0180 | Q=0.868
Paso 90,000/1,000,000 | episodio=472 | epsilon=0.676 | loss=0.0283 | Q=0.915
Paso 91,000/1,000,000 | episodio=475 | epsilon=0.672 | loss=0.0184 | Q=1.072
Paso 92,000/1,000,000 | episodio=478 | epsilon=0.669 | loss=0.0121 | Q=0.845
Paso 93,000/1,000,000 | episodio=482 | epsilon=0.665 | loss=0.0258 | Q=0.853
Paso 94,000/1,000,000 | episodio=485 | epsilon=0.662 | loss=0.0206 | Q=0.975
Paso 95,000/1,000,000 | episodio=490 | epsilon=0.658 | loss=0.0195 | Q=1.047
Paso 96,000/1,000,000 | episodio=496 | epsilon=0.654 | loss=0.0308 | Q=0.887
Paso 97,000/1,000,000 | episodio=502 | epsilon=0.651 | loss=0.0358 | Q=0.891
Paso 98,000/1,000,000 | episodio=506 | epsilon=0.647 | loss=0.0157 | Q=1.170
Paso 99,000/1,000,000 | episodio=510 | epsilon=0.644 | loss=0.0162 | Q=0.951
Paso 100,000/1,000,000 | episodio=516 | epsilon=0.640 | loss=0.0144 | Q=0.999

EVALUACIÓN | paso=100,000 | promedio=191.00 | mediana=160.00 | máximo=330.00

Paso 101,000/1,000,000 | episodio=518 | epsilon=0.636 | loss=0.0176 | Q=1.145
Paso 102,000/1,000,000 | episodio=522 | epsilon=0.633 | loss=0.0222 | Q=1.327
Paso 103,000/1,000,000 | episodio=525 | epsilon=0.629 | loss=0.0272 | Q=0.976
Paso 104,000/1,000,000 | episodio=529 | epsilon=0.626 | loss=0.0178 | Q=1.143
Paso 105,000/1,000,000 | episodio=534 | epsilon=0.622 | loss=0.0125 | Q=1.043
Paso 106,000/1,000,000 | episodio=538 | epsilon=0.618 | loss=0.0167 | Q=1.250
Paso 107,000/1,000,000 | episodio=542 | epsilon=0.615 | loss=0.0254 | Q=1.019
Paso 108,000/1,000,000 | episodio=548 | epsilon=0.611 | loss=0.0211 | Q=1.308
Paso 109,000/1,000,000 | episodio=551 | epsilon=0.608 | loss=0.0154 | Q=1.016
Paso 110,000/1,000,000 | episodio=556 | epsilon=0.604 | loss=0.0192 | Q=1.156
Paso 111,000/1,000,000 | episodio=560 | epsilon=0.600 | loss=0.0259 | Q=1.102
Paso 112,000/1,000,000 | episodio=566 | epsilon=0.597 | loss=0.0149 | Q=1.153
Paso 113,000/1,000,000 | episodio=570 | epsilon=0.593 | loss=0.0186 | Q=1.088
Paso 114,000/1,000,000 | episodio=573 | epsilon=0.590 | loss=0.0106 | Q=1.009
Paso 115,000/1,000,000 | episodio=577 | epsilon=0.586 | loss=0.0175 | Q=1.216
Paso 116,000/1,000,000 | episodio=581 | epsilon=0.582 | loss=0.0141 | Q=0.993
Paso 117,000/1,000,000 | episodio=584 | epsilon=0.579 | loss=0.0215 | Q=1.260
Paso 118,000/1,000,000 | episodio=588 | epsilon=0.575 | loss=0.0128 | Q=1.113
Paso 119,000/1,000,000 | episodio=592 | epsilon=0.572 | loss=0.0119 | Q=1.015
Paso 120,000/1,000,000 | episodio=596 | epsilon=0.568 | loss=0.0178 | Q=1.215
Paso 121,000/1,000,000 | episodio=600 | epsilon=0.564 | loss=0.0224 | Q=1.267
Paso 122,000/1,000,000 | episodio=605 | epsilon=0.561 | loss=0.0147 | Q=1.555
Paso 123,000/1,000,000 | episodio=609 | epsilon=0.557 | loss=0.0159 | Q=1.403
Paso 124,000/1,000,000 | episodio=612 | epsilon=0.554 | loss=0.0232 | Q=1.314
Paso 125,000/1,000,000 | episodio=616 | epsilon=0.550 | loss=0.0160 | Q=1.277
Paso 126,000/1,000,000 | episodio=621 | epsilon=0.546 | loss=0.0150 | Q=1.142
Paso 127,000/1,000,000 | episodio=626 | epsilon=0.543 | loss=0.0111 | Q=1.296
Paso 128,000/1,000,000 | episodio=629 | epsilon=0.539 | loss=0.0126 | Q=0.999
Paso 129,000/1,000,000 | episodio=634 | epsilon=0.536 | loss=0.0146 | Q=1.583
Paso 130,000/1,000,000 | episodio=639 | epsilon=0.532 | loss=0.0130 | Q=1.334
Paso 131,000/1,000,000 | episodio=644 | epsilon=0.528 | loss=0.0194 | Q=1.547
Paso 132,000/1,000,000 | episodio=649 | epsilon=0.525 | loss=0.0146 | Q=1.003
Paso 133,000/1,000,000 | episodio=652 | epsilon=0.521 | loss=0.0189 | Q=1.381
Paso 134,000/1,000,000 | episodio=656 | epsilon=0.518 | loss=0.0087 | Q=1.215
Paso 135,000/1,000,000 | episodio=660 | epsilon=0.514 | loss=0.0165 | Q=1.373
Paso 136,000/1,000,000 | episodio=664 | epsilon=0.510 | loss=0.0128 | Q=1.752
Paso 137,000/1,000,000 | episodio=668 | epsilon=0.507 | loss=0.0117 | Q=1.149
Paso 138,000/1,000,000 | episodio=671 | epsilon=0.503 | loss=0.0101 | Q=1.279
Paso 139,000/1,000,000 | episodio=675 | epsilon=0.500 | loss=0.0074 | Q=1.288
Paso 140,000/1,000,000 | episodio=680 | epsilon=0.496 | loss=0.0076 | Q=1.478
Paso 141,000/1,000,000 | episodio=684 | epsilon=0.492 | loss=0.0224 | Q=1.424
Paso 142,000/1,000,000 | episodio=688 | epsilon=0.489 | loss=0.0127 | Q=1.476
Paso 143,000/1,000,000 | episodio=692 | epsilon=0.485 | loss=0.0071 | Q=1.522
Paso 144,000/1,000,000 | episodio=697 | epsilon=0.482 | loss=0.0243 | Q=1.563
Paso 145,000/1,000,000 | episodio=702 | epsilon=0.478 | loss=0.0128 | Q=1.397
Paso 146,000/1,000,000 | episodio=707 | epsilon=0.474 | loss=0.0222 | Q=1.396
Paso 147,000/1,000,000 | episodio=710 | epsilon=0.471 | loss=0.0095 | Q=1.562
Paso 148,000/1,000,000 | episodio=715 | epsilon=0.467 | loss=0.0150 | Q=1.429
Paso 149,000/1,000,000 | episodio=718 | epsilon=0.464 | loss=0.0115 | Q=1.604
Paso 150,000/1,000,000 | episodio=724 | epsilon=0.460 | loss=0.0070 | Q=1.475

EVALUACIÓN | paso=150,000 | promedio=297.00 | mediana=295.00 | máximo=460.00

Paso 151,000/1,000,000 | episodio=729 | epsilon=0.456 | loss=0.0229 | Q=1.753
Paso 152,000/1,000,000 | episodio=731 | epsilon=0.453 | loss=0.0244 | Q=1.624
Paso 153,000/1,000,000 | episodio=735 | epsilon=0.449 | loss=0.0178 | Q=1.422
Paso 154,000/1,000,000 | episodio=739 | epsilon=0.446 | loss=0.0229 | Q=1.668
Paso 155,000/1,000,000 | episodio=743 | epsilon=0.442 | loss=0.0125 | Q=1.607
Paso 156,000/1,000,000 | episodio=747 | epsilon=0.438 | loss=0.0167 | Q=1.575
Paso 157,000/1,000,000 | episodio=750 | epsilon=0.435 | loss=0.0142 | Q=1.494
Paso 158,000/1,000,000 | episodio=753 | epsilon=0.431 | loss=0.0048 | Q=1.629
Paso 159,000/1,000,000 | episodio=757 | epsilon=0.428 | loss=0.0090 | Q=1.782
Paso 160,000/1,000,000 | episodio=762 | epsilon=0.424 | loss=0.0291 | Q=1.415
Paso 161,000/1,000,000 | episodio=765 | epsilon=0.420 | loss=0.0155 | Q=1.787
Paso 162,000/1,000,000 | episodio=770 | epsilon=0.417 | loss=0.0080 | Q=1.602
Paso 163,000/1,000,000 | episodio=774 | epsilon=0.413 | loss=0.0349 | Q=1.743
Paso 164,000/1,000,000 | episodio=778 | epsilon=0.410 | loss=0.0090 | Q=1.699
Paso 165,000/1,000,000 | episodio=782 | epsilon=0.406 | loss=0.0184 | Q=1.607
Paso 166,000/1,000,000 | episodio=786 | epsilon=0.402 | loss=0.0116 | Q=1.661
Paso 167,000/1,000,000 | episodio=790 | epsilon=0.399 | loss=0.0163 | Q=1.847
Paso 168,000/1,000,000 | episodio=795 | epsilon=0.395 | loss=0.0134 | Q=1.567
Paso 169,000/1,000,000 | episodio=798 | epsilon=0.392 | loss=0.0214 | Q=1.832
Paso 170,000/1,000,000 | episodio=801 | epsilon=0.388 | loss=0.0124 | Q=1.978
Paso 171,000/1,000,000 | episodio=803 | epsilon=0.384 | loss=0.0231 | Q=2.080
Paso 172,000/1,000,000 | episodio=808 | epsilon=0.381 | loss=0.0089 | Q=1.818
Paso 173,000/1,000,000 | episodio=813 | epsilon=0.377 | loss=0.0163 | Q=1.512
Paso 174,000/1,000,000 | episodio=816 | epsilon=0.374 | loss=0.0172 | Q=1.483
Paso 175,000/1,000,000 | episodio=820 | epsilon=0.370 | loss=0.0126 | Q=1.460
Paso 176,000/1,000,000 | episodio=824 | epsilon=0.366 | loss=0.0104 | Q=1.728
Paso 177,000/1,000,000 | episodio=827 | epsilon=0.363 | loss=0.0078 | Q=1.690
Paso 178,000/1,000,000 | episodio=831 | epsilon=0.359 | loss=0.0267 | Q=1.721
Paso 179,000/1,000,000 | episodio=835 | epsilon=0.356 | loss=0.0173 | Q=1.882
Paso 180,000/1,000,000 | episodio=840 | epsilon=0.352 | loss=0.0079 | Q=1.780
Paso 181,000/1,000,000 | episodio=844 | epsilon=0.348 | loss=0.0067 | Q=1.883
Paso 182,000/1,000,000 | episodio=847 | epsilon=0.345 | loss=0.0128 | Q=2.045
Paso 183,000/1,000,000 | episodio=848 | epsilon=0.341 | loss=0.0100 | Q=1.823
Paso 184,000/1,000,000 | episodio=850 | epsilon=0.338 | loss=0.0124 | Q=1.877
Paso 185,000/1,000,000 | episodio=854 | epsilon=0.334 | loss=0.0174 | Q=2.084
Paso 186,000/1,000,000 | episodio=858 | epsilon=0.330 | loss=0.0145 | Q=1.699
Paso 187,000/1,000,000 | episodio=862 | epsilon=0.327 | loss=0.0106 | Q=1.923
Paso 188,000/1,000,000 | episodio=866 | epsilon=0.323 | loss=0.0100 | Q=1.943
Paso 189,000/1,000,000 | episodio=870 | epsilon=0.320 | loss=0.0145 | Q=1.651
Paso 190,000/1,000,000 | episodio=874 | epsilon=0.316 | loss=0.0132 | Q=1.862
Paso 191,000/1,000,000 | episodio=879 | epsilon=0.312 | loss=0.0128 | Q=2.088
Paso 192,000/1,000,000 | episodio=883 | epsilon=0.309 | loss=0.0186 | Q=1.801
Paso 193,000/1,000,000 | episodio=888 | epsilon=0.305 | loss=0.0150 | Q=1.851
Paso 194,000/1,000,000 | episodio=891 | epsilon=0.302 | loss=0.0138 | Q=1.586
Paso 195,000/1,000,000 | episodio=895 | epsilon=0.298 | loss=0.0141 | Q=2.059
Paso 196,000/1,000,000 | episodio=898 | epsilon=0.294 | loss=0.0265 | Q=1.570
Paso 197,000/1,000,000 | episodio=903 | epsilon=0.291 | loss=0.0262 | Q=2.087
Paso 198,000/1,000,000 | episodio=907 | epsilon=0.287 | loss=0.0120 | Q=1.866
Paso 199,000/1,000,000 | episodio=911 | epsilon=0.284 | loss=0.0117 | Q=1.999
Paso 200,000/1,000,000 | episodio=915 | epsilon=0.280 | loss=0.0206 | Q=1.887

EVALUACIÓN | paso=200,000 | promedio=383.00 | mediana=305.00 | máximo=545.00

Paso 201,000/1,000,000 | episodio=918 | epsilon=0.276 | loss=0.0061 | Q=2.128
Paso 202,000/1,000,000 | episodio=921 | epsilon=0.273 | loss=0.0271 | Q=1.908
Paso 203,000/1,000,000 | episodio=924 | epsilon=0.269 | loss=0.0199 | Q=2.300
Paso 204,000/1,000,000 | episodio=927 | epsilon=0.266 | loss=0.0292 | Q=2.104
Paso 205,000/1,000,000 | episodio=930 | epsilon=0.262 | loss=0.0292 | Q=2.130
Paso 206,000/1,000,000 | episodio=934 | epsilon=0.258 | loss=0.0103 | Q=1.942
Paso 207,000/1,000,000 | episodio=937 | epsilon=0.255 | loss=0.0097 | Q=2.158
Paso 208,000/1,000,000 | episodio=941 | epsilon=0.251 | loss=0.0035 | Q=2.352
Paso 209,000/1,000,000 | episodio=945 | epsilon=0.248 | loss=0.0171 | Q=2.171
Paso 210,000/1,000,000 | episodio=947 | epsilon=0.244 | loss=0.0169 | Q=2.216
Paso 211,000/1,000,000 | episodio=951 | epsilon=0.240 | loss=0.0171 | Q=2.166
Paso 212,000/1,000,000 | episodio=956 | epsilon=0.237 | loss=0.0129 | Q=2.259
Paso 213,000/1,000,000 | episodio=959 | epsilon=0.233 | loss=0.0119 | Q=2.109
Paso 214,000/1,000,000 | episodio=963 | epsilon=0.230 | loss=0.0127 | Q=2.548
Paso 215,000/1,000,000 | episodio=966 | epsilon=0.226 | loss=0.0160 | Q=2.338
Paso 216,000/1,000,000 | episodio=970 | epsilon=0.222 | loss=0.0233 | Q=2.363
Paso 217,000/1,000,000 | episodio=972 | epsilon=0.219 | loss=0.0113 | Q=2.092
Paso 218,000/1,000,000 | episodio=975 | epsilon=0.215 | loss=0.0070 | Q=2.165
Paso 219,000/1,000,000 | episodio=977 | epsilon=0.212 | loss=0.0083 | Q=2.202
Paso 220,000/1,000,000 | episodio=981 | epsilon=0.208 | loss=0.0248 | Q=2.130
Paso 221,000/1,000,000 | episodio=983 | epsilon=0.204 | loss=0.0185 | Q=2.501
Paso 222,000/1,000,000 | episodio=987 | epsilon=0.201 | loss=0.0227 | Q=2.335
Paso 223,000/1,000,000 | episodio=991 | epsilon=0.197 | loss=0.0136 | Q=2.083
Paso 224,000/1,000,000 | episodio=995 | epsilon=0.194 | loss=0.0192 | Q=2.603
Paso 225,000/1,000,000 | episodio=998 | epsilon=0.190 | loss=0.0115 | Q=2.124
Paso 226,000/1,000,000 | episodio=1001 | epsilon=0.186 | loss=0.0187 | Q=2.168
Paso 227,000/1,000,000 | episodio=1005 | epsilon=0.183 | loss=0.0095 | Q=2.210
Paso 228,000/1,000,000 | episodio=1008 | epsilon=0.179 | loss=0.0081 | Q=2.558
Paso 229,000/1,000,000 | episodio=1011 | epsilon=0.176 | loss=0.0185 | Q=2.476
Paso 230,000/1,000,000 | episodio=1015 | epsilon=0.172 | loss=0.0188 | Q=2.336
Paso 231,000/1,000,000 | episodio=1019 | epsilon=0.168 | loss=0.0203 | Q=2.443
Paso 232,000/1,000,000 | episodio=1023 | epsilon=0.165 | loss=0.0220 | Q=2.394
Paso 233,000/1,000,000 | episodio=1026 | epsilon=0.161 | loss=0.0225 | Q=2.257
Paso 234,000/1,000,000 | episodio=1029 | epsilon=0.158 | loss=0.0201 | Q=2.447
Paso 235,000/1,000,000 | episodio=1033 | epsilon=0.154 | loss=0.0204 | Q=2.299
Paso 236,000/1,000,000 | episodio=1034 | epsilon=0.150 | loss=0.0176 | Q=2.449
Paso 237,000/1,000,000 | episodio=1038 | epsilon=0.147 | loss=0.0212 | Q=2.497
Paso 238,000/1,000,000 | episodio=1043 | epsilon=0.143 | loss=0.0266 | Q=2.374
Paso 239,000/1,000,000 | episodio=1047 | epsilon=0.140 | loss=0.0163 | Q=2.522
Paso 240,000/1,000,000 | episodio=1052 | epsilon=0.136 | loss=0.0062 | Q=2.415
Paso 241,000/1,000,000 | episodio=1056 | epsilon=0.132 | loss=0.0171 | Q=2.504
Paso 242,000/1,000,000 | episodio=1058 | epsilon=0.129 | loss=0.0398 | Q=2.407
Paso 243,000/1,000,000 | episodio=1062 | epsilon=0.125 | loss=0.0124 | Q=2.686
Paso 244,000/1,000,000 | episodio=1066 | epsilon=0.122 | loss=0.0132 | Q=2.562
Paso 245,000/1,000,000 | episodio=1069 | epsilon=0.118 | loss=0.0131 | Q=2.474
Paso 246,000/1,000,000 | episodio=1073 | epsilon=0.114 | loss=0.0195 | Q=2.287
Paso 247,000/1,000,000 | episodio=1078 | epsilon=0.111 | loss=0.0130 | Q=2.444
Paso 248,000/1,000,000 | episodio=1081 | epsilon=0.107 | loss=0.0277 | Q=3.010
Paso 249,000/1,000,000 | episodio=1085 | epsilon=0.104 | loss=0.0174 | Q=2.552
Paso 250,000/1,000,000 | episodio=1088 | epsilon=0.100 | loss=0.0305 | Q=2.142

EVALUACIÓN | paso=250,000 | promedio=302.00 | mediana=305.00 | máximo=420.00

Paso 251,000/1,000,000 | episodio=1092 | epsilon=0.100 | loss=0.0068 | Q=2.512
Paso 252,000/1,000,000 | episodio=1095 | epsilon=0.100 | loss=0.0069 | Q=2.574
Paso 253,000/1,000,000 | episodio=1100 | epsilon=0.100 | loss=0.0110 | Q=2.635
Paso 254,000/1,000,000 | episodio=1103 | epsilon=0.100 | loss=0.0105 | Q=2.868
Paso 255,000/1,000,000 | episodio=1107 | epsilon=0.100 | loss=0.0108 | Q=2.294
Paso 256,000/1,000,000 | episodio=1110 | epsilon=0.100 | loss=0.0278 | Q=2.150
Paso 257,000/1,000,000 | episodio=1113 | epsilon=0.100 | loss=0.0169 | Q=2.314
Paso 258,000/1,000,000 | episodio=1118 | epsilon=0.100 | loss=0.0153 | Q=2.526
Paso 259,000/1,000,000 | episodio=1122 | epsilon=0.100 | loss=0.0114 | Q=2.619
Paso 260,000/1,000,000 | episodio=1127 | epsilon=0.100 | loss=0.0162 | Q=2.644

In [3]:
ruta_evaluaciones_v7 = Path(
    "../logs/entrenamientos/"
    "v7_dqn_per_a04_3step/evaluaciones.csv"
)

df_evaluaciones_v7 = pd.read_csv(
    ruta_evaluaciones_v7
)

df_evaluaciones_v7 = (
    df_evaluaciones_v7
    .sort_values("paso_global")
    .reset_index(drop=True)
)

display(df_evaluaciones_v7)

mejor_evaluacion_v7 = df_evaluaciones_v7.loc[
    df_evaluaciones_v7["promedio"].idxmax()
]

ultimas_tres_v7 = (
    df_evaluaciones_v7
    .tail(3)["promedio"]
    .mean()
)

print("\nRESUMEN DE V7")
print(
    f"Mejor paso: "
    f"{int(mejor_evaluacion_v7['paso_global']):,}"
)
print(
    f"Mejor promedio: "
    f"{mejor_evaluacion_v7['promedio']:.2f}"
)
print(
    f"Mediana del mejor checkpoint: "
    f"{mejor_evaluacion_v7['mediana']:.2f}"
)
print(
    f"Desviación: "
    f"{mejor_evaluacion_v7['desviacion']:.2f}"
)
print(
    f"Mínimo: "
    f"{mejor_evaluacion_v7['minimo']:.2f}"
)
print(
    f"Máximo: "
    f"{mejor_evaluacion_v7['maximo']:.2f}"
)
print(
    f"Promedio de las últimas tres evaluaciones: "
    f"{ultimas_tres_v7:.2f}"
)

ruta_mejor_v7 = Path(
    "../models/v7_dqn_per_a04_3step/"
    "mejor_modelo.pt"
)

print(
    "\nCheckpoint disponible: "
    f"{'OK' if ruta_mejor_v7.exists() else 'NO ENCONTRADO'}"
)

    paso_global  promedio  mediana  desviacion  minimo  maximo
0         50000     149.0    135.0   52.478567    95.0   240.0
1        100000     191.0    160.0  116.206712    70.0   330.0
2        150000     297.0    295.0  116.730459   135.0   460.0
3        200000     383.0    305.0  123.393679   255.0   545.0
4        250000     302.0    305.0   80.659779   175.0   420.0
5        300000     242.0    160.0  113.604577   155.0   445.0
6        350000     250.0    200.0   85.029407   160.0   365.0
7        400000     478.0    465.0  124.923977   325.0   630.0
8        450000     267.0    220.0  113.428392   130.0   425.0
9        500000     294.0    330.0  103.121288   160.0   415.0
10       550000     389.0    375.0   99.869915   240.0   520.0
11       600000     488.0    510.0  116.730459   270.0   600.0
12       650000     472.0    480.0   60.299254   375.0   555.0
13       700000     315.0    325.0   79.686887   170.0   405.0
14       750000     402.0    400.0   80.597767   260.0   480.0
15       800000     418.0    420.0   81.890170   315.0   540.0
16       850000     370.0    375.0   23.452079   330.0   395.0
17       900000     409.0    435.0   90.906545   285.0   545.0
18       950000     414.0    430.0   79.649231   260.0   480.0
19      1000000     493.0    480.0  114.043851   365.0   705.0

RESUMEN DE V7
Mejor paso: 1,000,000
Mejor promedio: 493.00
Mediana del mejor checkpoint: 480.00
Desviación: 114.04
Mínimo: 365.00
Máximo: 705.00
Promedio de las últimas tres evaluaciones: 438.67

Checkpoint disponible: OK

## Extensión de V7 hasta 1,500,000 pasos

Debido a que el mejor resultado de V7 ocurrió en el último checkpoint y las evaluaciones finales mostraron una tendencia favorable, se continúa el entrenamiento durante 500,000 pasos adicionales.

El replay buffer comienza vacío al reanudar, por lo que se recopilan 10,000 experiencias nuevas antes de retomar las actualizaciones.

In [4]:
import importlib
import gc

import train
importlib.reload(train)

from train import ConfigDQN, entrenar_dqn

ruta_checkpoint_v7 = Path(
    "../models/v7_dqn_per_a04_3step/"
    "checkpoint_final.pt"
)

if not ruta_checkpoint_v7.exists():
    raise FileNotFoundError(
        f"No se encontró el checkpoint: "
        f"{ruta_checkpoint_v7}"
    )

gc.collect()

if device.type == "mps":
    torch.mps.empty_cache()

config_v7_extendido = ConfigDQN(
    nombre_experimento=(
        "v7_dqn_per_a04_3step_extendido"
    ),
    total_pasos=1_500_000,

    seed=42,
    gamma=0.99,
    n_step=3,
    learning_rate=1e-4,
    batch_size=32,
    frecuencia_entrenamiento=4,

    capacidad_buffer=20_000,
    inicio_entrenamiento=10_000,
    frecuencia_actualizacion_target=10_000,
    gradient_clip=10.0,

    epsilon_inicial=1.0,
    epsilon_final=0.1,
    pasos_decay_epsilon=250_000,

    usar_per=True,
    per_alpha=0.4,
    per_beta_inicial=0.4,
    per_beta_final=1.0,
    per_pasos_beta=500_000,
    per_epsilon=1e-6,

    frecuencia_evaluacion=50_000,
    episodios_evaluacion=5,
    seed_evaluacion=1_000,
    frecuencia_log=1_000,

    terminal_on_life_loss=True,
    clip_reward=True,
)

resultado_v7_extendido = entrenar_dqn(
    config=config_v7_extendido,
    clase_modelo=DQN,
    device=device,
    usar_double_dqn=False,
    ruta_checkpoint_inicial=(
        ruta_checkpoint_v7
    ),
)

print(
    "\nEXTENSIÓN DE V7 FINALIZADA"
)

print(
    "Mejor promedio durante la extensión: "
    f"{resultado_v7_extendido['mejor_promedio_evaluacion']:.2f}"
)

Reanudando entrenamiento desde el paso 1,000,000 (checkpoint: ../models/v7_dqn_per_a04_3step/checkpoint_final.pt)
Replay buffer: priorizado | alpha=0.4 | beta inicial=0.4
Retorno utilizado: 3-step
Paso 1,010,000/1,500,000 | episodio=25 | epsilon=0.100 | loss=0.0399 | Q=5.046
Paso 1,011,000/1,500,000 | episodio=28 | epsilon=0.100 | loss=0.0203 | Q=4.656
Paso 1,012,000/1,500,000 | episodio=31 | epsilon=0.100 | loss=0.0062 | Q=5.263
Paso 1,013,000/1,500,000 | episodio=33 | epsilon=0.100 | loss=0.0217 | Q=5.342
Paso 1,014,000/1,500,000 | episodio=37 | epsilon=0.100 | loss=0.0265 | Q=5.254
Paso 1,015,000/1,500,000 | episodio=39 | epsilon=0.100 | loss=0.0082 | Q=5.395
Paso 1,016,000/1,500,000 | episodio=40 | epsilon=0.100 | loss=0.0164 | Q=4.702
Paso 1,017,000/1,500,000 | episodio=43 | epsilon=0.100 | loss=0.0022 | Q=5.224
Paso 1,018,000/1,500,000 | episodio=47 | epsilon=0.100 | loss=0.0056 | Q=4.788
Paso 1,019,000/1,500,000 | episodio=50 | epsilon=0.100 | loss=0.0056 | Q=4.933
Paso 1,020,000/1,500,000 | episodio=51 | epsilon=0.100 | loss=0.0127 | Q=5.149
Paso 1,021,000/1,500,000 | episodio=54 | epsilon=0.100 | loss=0.0177 | Q=5.194
Paso 1,022,000/1,500,000 | episodio=57 | epsilon=0.100 | loss=0.0154 | Q=5.215
Paso 1,023,000/1,500,000 | episodio=60 | epsilon=0.100 | loss=0.0079 | Q=5.048
Paso 1,024,000/1,500,000 | episodio=63 | epsilon=0.100 | loss=0.0150 | Q=4.832
Paso 1,025,000/1,500,000 | episodio=66 | epsilon=0.100 | loss=0.0198 | Q=5.051
Paso 1,026,000/1,500,000 | episodio=69 | epsilon=0.100 | loss=0.0139 | Q=5.051
Paso 1,027,000/1,500,000 | episodio=70 | epsilon=0.100 | loss=0.0148 | Q=5.441
Paso 1,028,000/1,500,000 | episodio=73 | epsilon=0.100 | loss=0.0168 | Q=4.868
Paso 1,029,000/1,500,000 | episodio=75 | epsilon=0.100 | loss=0.0065 | Q=5.274
Paso 1,030,000/1,500,000 | episodio=79 | epsilon=0.100 | loss=0.0176 | Q=5.187
Paso 1,031,000/1,500,000 | episodio=81 | epsilon=0.100 | loss=0.0078 | Q=5.208
Paso 1,032,000/1,500,000 | episodio=82 | epsilon=0.100 | loss=0.0042 | Q=4.984
Paso 1,033,000/1,500,000 | episodio=85 | epsilon=0.100 | loss=0.0075 | Q=5.318
Paso 1,034,000/1,500,000 | episodio=89 | epsilon=0.100 | loss=0.0203 | Q=5.309
Paso 1,035,000/1,500,000 | episodio=91 | epsilon=0.100 | loss=0.0076 | Q=4.933
Paso 1,036,000/1,500,000 | episodio=93 | epsilon=0.100 | loss=0.0077 | Q=5.307
Paso 1,037,000/1,500,000 | episodio=96 | epsilon=0.100 | loss=0.0199 | Q=4.625
Paso 1,038,000/1,500,000 | episodio=99 | epsilon=0.100 | loss=0.0054 | Q=5.116
Paso 1,039,000/1,500,000 | episodio=101 | epsilon=0.100 | loss=0.0118 | Q=4.605
Paso 1,040,000/1,500,000 | episodio=103 | epsilon=0.100 | loss=0.0077 | Q=4.866
Paso 1,041,000/1,500,000 | episodio=105 | epsilon=0.100 | loss=0.0118 | Q=4.679
Paso 1,042,000/1,500,000 | episodio=107 | epsilon=0.100 | loss=0.0065 | Q=4.970
Paso 1,043,000/1,500,000 | episodio=110 | epsilon=0.100 | loss=0.0184 | Q=4.572
Paso 1,044,000/1,500,000 | episodio=113 | epsilon=0.100 | loss=0.0071 | Q=5.477
Paso 1,045,000/1,500,000 | episodio=116 | epsilon=0.100 | loss=0.0155 | Q=5.026
Paso 1,046,000/1,500,000 | episodio=119 | epsilon=0.100 | loss=0.0169 | Q=5.300
Paso 1,047,000/1,500,000 | episodio=121 | epsilon=0.100 | loss=0.0151 | Q=5.079
Paso 1,048,000/1,500,000 | episodio=124 | epsilon=0.100 | loss=0.0143 | Q=4.980
Paso 1,049,000/1,500,000 | episodio=128 | epsilon=0.100 | loss=0.0081 | Q=4.957
Paso 1,050,000/1,500,000 | episodio=130 | epsilon=0.100 | loss=0.0208 | Q=5.099

EVALUACIÓN | paso=1,050,000 | promedio=455.00 | mediana=450.00 | máximo=615.00

Paso 1,051,000/1,500,000 | episodio=131 | epsilon=0.100 | loss=0.0344 | Q=4.951
Paso 1,052,000/1,500,000 | episodio=134 | epsilon=0.100 | loss=0.0126 | Q=5.488
Paso 1,053,000/1,500,000 | episodio=137 | epsilon=0.100 | loss=0.0130 | Q=4.337
Paso 1,054,000/1,500,000 | episodio=141 | epsilon=0.100 | loss=0.0265 | Q=4.596
Paso 1,055,000/1,500,000 | episodio=143 | epsilon=0.100 | loss=0.0248 | Q=5.368
Paso 1,056,000/1,500,000 | episodio=146 | epsilon=0.100 | loss=0.0141 | Q=4.634
Paso 1,057,000/1,500,000 | episodio=148 | epsilon=0.100 | loss=0.0160 | Q=5.212
Paso 1,058,000/1,500,000 | episodio=150 | epsilon=0.100 | loss=0.0140 | Q=4.962
Paso 1,059,000/1,500,000 | episodio=153 | epsilon=0.100 | loss=0.0153 | Q=5.199
Paso 1,060,000/1,500,000 | episodio=156 | epsilon=0.100 | loss=0.0083 | Q=5.145
Paso 1,061,000/1,500,000 | episodio=160 | epsilon=0.100 | loss=0.0152 | Q=5.004
Paso 1,062,000/1,500,000 | episodio=162 | epsilon=0.100 | loss=0.0098 | Q=4.583
Paso 1,063,000/1,500,000 | episodio=166 | epsilon=0.100 | loss=0.0169 | Q=4.911
Paso 1,064,000/1,500,000 | episodio=168 | epsilon=0.100 | loss=0.0238 | Q=5.260
Paso 1,065,000/1,500,000 | episodio=171 | epsilon=0.100 | loss=0.0057 | Q=5.671
Paso 1,066,000/1,500,000 | episodio=173 | epsilon=0.100 | loss=0.0291 | Q=4.747
Paso 1,067,000/1,500,000 | episodio=175 | epsilon=0.100 | loss=0.0121 | Q=4.980
Paso 1,068,000/1,500,000 | episodio=177 | epsilon=0.100 | loss=0.0301 | Q=5.570
Paso 1,069,000/1,500,000 | episodio=180 | epsilon=0.100 | loss=0.0045 | Q=5.119
Paso 1,070,000/1,500,000 | episodio=183 | epsilon=0.100 | loss=0.0086 | Q=5.235
Paso 1,071,000/1,500,000 | episodio=185 | epsilon=0.100 | loss=0.0406 | Q=5.059
Paso 1,072,000/1,500,000 | episodio=187 | epsilon=0.100 | loss=0.0148 | Q=5.149
Paso 1,073,000/1,500,000 | episodio=189 | epsilon=0.100 | loss=0.0284 | Q=5.170
Paso 1,074,000/1,500,000 | episodio=192 | epsilon=0.100 | loss=0.0051 | Q=4.879
Paso 1,075,000/1,500,000 | episodio=194 | epsilon=0.100 | loss=0.0208 | Q=5.032
Paso 1,076,000/1,500,000 | episodio=197 | epsilon=0.100 | loss=0.0175 | Q=5.195
Paso 1,077,000/1,500,000 | episodio=198 | epsilon=0.100 | loss=0.0118 | Q=4.752
Paso 1,078,000/1,500,000 | episodio=201 | epsilon=0.100 | loss=0.0367 | Q=5.020
Paso 1,079,000/1,500,000 | episodio=204 | epsilon=0.100 | loss=0.0306 | Q=5.169
Paso 1,080,000/1,500,000 | episodio=207 | epsilon=0.100 | loss=0.0058 | Q=4.926
Paso 1,081,000/1,500,000 | episodio=210 | epsilon=0.100 | loss=0.0078 | Q=4.828
Paso 1,082,000/1,500,000 | episodio=211 | epsilon=0.100 | loss=0.0041 | Q=5.240
Paso 1,083,000/1,500,000 | episodio=212 | epsilon=0.100 | loss=0.0211 | Q=5.082
Paso 1,084,000/1,500,000 | episodio=216 | epsilon=0.100 | loss=0.0162 | Q=4.911
Paso 1,085,000/1,500,000 | episodio=219 | epsilon=0.100 | loss=0.0223 | Q=5.303
Paso 1,086,000/1,500,000 | episodio=221 | epsilon=0.100 | loss=0.0436 | Q=5.274
Paso 1,087,000/1,500,000 | episodio=224 | epsilon=0.100 | loss=0.0225 | Q=4.783
Paso 1,088,000/1,500,000 | episodio=226 | epsilon=0.100 | loss=0.0053 | Q=4.982
Paso 1,089,000/1,500,000 | episodio=229 | epsilon=0.100 | loss=0.0069 | Q=5.715
Paso 1,090,000/1,500,000 | episodio=232 | epsilon=0.100 | loss=0.0205 | Q=5.087
Paso 1,091,000/1,500,000 | episodio=235 | epsilon=0.100 | loss=0.0108 | Q=4.958
Paso 1,092,000/1,500,000 | episodio=238 | epsilon=0.100 | loss=0.0140 | Q=5.456
Paso 1,093,000/1,500,000 | episodio=241 | epsilon=0.100 | loss=0.0233 | Q=4.964
Paso 1,094,000/1,500,000 | episodio=243 | epsilon=0.100 | loss=0.0263 | Q=5.042
Paso 1,095,000/1,500,000 | episodio=246 | epsilon=0.100 | loss=0.0063 | Q=4.779
Paso 1,096,000/1,500,000 | episodio=248 | epsilon=0.100 | loss=0.0085 | Q=4.864
Paso 1,097,000/1,500,000 | episodio=250 | epsilon=0.100 | loss=0.0362 | Q=4.931
Paso 1,098,000/1,500,000 | episodio=254 | epsilon=0.100 | loss=0.0212 | Q=5.151
Paso 1,099,000/1,500,000 | episodio=256 | epsilon=0.100 | loss=0.0242 | Q=5.393
Paso 1,100,000/1,500,000 | episodio=260 | epsilon=0.100 | loss=0.0102 | Q=4.956

EVALUACIÓN | paso=1,100,000 | promedio=508.00 | mediana=425.00 | máximo=990.00

Paso 1,101,000/1,500,000 | episodio=262 | epsilon=0.100 | loss=0.0060 | Q=5.730
Paso 1,102,000/1,500,000 | episodio=264 | epsilon=0.100 | loss=0.0178 | Q=5.172
Paso 1,103,000/1,500,000 | episodio=266 | epsilon=0.100 | loss=0.0112 | Q=4.894
Paso 1,104,000/1,500,000 | episodio=268 | epsilon=0.100 | loss=0.0080 | Q=5.175
Paso 1,105,000/1,500,000 | episodio=270 | epsilon=0.100 | loss=0.0077 | Q=5.348
Paso 1,106,000/1,500,000 | episodio=272 | epsilon=0.100 | loss=0.0104 | Q=5.257
Paso 1,107,000/1,500,000 | episodio=275 | epsilon=0.100 | loss=0.0179 | Q=4.587
Paso 1,108,000/1,500,000 | episodio=277 | epsilon=0.100 | loss=0.0122 | Q=4.730
Paso 1,109,000/1,500,000 | episodio=279 | epsilon=0.100 | loss=0.0107 | Q=5.081
Paso 1,110,000/1,500,000 | episodio=281 | epsilon=0.100 | loss=0.0081 | Q=4.631
Paso 1,111,000/1,500,000 | episodio=284 | epsilon=0.100 | loss=0.0055 | Q=5.394
Paso 1,112,000/1,500,000 | episodio=287 | epsilon=0.100 | loss=0.0067 | Q=5.286
Paso 1,113,000/1,500,000 | episodio=290 | epsilon=0.100 | loss=0.0126 | Q=5.083
Paso 1,114,000/1,500,000 | episodio=292 | epsilon=0.100 | loss=0.0187 | Q=4.985
Paso 1,115,000/1,500,000 | episodio=296 | epsilon=0.100 | loss=0.0058 | Q=4.922
Paso 1,116,000/1,500,000 | episodio=300 | epsilon=0.100 | loss=0.0073 | Q=5.458
Paso 1,117,000/1,500,000 | episodio=303 | epsilon=0.100 | loss=0.0148 | Q=4.705
Paso 1,118,000/1,500,000 | episodio=305 | epsilon=0.100 | loss=0.0242 | Q=5.856
Paso 1,119,000/1,500,000 | episodio=308 | epsilon=0.100 | loss=0.0060 | Q=5.120
Paso 1,120,000/1,500,000 | episodio=311 | epsilon=0.100 | loss=0.0096 | Q=5.349
Paso 1,121,000/1,500,000 | episodio=313 | epsilon=0.100 | loss=0.0214 | Q=4.993
Paso 1,122,000/1,500,000 | episodio=317 | epsilon=0.100 | loss=0.0138 | Q=5.489
Paso 1,123,000/1,500,000 | episodio=320 | epsilon=0.100 | loss=0.0084 | Q=4.660
Paso 1,124,000/1,500,000 | episodio=323 | epsilon=0.100 | loss=0.0102 | Q=4.902
Paso 1,125,000/1,500,000 | episodio=326 | epsilon=0.100 | loss=0.0120 | Q=4.834
Paso 1,126,000/1,500,000 | episodio=329 | epsilon=0.100 | loss=0.0224 | Q=4.721
Paso 1,127,000/1,500,000 | episodio=333 | epsilon=0.100 | loss=0.0225 | Q=5.191
Paso 1,128,000/1,500,000 | episodio=335 | epsilon=0.100 | loss=0.0116 | Q=4.641
Paso 1,129,000/1,500,000 | episodio=337 | epsilon=0.100 | loss=0.0189 | Q=5.111
Paso 1,130,000/1,500,000 | episodio=340 | epsilon=0.100 | loss=0.0075 | Q=5.775
Paso 1,131,000/1,500,000 | episodio=342 | epsilon=0.100 | loss=0.0096 | Q=5.613
Paso 1,132,000/1,500,000 | episodio=344 | epsilon=0.100 | loss=0.0251 | Q=5.390
Paso 1,133,000/1,500,000 | episodio=346 | epsilon=0.100 | loss=0.0114 | Q=5.326
Paso 1,134,000/1,500,000 | episodio=348 | epsilon=0.100 | loss=0.0071 | Q=4.757
Paso 1,135,000/1,500,000 | episodio=351 | epsilon=0.100 | loss=0.0118 | Q=5.262
Paso 1,136,000/1,500,000 | episodio=354 | epsilon=0.100 | loss=0.0026 | Q=5.428
Paso 1,137,000/1,500,000 | episodio=357 | epsilon=0.100 | loss=0.0059 | Q=5.342
Paso 1,138,000/1,500,000 | episodio=360 | epsilon=0.100 | loss=0.0102 | Q=5.350
Paso 1,139,000/1,500,000 | episodio=364 | epsilon=0.100 | loss=0.0109 | Q=4.767
Paso 1,140,000/1,500,000 | episodio=367 | epsilon=0.100 | loss=0.0119 | Q=4.928
Paso 1,141,000/1,500,000 | episodio=368 | epsilon=0.100 | loss=0.0121 | Q=5.524
Paso 1,142,000/1,500,000 | episodio=372 | epsilon=0.100 | loss=0.0353 | Q=5.707
Paso 1,143,000/1,500,000 | episodio=374 | epsilon=0.100 | loss=0.0047 | Q=4.983
Paso 1,144,000/1,500,000 | episodio=376 | epsilon=0.100 | loss=0.0079 | Q=5.251
Paso 1,145,000/1,500,000 | episodio=378 | epsilon=0.100 | loss=0.0171 | Q=5.076
Paso 1,146,000/1,500,000 | episodio=381 | epsilon=0.100 | loss=0.0101 | Q=5.372
Paso 1,147,000/1,500,000 | episodio=385 | epsilon=0.100 | loss=0.0122 | Q=5.352
Paso 1,148,000/1,500,000 | episodio=388 | epsilon=0.100 | loss=0.0235 | Q=5.322
Paso 1,149,000/1,500,000 | episodio=390 | epsilon=0.100 | loss=0.0236 | Q=5.261
Paso 1,150,000/1,500,000 | episodio=393 | epsilon=0.100 | loss=0.0076 | Q=5.271

EVALUACIÓN | paso=1,150,000 | promedio=475.00 | mediana=475.00 | máximo=575.00

Paso 1,151,000/1,500,000 | episodio=395 | epsilon=0.100 | loss=0.0230 | Q=5.204
Paso 1,152,000/1,500,000 | episodio=397 | epsilon=0.100 | loss=0.0031 | Q=5.009
Paso 1,153,000/1,500,000 | episodio=399 | epsilon=0.100 | loss=0.0102 | Q=5.186
Paso 1,154,000/1,500,000 | episodio=401 | epsilon=0.100 | loss=0.0171 | Q=5.094
Paso 1,155,000/1,500,000 | episodio=402 | epsilon=0.100 | loss=0.0114 | Q=4.874
Paso 1,156,000/1,500,000 | episodio=406 | epsilon=0.100 | loss=0.0055 | Q=5.560
Paso 1,157,000/1,500,000 | episodio=408 | epsilon=0.100 | loss=0.0015 | Q=5.470
Paso 1,158,000/1,500,000 | episodio=412 | epsilon=0.100 | loss=0.0081 | Q=5.378
Paso 1,159,000/1,500,000 | episodio=415 | epsilon=0.100 | loss=0.0110 | Q=5.313
Paso 1,160,000/1,500,000 | episodio=418 | epsilon=0.100 | loss=0.0098 | Q=5.190
Paso 1,161,000/1,500,000 | episodio=421 | epsilon=0.100 | loss=0.0034 | Q=5.505
Paso 1,162,000/1,500,000 | episodio=424 | epsilon=0.100 | loss=0.0300 | Q=5.491
Paso 1,163,000/1,500,000 | episodio=425 | epsilon=0.100 | loss=0.0205 | Q=5.478
Paso 1,164,000/1,500,000 | episodio=428 | epsilon=0.100 | loss=0.0140 | Q=5.443
Paso 1,165,000/1,500,000 | episodio=431 | epsilon=0.100 | loss=0.0096 | Q=5.565
Paso 1,166,000/1,500,000 | episodio=433 | epsilon=0.100 | loss=0.0136 | Q=5.142
Paso 1,167,000/1,500,000 | episodio=435 | epsilon=0.100 | loss=0.0206 | Q=5.326
Paso 1,168,000/1,500,000 | episodio=438 | epsilon=0.100 | loss=0.0174 | Q=5.013
Paso 1,169,000/1,500,000 | episodio=440 | epsilon=0.100 | loss=0.0165 | Q=5.272
Paso 1,170,000/1,500,000 | episodio=443 | epsilon=0.100 | loss=0.0201 | Q=5.319
Paso 1,171,000/1,500,000 | episodio=445 | epsilon=0.100 | loss=0.0093 | Q=5.769
Paso 1,172,000/1,500,000 | episodio=448 | epsilon=0.100 | loss=0.0034 | Q=5.377
Paso 1,173,000/1,500,000 | episodio=451 | epsilon=0.100 | loss=0.0099 | Q=4.952
Paso 1,174,000/1,500,000 | episodio=452 | epsilon=0.100 | loss=0.0089 | Q=4.924
Paso 1,175,000/1,500,000 | episodio=454 | epsilon=0.100 | loss=0.0119 | Q=5.325
Paso 1,176,000/1,500,000 | episodio=456 | epsilon=0.100 | loss=0.0084 | Q=5.451
Paso 1,177,000/1,500,000 | episodio=459 | epsilon=0.100 | loss=0.0195 | Q=5.194
Paso 1,178,000/1,500,000 | episodio=461 | epsilon=0.100 | loss=0.0054 | Q=4.802
Paso 1,179,000/1,500,000 | episodio=464 | epsilon=0.100 | loss=0.0081 | Q=6.049
Paso 1,180,000/1,500,000 | episodio=467 | epsilon=0.100 | loss=0.0032 | Q=5.234
Paso 1,181,000/1,500,000 | episodio=468 | epsilon=0.100 | loss=0.0149 | Q=5.812
Paso 1,182,000/1,500,000 | episodio=470 | epsilon=0.100 | loss=0.0161 | Q=5.158
Paso 1,183,000/1,500,000 | episodio=472 | epsilon=0.100 | loss=0.0166 | Q=5.455
Paso 1,184,000/1,500,000 | episodio=474 | epsilon=0.100 | loss=0.0189 | Q=5.486
Paso 1,185,000/1,500,000 | episodio=476 | epsilon=0.100 | loss=0.0269 | Q=4.951
Paso 1,186,000/1,500,000 | episodio=479 | epsilon=0.100 | loss=0.0055 | Q=5.210
Paso 1,187,000/1,500,000 | episodio=482 | epsilon=0.100 | loss=0.0163 | Q=5.473
Paso 1,188,000/1,500,000 | episodio=483 | epsilon=0.100 | loss=0.0031 | Q=4.885
Paso 1,189,000/1,500,000 | episodio=486 | epsilon=0.100 | loss=0.0170 | Q=5.225
Paso 1,190,000/1,500,000 | episodio=488 | epsilon=0.100 | loss=0.0103 | Q=5.629
Paso 1,191,000/1,500,000 | episodio=490 | epsilon=0.100 | loss=0.0128 | Q=5.018
Paso 1,192,000/1,500,000 | episodio=493 | epsilon=0.100 | loss=0.0050 | Q=4.944
Paso 1,193,000/1,500,000 | episodio=496 | epsilon=0.100 | loss=0.0100 | Q=5.486
Paso 1,194,000/1,500,000 | episodio=498 | epsilon=0.100 | loss=0.0115 | Q=5.453
Paso 1,195,000/1,500,000 | episodio=500 | epsilon=0.100 | loss=0.0120 | Q=5.375
Paso 1,196,000/1,500,000 | episodio=504 | epsilon=0.100 | loss=0.0053 | Q=5.498
Paso 1,197,000/1,500,000 | episodio=507 | epsilon=0.100 | loss=0.0226 | Q=5.351
Paso 1,198,000/1,500,000 | episodio=510 | epsilon=0.100 | loss=0.0093 | Q=5.526
Paso 1,199,000/1,500,000 | episodio=513 | epsilon=0.100 | loss=0.0244 | Q=5.244
Paso 1,200,000/1,500,000 | episodio=516 | epsilon=0.100 | loss=0.0145 | Q=5.333

EVALUACIÓN | paso=1,200,000 | promedio=447.00 | mediana=380.00 | máximo=745.00

Paso 1,201,000/1,500,000 | episodio=518 | epsilon=0.100 | loss=0.0100 | Q=5.280
Paso 1,202,000/1,500,000 | episodio=521 | epsilon=0.100 | loss=0.0199 | Q=5.275
Paso 1,203,000/1,500,000 | episodio=524 | epsilon=0.100 | loss=0.0090 | Q=5.375
Paso 1,204,000/1,500,000 | episodio=527 | epsilon=0.100 | loss=0.0114 | Q=5.741
Paso 1,205,000/1,500,000 | episodio=530 | epsilon=0.100 | loss=0.0088 | Q=4.674
Paso 1,206,000/1,500,000 | episodio=534 | epsilon=0.100 | loss=0.0145 | Q=5.600
Paso 1,207,000/1,500,000 | episodio=535 | epsilon=0.100 | loss=0.0318 | Q=4.999
Paso 1,208,000/1,500,000 | episodio=537 | epsilon=0.100 | loss=0.0215 | Q=5.294
Paso 1,209,000/1,500,000 | episodio=540 | epsilon=0.100 | loss=0.0046 | Q=5.070
Paso 1,210,000/1,500,000 | episodio=541 | epsilon=0.100 | loss=0.0059 | Q=5.380
Paso 1,211,000/1,500,000 | episodio=545 | epsilon=0.100 | loss=0.0111 | Q=5.726
Paso 1,212,000/1,500,000 | episodio=548 | epsilon=0.100 | loss=0.0142 | Q=5.049
Paso 1,213,000/1,500,000 | episodio=551 | epsilon=0.100 | loss=0.0096 | Q=5.544
Paso 1,214,000/1,500,000 | episodio=554 | epsilon=0.100 | loss=0.0048 | Q=5.952
Paso 1,215,000/1,500,000 | episodio=556 | epsilon=0.100 | loss=0.0123 | Q=5.601
Paso 1,216,000/1,500,000 | episodio=559 | epsilon=0.100 | loss=0.0038 | Q=5.616
Paso 1,217,000/1,500,000 | episodio=562 | epsilon=0.100 | loss=0.0120 | Q=5.489
Paso 1,218,000/1,500,000 | episodio=564 | epsilon=0.100 | loss=0.0157 | Q=5.168
Paso 1,219,000/1,500,000 | episodio=567 | epsilon=0.100 | loss=0.0344 | Q=4.829
Paso 1,220,000/1,500,000 | episodio=569 | epsilon=0.100 | loss=0.0276 | Q=5.189
Paso 1,221,000/1,500,000 | episodio=571 | epsilon=0.100 | loss=0.0094 | Q=5.021
Paso 1,222,000/1,500,000 | episodio=574 | epsilon=0.100 | loss=0.0061 | Q=6.103
Paso 1,223,000/1,500,000 | episodio=577 | epsilon=0.100 | loss=0.0124 | Q=5.354
Paso 1,224,000/1,500,000 | episodio=580 | epsilon=0.100 | loss=0.0093 | Q=5.783
Paso 1,225,000/1,500,000 | episodio=583 | epsilon=0.100 | loss=0.0193 | Q=5.221
Paso 1,226,000/1,500,000 | episodio=585 | epsilon=0.100 | loss=0.0179 | Q=5.030
Paso 1,227,000/1,500,000 | episodio=587 | epsilon=0.100 | loss=0.0223 | Q=5.191
Paso 1,228,000/1,500,000 | episodio=590 | epsilon=0.100 | loss=0.0211 | Q=5.331
Paso 1,229,000/1,500,000 | episodio=593 | epsilon=0.100 | loss=0.0122 | Q=5.020
Paso 1,230,000/1,500,000 | episodio=594 | epsilon=0.100 | loss=0.0077 | Q=5.254
Paso 1,231,000/1,500,000 | episodio=596 | epsilon=0.100 | loss=0.0096 | Q=5.495
Paso 1,232,000/1,500,000 | episodio=599 | epsilon=0.100 | loss=0.0176 | Q=5.426
Paso 1,233,000/1,500,000 | episodio=601 | epsilon=0.100 | loss=0.0280 | Q=4.892
Paso 1,234,000/1,500,000 | episodio=604 | epsilon=0.100 | loss=0.0020 | Q=5.233
Paso 1,235,000/1,500,000 | episodio=606 | epsilon=0.100 | loss=0.0075 | Q=5.134
Paso 1,236,000/1,500,000 | episodio=608 | epsilon=0.100 | loss=0.0042 | Q=5.400
Paso 1,237,000/1,500,000 | episodio=611 | epsilon=0.100 | loss=0.0118 | Q=5.177
Paso 1,238,000/1,500,000 | episodio=614 | epsilon=0.100 | loss=0.0132 | Q=5.201
Paso 1,239,000/1,500,000 | episodio=617 | epsilon=0.100 | loss=0.0228 | Q=5.373
Paso 1,240,000/1,500,000 | episodio=620 | epsilon=0.100 | loss=0.0214 | Q=5.611
Paso 1,241,000/1,500,000 | episodio=621 | epsilon=0.100 | loss=0.0058 | Q=5.522
Paso 1,242,000/1,500,000 | episodio=623 | epsilon=0.100 | loss=0.0155 | Q=4.844
Paso 1,243,000/1,500,000 | episodio=624 | epsilon=0.100 | loss=0.0124 | Q=5.576
Paso 1,244,000/1,500,000 | episodio=626 | epsilon=0.100 | loss=0.0053 | Q=5.001
Paso 1,245,000/1,500,000 | episodio=629 | epsilon=0.100 | loss=0.0133 | Q=4.940
Paso 1,246,000/1,500,000 | episodio=632 | epsilon=0.100 | loss=0.0055 | Q=5.277
Paso 1,247,000/1,500,000 | episodio=634 | epsilon=0.100 | loss=0.0057 | Q=5.140
Paso 1,248,000/1,500,000 | episodio=637 | epsilon=0.100 | loss=0.0129 | Q=5.436
Paso 1,249,000/1,500,000 | episodio=639 | epsilon=0.100 | loss=0.0231 | Q=5.401
Paso 1,250,000/1,500,000 | episodio=643 | epsilon=0.100 | loss=0.0145 | Q=5.216

EVALUACIÓN | paso=1,250,000 | promedio=462.00 | mediana=470.00 | máximo=545.00

Paso 1,251,000/1,500,000 | episodio=646 | epsilon=0.100 | loss=0.0260 | Q=5.152

In [5]:
ruta_evaluaciones_v7_ext = Path(
    "../logs/entrenamientos/"
    "v7_dqn_per_a04_3step_extendido/"
    "evaluaciones.csv"
)

df_evaluaciones_v7_ext = pd.read_csv(
    ruta_evaluaciones_v7_ext
)

df_evaluaciones_v7_ext = (
    df_evaluaciones_v7_ext
    .sort_values("paso_global")
    .reset_index(drop=True)
)

display(df_evaluaciones_v7_ext)

mejor_evaluacion_v7_ext = (
    df_evaluaciones_v7_ext.loc[
        df_evaluaciones_v7_ext[
            "promedio"
        ].idxmax()
    ]
)

print("\nMEJOR EVALUACIÓN DE V7 EXTENDIDO")
print(
    f"Paso: "
    f"{int(mejor_evaluacion_v7_ext['paso_global']):,}"
)
print(
    f"Promedio: "
    f"{mejor_evaluacion_v7_ext['promedio']:.2f}"
)
print(
    f"Mediana: "
    f"{mejor_evaluacion_v7_ext['mediana']:.2f}"
)
print(
    f"Desviación: "
    f"{mejor_evaluacion_v7_ext['desviacion']:.2f}"
)
print(
    f"Mínimo: "
    f"{mejor_evaluacion_v7_ext['minimo']:.2f}"
)
print(
    f"Máximo: "
    f"{mejor_evaluacion_v7_ext['maximo']:.2f}"
)

ruta_mejor_v7_ext = Path(
    "../models/"
    "v7_dqn_per_a04_3step_extendido/"
    "mejor_modelo.pt"
)

print(
    "\nCheckpoint disponible: "
    f"{'OK' if ruta_mejor_v7_ext.exists() else 'NO ENCONTRADO'}"
)

   paso_global  promedio  mediana  desviacion  minimo  maximo
0      1050000     455.0    450.0  122.759928   315.0   615.0
1      1100000     508.0    425.0  254.727305   285.0   990.0
2      1150000     475.0    475.0   60.580525   385.0   575.0
3      1200000     447.0    380.0  150.086642   345.0   745.0
4      1250000     462.0    470.0   92.336342   290.0   545.0
5      1300000     485.0    455.0   96.332757   350.0   600.0
6      1350000     427.0    325.0  197.651208   225.0   775.0
7      1400000     631.0    550.0  279.291962   340.0  1100.0
8      1450000     565.0    580.0  205.377701   330.0   885.0
9      1500000     465.0    375.0  149.432259   310.0   720.0

MEJOR EVALUACIÓN DE V7 EXTENDIDO
Paso: 1,400,000
Promedio: 631.00
Mediana: 550.00
Desviación: 279.29
Mínimo: 340.00
Máximo: 1100.00

Checkpoint disponible: OK

In [6]:
import evaluation
importlib.reload(evaluation)

from evaluation import evaluar_modelo
from models import DQN

N_EPISODIOS_EVALUACION = 30
SEMILLA_BASE_EVALUACION = 42

checkpoint_v7_ext = torch.load(
    ruta_mejor_v7_ext,
    map_location=device,
    weights_only=True,
)

mejor_v7_extendido = DQN(
    n_acciones=6
).to(device)

mejor_v7_extendido.load_state_dict(
    checkpoint_v7_ext[
        "modelo_online_state_dict"
    ]
)

mejor_v7_extendido.eval()

print(
    f"Checkpoint cargado desde el paso: "
    f"{checkpoint_v7_ext['paso']:,}"
)

print(
    "\nEvaluando V7 extendido durante "
    f"{N_EPISODIOS_EVALUACION} episodios...\n"
)

(
    resultados_v7_extendido,
    resumen_v7_extendido,
) = evaluar_modelo(
    modelo=mejor_v7_extendido,
    config=config_v7_extendido,
    device=device,
    n_episodios=N_EPISODIOS_EVALUACION,
    seed_base=SEMILLA_BASE_EVALUACION,
)

df_v7_extendido = pd.DataFrame(
    resultados_v7_extendido
)

df_v7_extendido["agente"] = (
    "DQN + PER a=0.4 + 3-step extendido"
)

df_v7_extendido = df_v7_extendido[
    [
        "agente",
        "episodio",
        "seed",
        "recompensa_total",
        "pasos",
        "terminated",
        "truncated",
    ]
]

print("RESUMEN DE 30 EPISODIOS")

for metrica, valor in resumen_v7_extendido.items():
    print(f"{metrica}: {valor:.2f}")

display(df_v7_extendido.head(10))

Checkpoint cargado desde el paso: 1,400,000

Evaluando V7 extendido durante 30 episodios...

RESUMEN DE 30 EPISODIOS
promedio: 421.83
mediana: 430.00
desviacion: 144.56
minimo: 180.00
maximo: 960.00

,agente,episodio,seed,recompensa_total,pasos,terminated,truncated
0,DQN + PER a=0.4 + 3-step extendido,0,42,630.0,1109,True,False
1,DQN + PER a=0.4 + 3-step extendido,1,43,400.0,726,True,False
2,DQN + PER a=0.4 + 3-step extendido,2,44,455.0,911,True,False
3,DQN + PER a=0.4 + 3-step extendido,3,45,280.0,645,True,False
4,DQN + PER a=0.4 + 3-step extendido,4,46,490.0,882,True,False
5,DQN + PER a=0.4 + 3-step extendido,5,47,330.0,613,True,False
6,DQN + PER a=0.4 + 3-step extendido,6,48,295.0,533,True,False
7,DQN + PER a=0.4 + 3-step extendido,7,49,485.0,880,True,False
8,DQN + PER a=0.4 + 3-step extendido,8,50,250.0,656,True,False
9,DQN + PER a=0.4 + 3-step extendido,9,51,960.0,1674,True,False

In [7]:
ruta_resultados_v7_ext = Path(
    "../logs/evaluacion_v7_extendido.csv"
)

df_v7_extendido.to_csv(
    ruta_resultados_v7_ext,
    index=False,
)

df_alpha06 = pd.read_csv(
    "../logs/evaluacion_dqn_per_3step.csv"
)

comparacion_alpha = (
    pd.concat(
        [
            df_alpha06,
            df_v7_extendido,
        ],
        ignore_index=True,
    )
    .pivot(
        index="seed",
        columns="agente",
        values="recompensa_total",
    )
    .dropna()
)

nombre_alpha06 = "DQN + PER + 3-step"
nombre_alpha04 = (
    "DQN + PER a=0.4 + 3-step extendido"
)

diferencia = (
    comparacion_alpha[nombre_alpha04]
    - comparacion_alpha[nombre_alpha06]
)

print(
    f"Victorias {nombre_alpha06}:",
    (diferencia < 0).sum(),
)

print(
    f"Victorias {nombre_alpha04}:",
    (diferencia > 0).sum(),
)

print(
    "Empates:",
    (diferencia == 0).sum(),
)

# Comparación del criterio mejor-de-cinco
df_competencia_alpha = pd.concat(
    [
        df_alpha06,
        df_v7_extendido,
    ],
    ignore_index=True,
)

df_competencia_alpha["bloque_de_5"] = (
    df_competencia_alpha["episodio"] // 5
) + 1

mejores_de_5_alpha = (
    df_competencia_alpha
    .groupby(
        ["agente", "bloque_de_5"],
        as_index=False,
    )
    .agg(
        mejor_recompensa=(
            "recompensa_total",
            "max",
        ),
        promedio_bloque=(
            "recompensa_total",
            "mean",
        ),
    )
)

resumen_competencia_alpha = (
    mejores_de_5_alpha
    .groupby("agente")
    .agg(
        mejor_de_5_promedio=(
            "mejor_recompensa",
            "mean",
        ),
        mejor_de_5_mediana=(
            "mejor_recompensa",
            "median",
        ),
        menor_mejor_de_5=(
            "mejor_recompensa",
            "min",
        ),
        mayor_mejor_de_5=(
            "mejor_recompensa",
            "max",
        ),
    )
    .round(2)
    .reset_index()
)

print(
    "\nCOMPARACIÓN DEL MEJOR DE CINCO"
)

display(resumen_competencia_alpha)

Victorias DQN + PER + 3-step: 17
Victorias DQN + PER a=0.4 + 3-step extendido: 12
Empates: 1

COMPARACIÓN DEL MEJOR DE CINCO

,agente,mejor_de_5_promedio,mejor_de_5_mediana,menor_mejor_de_5,mayor_mejor_de_5
0,DQN + PER + 3-step,611.67,582.5,490.0,770.0
1,DQN + PER a=0.4 + 3-step extendido,617.50,562.5,465.0,960.0

## Experimento V8: PER con alpha=0.6 y retorno 5-step

Esta iteración mantiene la configuración de priorización que produjo el mejor rendimiento general (`per_alpha=0.6`) y modifica únicamente el horizonte del retorno:

- V6: `n_step=3`
- V8: `n_step=5`

El objetivo es determinar si incorporar cinco recompensas consecutivas permite propagar mejor la señal de recompensa. Los demás hiperparámetros se mantienen constantes para realizar una comparación controlada.

In [8]:
import gc
import importlib

import train
importlib.reload(train)

from train import ConfigDQN, entrenar_dqn
from models import DQN

# Liberar modelos anteriores
objetos_temporales = [
    "resultado_v7_extendido",
    "mejor_v7_extendido",
    "checkpoint_v7_ext",
]

for nombre in objetos_temporales:
    globals().pop(nombre, None)

gc.collect()

if device.type == "mps":
    torch.mps.empty_cache()

config_per_alpha06_5step = ConfigDQN(
    nombre_experimento="v8_dqn_per_a06_5step",
    total_pasos=1_000_000,

    seed=42,
    gamma=0.99,
    n_step=5,
    learning_rate=1e-4,
    batch_size=32,
    frecuencia_entrenamiento=4,

    capacidad_buffer=20_000,
    inicio_entrenamiento=10_000,
    frecuencia_actualizacion_target=10_000,
    gradient_clip=10.0,

    epsilon_inicial=1.0,
    epsilon_final=0.1,
    pasos_decay_epsilon=250_000,

    usar_per=True,
    per_alpha=0.6,
    per_beta_inicial=0.4,
    per_beta_final=1.0,
    per_pasos_beta=500_000,
    per_epsilon=1e-6,

    frecuencia_evaluacion=50_000,
    episodios_evaluacion=5,
    seed_evaluacion=1_000,
    frecuencia_log=1_000,

    terminal_on_life_loss=True,
    clip_reward=True,
)

resultado_per_alpha06_5step = entrenar_dqn(
    config=config_per_alpha06_5step,
    clase_modelo=DQN,
    device=device,
    usar_double_dqn=False,
)

print(
    "\nENTRENAMIENTO V8 FINALIZADO"
)

print(
    "Mejor promedio de evaluación: "
    f"{resultado_per_alpha06_5step['mejor_promedio_evaluacion']:.2f}"
)

Replay buffer: priorizado | alpha=0.6 | beta inicial=0.4
Retorno utilizado: 5-step
Paso 10,000/1,000,000 | episodio=49 | epsilon=0.964 | loss=0.0857 | Q=-0.007
Paso 11,000/1,000,000 | episodio=52 | epsilon=0.960 | loss=0.0158 | Q=0.190
Paso 12,000/1,000,000 | episodio=57 | epsilon=0.957 | loss=0.0609 | Q=0.219
Paso 13,000/1,000,000 | episodio=63 | epsilon=0.953 | loss=0.0386 | Q=0.228
Paso 14,000/1,000,000 | episodio=66 | epsilon=0.950 | loss=0.0377 | Q=0.255
Paso 15,000/1,000,000 | episodio=72 | epsilon=0.946 | loss=0.0370 | Q=0.234
Paso 16,000/1,000,000 | episodio=77 | epsilon=0.942 | loss=0.0211 | Q=0.181
Paso 17,000/1,000,000 | episodio=79 | epsilon=0.939 | loss=0.0617 | Q=0.229
Paso 18,000/1,000,000 | episodio=84 | epsilon=0.935 | loss=0.0366 | Q=0.217
Paso 19,000/1,000,000 | episodio=92 | epsilon=0.932 | loss=0.0196 | Q=0.216
Paso 20,000/1,000,000 | episodio=98 | epsilon=0.928 | loss=0.0356 | Q=0.261
Paso 21,000/1,000,000 | episodio=103 | epsilon=0.924 | loss=0.0210 | Q=0.505
Paso 22,000/1,000,000 | episodio=106 | epsilon=0.921 | loss=0.0388 | Q=0.537
Paso 23,000/1,000,000 | episodio=111 | epsilon=0.917 | loss=0.0203 | Q=0.434
Paso 24,000/1,000,000 | episodio=117 | epsilon=0.914 | loss=0.0219 | Q=0.350
Paso 25,000/1,000,000 | episodio=120 | epsilon=0.910 | loss=0.0068 | Q=0.460
Paso 26,000/1,000,000 | episodio=126 | epsilon=0.906 | loss=0.0385 | Q=0.494
Paso 27,000/1,000,000 | episodio=130 | epsilon=0.903 | loss=0.0230 | Q=0.433
Paso 28,000/1,000,000 | episodio=135 | epsilon=0.899 | loss=0.0346 | Q=0.530
Paso 29,000/1,000,000 | episodio=140 | epsilon=0.896 | loss=0.0210 | Q=0.410
Paso 30,000/1,000,000 | episodio=146 | epsilon=0.892 | loss=0.0196 | Q=0.299
Paso 31,000/1,000,000 | episodio=151 | epsilon=0.888 | loss=0.0375 | Q=0.588
Paso 32,000/1,000,000 | episodio=155 | epsilon=0.885 | loss=0.0385 | Q=0.515
Paso 33,000/1,000,000 | episodio=161 | epsilon=0.881 | loss=0.0145 | Q=0.537
Paso 34,000/1,000,000 | episodio=168 | epsilon=0.878 | loss=0.0202 | Q=0.568
Paso 35,000/1,000,000 | episodio=170 | epsilon=0.874 | loss=0.0211 | Q=0.467
Paso 36,000/1,000,000 | episodio=175 | epsilon=0.870 | loss=0.0384 | Q=0.555
Paso 37,000/1,000,000 | episodio=181 | epsilon=0.867 | loss=0.0257 | Q=0.578
Paso 38,000/1,000,000 | episodio=186 | epsilon=0.863 | loss=0.0203 | Q=0.476
Paso 39,000/1,000,000 | episodio=190 | epsilon=0.860 | loss=0.0222 | Q=0.466
Paso 40,000/1,000,000 | episodio=197 | epsilon=0.856 | loss=0.0145 | Q=0.518
Paso 41,000/1,000,000 | episodio=201 | epsilon=0.852 | loss=0.0203 | Q=0.598
Paso 42,000/1,000,000 | episodio=206 | epsilon=0.849 | loss=0.0216 | Q=0.744
Paso 43,000/1,000,000 | episodio=212 | epsilon=0.845 | loss=0.0431 | Q=0.691
Paso 44,000/1,000,000 | episodio=217 | epsilon=0.842 | loss=0.0201 | Q=0.636
Paso 45,000/1,000,000 | episodio=222 | epsilon=0.838 | loss=0.0240 | Q=0.701
Paso 46,000/1,000,000 | episodio=228 | epsilon=0.834 | loss=0.0319 | Q=0.685
Paso 47,000/1,000,000 | episodio=233 | epsilon=0.831 | loss=0.0406 | Q=0.764
Paso 48,000/1,000,000 | episodio=239 | epsilon=0.827 | loss=0.0208 | Q=0.678
Paso 49,000/1,000,000 | episodio=244 | epsilon=0.824 | loss=0.0160 | Q=0.586
Paso 50,000/1,000,000 | episodio=248 | epsilon=0.820 | loss=0.0224 | Q=0.704

EVALUACIÓN | paso=50,000 | promedio=168.00 | mediana=110.00 | máximo=385.00

Paso 51,000/1,000,000 | episodio=252 | epsilon=0.816 | loss=0.0461 | Q=0.772
Paso 52,000/1,000,000 | episodio=259 | epsilon=0.813 | loss=0.0340 | Q=0.851
Paso 53,000/1,000,000 | episodio=266 | epsilon=0.809 | loss=0.0338 | Q=0.837
Paso 54,000/1,000,000 | episodio=272 | epsilon=0.806 | loss=0.0128 | Q=0.836
Paso 55,000/1,000,000 | episodio=275 | epsilon=0.802 | loss=0.0306 | Q=0.686
Paso 56,000/1,000,000 | episodio=280 | epsilon=0.798 | loss=0.0334 | Q=0.835
Paso 57,000/1,000,000 | episodio=285 | epsilon=0.795 | loss=0.0400 | Q=1.004
Paso 58,000/1,000,000 | episodio=288 | epsilon=0.791 | loss=0.0215 | Q=0.710
Paso 59,000/1,000,000 | episodio=292 | epsilon=0.788 | loss=0.0091 | Q=0.632
Paso 60,000/1,000,000 | episodio=295 | epsilon=0.784 | loss=0.0359 | Q=0.834
Paso 61,000/1,000,000 | episodio=300 | epsilon=0.780 | loss=0.0365 | Q=0.927
Paso 62,000/1,000,000 | episodio=306 | epsilon=0.777 | loss=0.0302 | Q=0.934
Paso 63,000/1,000,000 | episodio=311 | epsilon=0.773 | loss=0.0359 | Q=1.010
Paso 64,000/1,000,000 | episodio=316 | epsilon=0.770 | loss=0.0336 | Q=0.963
Paso 65,000/1,000,000 | episodio=321 | epsilon=0.766 | loss=0.0211 | Q=1.054
Paso 66,000/1,000,000 | episodio=325 | epsilon=0.762 | loss=0.0291 | Q=1.014
Paso 67,000/1,000,000 | episodio=329 | epsilon=0.759 | loss=0.0246 | Q=0.954
Paso 68,000/1,000,000 | episodio=335 | epsilon=0.755 | loss=0.0248 | Q=0.873
Paso 69,000/1,000,000 | episodio=341 | epsilon=0.752 | loss=0.0222 | Q=0.943
Paso 70,000/1,000,000 | episodio=344 | epsilon=0.748 | loss=0.0171 | Q=0.853
Paso 71,000/1,000,000 | episodio=349 | epsilon=0.744 | loss=0.0434 | Q=0.903
Paso 72,000/1,000,000 | episodio=356 | epsilon=0.741 | loss=0.0273 | Q=0.925
Paso 73,000/1,000,000 | episodio=359 | epsilon=0.737 | loss=0.0190 | Q=0.989
Paso 74,000/1,000,000 | episodio=362 | epsilon=0.734 | loss=0.0314 | Q=1.141
Paso 75,000/1,000,000 | episodio=368 | epsilon=0.730 | loss=0.0268 | Q=0.967
Paso 76,000/1,000,000 | episodio=373 | epsilon=0.726 | loss=0.0271 | Q=0.882
Paso 77,000/1,000,000 | episodio=380 | epsilon=0.723 | loss=0.0274 | Q=1.244
Paso 78,000/1,000,000 | episodio=384 | epsilon=0.719 | loss=0.0318 | Q=1.106
Paso 79,000/1,000,000 | episodio=389 | epsilon=0.716 | loss=0.0055 | Q=0.937
Paso 80,000/1,000,000 | episodio=391 | epsilon=0.712 | loss=0.0486 | Q=1.053
Paso 81,000/1,000,000 | episodio=395 | epsilon=0.708 | loss=0.0429 | Q=1.332
Paso 82,000/1,000,000 | episodio=401 | epsilon=0.705 | loss=0.0298 | Q=1.267
Paso 83,000/1,000,000 | episodio=406 | epsilon=0.701 | loss=0.0280 | Q=1.276
Paso 84,000/1,000,000 | episodio=410 | epsilon=0.698 | loss=0.0302 | Q=1.241
Paso 85,000/1,000,000 | episodio=413 | epsilon=0.694 | loss=0.0344 | Q=1.208
Paso 86,000/1,000,000 | episodio=416 | epsilon=0.690 | loss=0.0315 | Q=1.164
Paso 87,000/1,000,000 | episodio=421 | epsilon=0.687 | loss=0.0211 | Q=1.291
Paso 88,000/1,000,000 | episodio=427 | epsilon=0.683 | loss=0.0137 | Q=1.233
Paso 89,000/1,000,000 | episodio=432 | epsilon=0.680 | loss=0.0257 | Q=1.283
Paso 90,000/1,000,000 | episodio=436 | epsilon=0.676 | loss=0.0154 | Q=1.156
Paso 91,000/1,000,000 | episodio=441 | epsilon=0.672 | loss=0.0223 | Q=1.111
Paso 92,000/1,000,000 | episodio=444 | epsilon=0.669 | loss=0.0388 | Q=1.225
Paso 93,000/1,000,000 | episodio=449 | epsilon=0.665 | loss=0.0410 | Q=1.203
Paso 94,000/1,000,000 | episodio=453 | epsilon=0.662 | loss=0.0432 | Q=1.434
Paso 95,000/1,000,000 | episodio=457 | epsilon=0.658 | loss=0.0212 | Q=1.316
Paso 96,000/1,000,000 | episodio=462 | epsilon=0.654 | loss=0.0287 | Q=1.424
Paso 97,000/1,000,000 | episodio=465 | epsilon=0.651 | loss=0.0213 | Q=1.390
Paso 98,000/1,000,000 | episodio=470 | epsilon=0.647 | loss=0.0420 | Q=1.024
Paso 99,000/1,000,000 | episodio=474 | epsilon=0.644 | loss=0.0232 | Q=1.235
Paso 100,000/1,000,000 | episodio=479 | epsilon=0.640 | loss=0.0191 | Q=1.307

EVALUACIÓN | paso=100,000 | promedio=192.00 | mediana=155.00 | máximo=335.00

Paso 101,000/1,000,000 | episodio=483 | epsilon=0.636 | loss=0.0325 | Q=1.639
Paso 102,000/1,000,000 | episodio=486 | epsilon=0.633 | loss=0.0289 | Q=1.818
Paso 103,000/1,000,000 | episodio=491 | epsilon=0.629 | loss=0.0135 | Q=1.620
Paso 104,000/1,000,000 | episodio=496 | epsilon=0.626 | loss=0.0171 | Q=1.262
Paso 105,000/1,000,000 | episodio=500 | epsilon=0.622 | loss=0.0215 | Q=1.633
Paso 106,000/1,000,000 | episodio=504 | epsilon=0.618 | loss=0.0285 | Q=1.483
Paso 107,000/1,000,000 | episodio=507 | epsilon=0.615 | loss=0.0164 | Q=1.821
Paso 108,000/1,000,000 | episodio=511 | epsilon=0.611 | loss=0.0238 | Q=1.692
Paso 109,000/1,000,000 | episodio=515 | epsilon=0.608 | loss=0.0124 | Q=1.241
Paso 110,000/1,000,000 | episodio=519 | epsilon=0.604 | loss=0.0188 | Q=1.483
Paso 111,000/1,000,000 | episodio=523 | epsilon=0.600 | loss=0.0301 | Q=1.828
Paso 112,000/1,000,000 | episodio=526 | epsilon=0.597 | loss=0.0203 | Q=1.680
Paso 113,000/1,000,000 | episodio=529 | epsilon=0.593 | loss=0.0307 | Q=1.875
Paso 114,000/1,000,000 | episodio=532 | epsilon=0.590 | loss=0.0315 | Q=1.657
Paso 115,000/1,000,000 | episodio=535 | epsilon=0.586 | loss=0.0204 | Q=1.824
Paso 116,000/1,000,000 | episodio=539 | epsilon=0.582 | loss=0.0207 | Q=1.882
Paso 117,000/1,000,000 | episodio=544 | epsilon=0.579 | loss=0.0237 | Q=1.837
Paso 118,000/1,000,000 | episodio=547 | epsilon=0.575 | loss=0.0366 | Q=2.003
Paso 119,000/1,000,000 | episodio=552 | epsilon=0.572 | loss=0.0354 | Q=1.694
Paso 120,000/1,000,000 | episodio=557 | epsilon=0.568 | loss=0.0148 | Q=1.663
Paso 121,000/1,000,000 | episodio=559 | epsilon=0.564 | loss=0.0217 | Q=1.824
Paso 122,000/1,000,000 | episodio=563 | epsilon=0.561 | loss=0.0371 | Q=1.893
Paso 123,000/1,000,000 | episodio=567 | epsilon=0.557 | loss=0.0285 | Q=1.912
Paso 124,000/1,000,000 | episodio=571 | epsilon=0.554 | loss=0.0499 | Q=2.034
Paso 125,000/1,000,000 | episodio=574 | epsilon=0.550 | loss=0.0206 | Q=1.735
Paso 126,000/1,000,000 | episodio=578 | epsilon=0.546 | loss=0.0208 | Q=1.665
Paso 127,000/1,000,000 | episodio=582 | epsilon=0.543 | loss=0.0343 | Q=1.896
Paso 128,000/1,000,000 | episodio=586 | epsilon=0.539 | loss=0.0109 | Q=1.816
Paso 129,000/1,000,000 | episodio=589 | epsilon=0.536 | loss=0.0121 | Q=2.204
Paso 130,000/1,000,000 | episodio=593 | epsilon=0.532 | loss=0.0252 | Q=2.012
Paso 131,000/1,000,000 | episodio=598 | epsilon=0.528 | loss=0.0206 | Q=1.973
Paso 132,000/1,000,000 | episodio=602 | epsilon=0.525 | loss=0.0180 | Q=2.095
Paso 133,000/1,000,000 | episodio=605 | epsilon=0.521 | loss=0.0356 | Q=2.060
Paso 134,000/1,000,000 | episodio=606 | epsilon=0.518 | loss=0.0294 | Q=1.909
Paso 135,000/1,000,000 | episodio=609 | epsilon=0.514 | loss=0.0152 | Q=1.797
Paso 136,000/1,000,000 | episodio=612 | epsilon=0.510 | loss=0.0339 | Q=1.795
Paso 137,000/1,000,000 | episodio=617 | epsilon=0.507 | loss=0.0196 | Q=1.993
Paso 138,000/1,000,000 | episodio=620 | epsilon=0.503 | loss=0.0406 | Q=1.573
Paso 139,000/1,000,000 | episodio=624 | epsilon=0.500 | loss=0.0329 | Q=1.908
Paso 140,000/1,000,000 | episodio=627 | epsilon=0.496 | loss=0.0135 | Q=1.960
Paso 141,000/1,000,000 | episodio=630 | epsilon=0.492 | loss=0.0257 | Q=2.179
Paso 142,000/1,000,000 | episodio=633 | epsilon=0.489 | loss=0.0138 | Q=1.617
Paso 143,000/1,000,000 | episodio=636 | epsilon=0.485 | loss=0.0196 | Q=1.991
Paso 144,000/1,000,000 | episodio=641 | epsilon=0.482 | loss=0.0105 | Q=1.706
Paso 145,000/1,000,000 | episodio=647 | epsilon=0.478 | loss=0.0332 | Q=1.988
Paso 146,000/1,000,000 | episodio=651 | epsilon=0.474 | loss=0.0265 | Q=1.877
Paso 147,000/1,000,000 | episodio=654 | epsilon=0.471 | loss=0.0301 | Q=2.041
Paso 148,000/1,000,000 | episodio=658 | epsilon=0.467 | loss=0.0104 | Q=1.560
Paso 149,000/1,000,000 | episodio=661 | epsilon=0.464 | loss=0.0115 | Q=1.400
Paso 150,000/1,000,000 | episodio=664 | epsilon=0.460 | loss=0.0197 | Q=1.821

EVALUACIÓN | paso=150,000 | promedio=354.00 | mediana=390.00 | máximo=535.00

Paso 151,000/1,000,000 | episodio=669 | epsilon=0.456 | loss=0.0489 | Q=1.690
Paso 152,000/1,000,000 | episodio=674 | epsilon=0.453 | loss=0.0361 | Q=2.098
Paso 153,000/1,000,000 | episodio=679 | epsilon=0.449 | loss=0.0470 | Q=2.054
Paso 154,000/1,000,000 | episodio=683 | epsilon=0.446 | loss=0.0179 | Q=2.062
Paso 155,000/1,000,000 | episodio=686 | epsilon=0.442 | loss=0.0137 | Q=2.198
Paso 156,000/1,000,000 | episodio=690 | epsilon=0.438 | loss=0.0266 | Q=1.970
Paso 157,000/1,000,000 | episodio=694 | epsilon=0.435 | loss=0.0430 | Q=2.337
Paso 158,000/1,000,000 | episodio=699 | epsilon=0.431 | loss=0.0544 | Q=1.958
Paso 159,000/1,000,000 | episodio=700 | epsilon=0.428 | loss=0.0163 | Q=2.058
Paso 160,000/1,000,000 | episodio=704 | epsilon=0.424 | loss=0.0280 | Q=2.010
Paso 161,000/1,000,000 | episodio=708 | epsilon=0.420 | loss=0.0205 | Q=2.211
Paso 162,000/1,000,000 | episodio=710 | epsilon=0.417 | loss=0.0267 | Q=2.506
Paso 163,000/1,000,000 | episodio=714 | epsilon=0.413 | loss=0.0092 | Q=2.786
Paso 164,000/1,000,000 | episodio=716 | epsilon=0.410 | loss=0.0251 | Q=2.055
Paso 165,000/1,000,000 | episodio=720 | epsilon=0.406 | loss=0.0296 | Q=2.203
Paso 166,000/1,000,000 | episodio=724 | epsilon=0.402 | loss=0.0236 | Q=2.502
Paso 167,000/1,000,000 | episodio=727 | epsilon=0.399 | loss=0.0294 | Q=2.236
Paso 168,000/1,000,000 | episodio=730 | epsilon=0.395 | loss=0.0316 | Q=2.365
Paso 169,000/1,000,000 | episodio=733 | epsilon=0.392 | loss=0.0088 | Q=2.119
Paso 170,000/1,000,000 | episodio=738 | epsilon=0.388 | loss=0.0112 | Q=2.664
Paso 171,000/1,000,000 | episodio=740 | epsilon=0.384 | loss=0.0490 | Q=2.403
Paso 172,000/1,000,000 | episodio=743 | epsilon=0.381 | loss=0.0227 | Q=2.077
Paso 173,000/1,000,000 | episodio=747 | epsilon=0.377 | loss=0.0234 | Q=2.344
Paso 174,000/1,000,000 | episodio=752 | epsilon=0.374 | loss=0.0193 | Q=3.008
Paso 175,000/1,000,000 | episodio=755 | epsilon=0.370 | loss=0.0113 | Q=2.390
Paso 176,000/1,000,000 | episodio=759 | epsilon=0.366 | loss=0.0202 | Q=2.343
Paso 177,000/1,000,000 | episodio=764 | epsilon=0.363 | loss=0.0147 | Q=2.478
Paso 178,000/1,000,000 | episodio=769 | epsilon=0.359 | loss=0.0411 | Q=2.045
Paso 179,000/1,000,000 | episodio=774 | epsilon=0.356 | loss=0.0264 | Q=2.325
Paso 180,000/1,000,000 | episodio=779 | epsilon=0.352 | loss=0.0311 | Q=2.028
Paso 181,000/1,000,000 | episodio=783 | epsilon=0.348 | loss=0.0252 | Q=2.293
Paso 182,000/1,000,000 | episodio=786 | epsilon=0.345 | loss=0.0208 | Q=2.235
Paso 183,000/1,000,000 | episodio=791 | epsilon=0.341 | loss=0.0292 | Q=2.479
Paso 184,000/1,000,000 | episodio=795 | epsilon=0.338 | loss=0.0088 | Q=2.254
Paso 185,000/1,000,000 | episodio=799 | epsilon=0.334 | loss=0.0383 | Q=2.282
Paso 186,000/1,000,000 | episodio=801 | epsilon=0.330 | loss=0.0173 | Q=2.627
Paso 187,000/1,000,000 | episodio=805 | epsilon=0.327 | loss=0.0270 | Q=2.649
Paso 188,000/1,000,000 | episodio=808 | epsilon=0.323 | loss=0.0146 | Q=2.850
Paso 189,000/1,000,000 | episodio=813 | epsilon=0.320 | loss=0.0139 | Q=2.535
Paso 190,000/1,000,000 | episodio=817 | epsilon=0.316 | loss=0.0225 | Q=2.603
Paso 191,000/1,000,000 | episodio=820 | epsilon=0.312 | loss=0.0148 | Q=2.597
Paso 192,000/1,000,000 | episodio=825 | epsilon=0.309 | loss=0.0327 | Q=2.094
Paso 193,000/1,000,000 | episodio=829 | epsilon=0.305 | loss=0.0230 | Q=2.387
Paso 194,000/1,000,000 | episodio=833 | epsilon=0.302 | loss=0.0155 | Q=2.406
Paso 195,000/1,000,000 | episodio=838 | epsilon=0.298 | loss=0.0129 | Q=2.385
Paso 196,000/1,000,000 | episodio=843 | epsilon=0.294 | loss=0.0099 | Q=2.633
Paso 197,000/1,000,000 | episodio=846 | epsilon=0.291 | loss=0.0203 | Q=2.516
Paso 198,000/1,000,000 | episodio=850 | epsilon=0.287 | loss=0.0281 | Q=2.321
Paso 199,000/1,000,000 | episodio=853 | epsilon=0.284 | loss=0.0443 | Q=2.362
Paso 200,000/1,000,000 | episodio=856 | epsilon=0.280 | loss=0.0377 | Q=2.665

EVALUACIÓN | paso=200,000 | promedio=250.00 | mediana=155.00 | máximo=545.00

Paso 201,000/1,000,000 | episodio=860 | epsilon=0.276 | loss=0.0319 | Q=2.510
Paso 202,000/1,000,000 | episodio=865 | epsilon=0.273 | loss=0.0192 | Q=2.105
Paso 203,000/1,000,000 | episodio=869 | epsilon=0.269 | loss=0.0144 | Q=2.621
Paso 204,000/1,000,000 | episodio=874 | epsilon=0.266 | loss=0.0354 | Q=2.864
Paso 205,000/1,000,000 | episodio=878 | epsilon=0.262 | loss=0.0180 | Q=2.352
Paso 206,000/1,000,000 | episodio=883 | epsilon=0.258 | loss=0.0087 | Q=2.914
Paso 207,000/1,000,000 | episodio=887 | epsilon=0.255 | loss=0.0083 | Q=2.980
Paso 208,000/1,000,000 | episodio=891 | epsilon=0.251 | loss=0.0247 | Q=2.714
Paso 209,000/1,000,000 | episodio=894 | epsilon=0.248 | loss=0.0414 | Q=2.581
Paso 210,000/1,000,000 | episodio=897 | epsilon=0.244 | loss=0.0184 | Q=2.428
Paso 211,000/1,000,000 | episodio=900 | epsilon=0.240 | loss=0.0271 | Q=2.586
Paso 212,000/1,000,000 | episodio=905 | epsilon=0.237 | loss=0.0171 | Q=2.015
Paso 213,000/1,000,000 | episodio=909 | epsilon=0.233 | loss=0.0402 | Q=2.317
Paso 214,000/1,000,000 | episodio=911 | epsilon=0.230 | loss=0.0186 | Q=2.306
Paso 215,000/1,000,000 | episodio=916 | epsilon=0.226 | loss=0.0197 | Q=2.512
Paso 216,000/1,000,000 | episodio=921 | epsilon=0.222 | loss=0.0239 | Q=2.085
Paso 217,000/1,000,000 | episodio=925 | epsilon=0.219 | loss=0.0183 | Q=2.985
Paso 218,000/1,000,000 | episodio=930 | epsilon=0.215 | loss=0.0244 | Q=2.855
Paso 219,000/1,000,000 | episodio=932 | epsilon=0.212 | loss=0.0487 | Q=2.328
Paso 220,000/1,000,000 | episodio=934 | epsilon=0.208 | loss=0.0278 | Q=2.861
Paso 221,000/1,000,000 | episodio=937 | epsilon=0.204 | loss=0.0368 | Q=3.004
Paso 222,000/1,000,000 | episodio=941 | epsilon=0.201 | loss=0.0308 | Q=2.762
Paso 223,000/1,000,000 | episodio=946 | epsilon=0.197 | loss=0.0122 | Q=2.873
Paso 224,000/1,000,000 | episodio=952 | epsilon=0.194 | loss=0.0666 | Q=2.915
Paso 225,000/1,000,000 | episodio=956 | epsilon=0.190 | loss=0.0231 | Q=2.767
Paso 226,000/1,000,000 | episodio=959 | epsilon=0.186 | loss=0.0263 | Q=2.578
Paso 227,000/1,000,000 | episodio=962 | epsilon=0.183 | loss=0.0376 | Q=2.573
Paso 228,000/1,000,000 | episodio=965 | epsilon=0.179 | loss=0.0202 | Q=2.852
Paso 229,000/1,000,000 | episodio=970 | epsilon=0.176 | loss=0.0201 | Q=2.892
Paso 230,000/1,000,000 | episodio=972 | epsilon=0.172 | loss=0.0110 | Q=2.404
Paso 231,000/1,000,000 | episodio=975 | epsilon=0.168 | loss=0.0340 | Q=2.739
Paso 232,000/1,000,000 | episodio=978 | epsilon=0.165 | loss=0.0170 | Q=2.883
Paso 233,000/1,000,000 | episodio=981 | epsilon=0.161 | loss=0.0390 | Q=2.325
Paso 234,000/1,000,000 | episodio=985 | epsilon=0.158 | loss=0.0306 | Q=2.611
Paso 235,000/1,000,000 | episodio=988 | epsilon=0.154 | loss=0.0270 | Q=3.080
Paso 236,000/1,000,000 | episodio=991 | epsilon=0.150 | loss=0.0139 | Q=2.370
Paso 237,000/1,000,000 | episodio=996 | epsilon=0.147 | loss=0.0428 | Q=2.304
Paso 238,000/1,000,000 | episodio=1002 | epsilon=0.143 | loss=0.0217 | Q=2.484
Paso 239,000/1,000,000 | episodio=1006 | epsilon=0.140 | loss=0.0469 | Q=2.689
Paso 240,000/1,000,000 | episodio=1010 | epsilon=0.136 | loss=0.0300 | Q=3.024
Paso 241,000/1,000,000 | episodio=1014 | epsilon=0.132 | loss=0.0221 | Q=2.734
Paso 242,000/1,000,000 | episodio=1016 | epsilon=0.129 | loss=0.0232 | Q=2.770
Paso 243,000/1,000,000 | episodio=1020 | epsilon=0.125 | loss=0.0230 | Q=2.974
Paso 244,000/1,000,000 | episodio=1023 | epsilon=0.122 | loss=0.0265 | Q=3.331
Paso 245,000/1,000,000 | episodio=1026 | epsilon=0.118 | loss=0.0189 | Q=2.653
Paso 246,000/1,000,000 | episodio=1030 | epsilon=0.114 | loss=0.0184 | Q=2.991
Paso 247,000/1,000,000 | episodio=1033 | epsilon=0.111 | loss=0.0141 | Q=2.796
Paso 248,000/1,000,000 | episodio=1037 | epsilon=0.107 | loss=0.0179 | Q=2.845
Paso 249,000/1,000,000 | episodio=1040 | epsilon=0.104 | loss=0.0364 | Q=2.798
Paso 250,000/1,000,000 | episodio=1045 | epsilon=0.100 | loss=0.0199 | Q=3.019

EVALUACIÓN | paso=250,000 | promedio=453.00 | mediana=360.00 | máximo=870.00

Paso 251,000/1,000,000 | episodio=1050 | epsilon=0.100 | loss=0.0405 | Q=3.094
Paso 252,000/1,000,000 | episodio=1054 | epsilon=0.100 | loss=0.0266 | Q=2.546
Paso 253,000/1,000,000 | episodio=1057 | epsilon=0.100 | loss=0.0417 | Q=2.612
Paso 254,000/1,000,000 | episodio=1059 | epsilon=0.100 | loss=0.0077 | Q=3.134
Paso 255,000/1,000,000 | episodio=1063 | epsilon=0.100 | loss=0.0285 | Q=2.887
Paso 256,000/1,000,000 | episodio=1067 | epsilon=0.100 | loss=0.0099 | Q=2.862
Paso 257,000/1,000,000 | episodio=1072 | epsilon=0.100 | loss=0.0179 | Q=2.821
Paso 258,000/1,000,000 | episodio=1074 | epsilon=0.100 | loss=0.0261 | Q=2.935
Paso 259,000/1,000,000 | episodio=1078 | epsilon=0.100 | loss=0.0142 | Q=2.664
Paso 260,000/1,000,000 | episodio=1080 | epsilon=0.100 | loss=0.0140 | Q=2.634

In [9]:
from pathlib import Path
import pandas as pd
from IPython.display import display

RUTA_LOG_V8 = Path(
    "../logs/entrenamientos/v8_dqn_per_a06_5step/evaluaciones.csv"
)
RUTA_MODELO_V8 = Path(
    "../models/v8_dqn_per_a06_5step/mejor_modelo.pt"
)

df_evaluaciones_v8 = pd.read_csv(RUTA_LOG_V8)

display(df_evaluaciones_v8)

mejor_fila_v8 = df_evaluaciones_v8.loc[
    df_evaluaciones_v8["promedio"].idxmax()
]

promedio_ultimas_tres_v8 = (
    df_evaluaciones_v8["promedio"]
    .tail(3)
    .mean()
)

print("\nMEJOR EVALUACIÓN DE V8")
print(f"Paso: {int(mejor_fila_v8['paso_global']):,}")
print(f"Promedio: {mejor_fila_v8['promedio']:.2f}")
print(f"Mediana: {mejor_fila_v8['mediana']:.2f}")
print(f"Desviación: {mejor_fila_v8['desviacion']:.2f}")
print(f"Mínimo: {mejor_fila_v8['minimo']:.2f}")
print(f"Máximo: {mejor_fila_v8['maximo']:.2f}")

print(
    "\nPromedio de las últimas tres evaluaciones: "
    f"{promedio_ultimas_tres_v8:.2f}"
)

print(
    "\nCheckpoint disponible:",
    "OK" if RUTA_MODELO_V8.exists() else "NO ENCONTRADO",
)

    paso_global  promedio  mediana  desviacion  minimo  maximo
0         50000     168.0    110.0  111.292408    90.0   385.0
1        100000     192.0    155.0   77.304592   125.0   335.0
2        150000     354.0    390.0  130.820488   160.0   535.0
3        200000     250.0    155.0  151.129084   155.0   545.0
4        250000     453.0    360.0  218.965751   245.0   870.0
5        300000     326.0    295.0  112.178429   165.0   465.0
6        350000     242.0    290.0  106.423682    95.0   350.0
7        400000     524.0    520.0  235.868607   270.0   945.0
8        450000     440.0    455.0   98.640762   290.0   545.0
9        500000     470.0    515.0  125.777581   225.0   575.0
10       550000     269.0    280.0   27.459060   215.0   290.0
11       600000     474.0    460.0  147.898614   300.0   710.0
12       650000     444.0    465.0   72.897188   350.0   540.0
13       700000     482.0    490.0  135.151767   285.0   670.0
14       750000     420.0    390.0  175.071414   220.0   710.0
15       800000     522.0    465.0  189.857842   290.0   780.0
16       850000     495.0    510.0  137.767921   290.0   700.0
17       900000     351.0    400.0  115.299610   165.0   500.0
18       950000     509.0    480.0  141.046092   365.0   775.0
19      1000000     525.0    575.0  177.115781   260.0   775.0

MEJOR EVALUACIÓN DE V8
Paso: 1,000,000
Promedio: 525.00
Mediana: 575.00
Desviación: 177.12
Mínimo: 260.00
Máximo: 775.00

Promedio de las últimas tres evaluaciones: 461.67

Checkpoint disponible: OK

In [13]:
import torch
from pathlib import Path

from models import DQN
from evaluation import evaluar_modelo


RUTA_CHECKPOINT_V8 = Path(
    "../models/v8_dqn_per_a06_5step/mejor_modelo.pt"
)

checkpoint_v8 = torch.load(
    RUTA_CHECKPOINT_V8,
    map_location=device,
    weights_only=True,
)

mejor_dqn_v8 = DQN(
    n_acciones=6
).to(device)

mejor_dqn_v8.load_state_dict(
    checkpoint_v8["modelo_online_state_dict"]
)

mejor_dqn_v8.eval()

print(
    "Checkpoint cargado desde el paso:",
    f"{checkpoint_v8['paso']:,}",
)

Checkpoint cargado desde el paso: 1,000,000

In [16]:
N_EPISODIOS_EVALUACION = 30
SEMILLA_BASE_EVALUACION = 42

print(
    f"\nEvaluando V8: DQN + PER + 5-step durante "
    f"{N_EPISODIOS_EVALUACION} episodios...\n"
)

resultados_v8, resumen_v8 = evaluar_modelo(
    modelo=mejor_dqn_v8,
    config=config_per_alpha06_5step,
    device=device,
    n_episodios=N_EPISODIOS_EVALUACION,
    seed_base=SEMILLA_BASE_EVALUACION,
)

df_v8 = pd.DataFrame(resultados_v8)

df_v8["agente"] = "DQN + PER + 5-step"

df_v8 = df_v8[
    [
        "agente",
        "episodio",
        "seed",
        "recompensa_total",
        "pasos",
        "terminated",
        "truncated",
    ]
]

print("RESUMEN DE 30 EPISODIOS")

for metrica, valor in resumen_v8.items():
    print(f"{metrica}: {valor:.2f}")

display(df_v8.head(10))

Evaluando V8: DQN + PER + 5-step durante 30 episodios...

RESUMEN DE 30 EPISODIOS
promedio: 440.17
mediana: 410.00
desviacion: 124.38
minimo: 255.00
maximo: 805.00

,agente,episodio,seed,recompensa_total,pasos,terminated,truncated
0,DQN + PER + 5-step,0,42,325.0,541,True,False
1,DQN + PER + 5-step,1,43,390.0,579,True,False
2,DQN + PER + 5-step,2,44,405.0,761,True,False
3,DQN + PER + 5-step,3,45,300.0,712,True,False
4,DQN + PER + 5-step,4,46,255.0,657,True,False
5,DQN + PER + 5-step,5,47,515.0,606,True,False
6,DQN + PER + 5-step,6,48,540.0,625,True,False
7,DQN + PER + 5-step,7,49,435.0,880,True,False
8,DQN + PER + 5-step,8,50,395.0,711,True,False
9,DQN + PER + 5-step,9,51,305.0,600,True,False

In [17]:
import gc
from dataclasses import replace
from pathlib import Path

import torch

from train import entrenar_dqn
from models import DQN

config_v8_extendido = replace(
    config_per_alpha06_5step,
    nombre_experimento="v8_dqn_per_a06_5step_extendido",
    total_pasos=2_000_000,
)

directorio_v8_original = Path(
    "../models/v8_dqn_per_a06_5step"
)

ruta_checkpoint_v8 = (
    directorio_v8_original / "checkpoint_final.pt"
)

if not ruta_checkpoint_v8.exists():
    ruta_checkpoint_v8 = (
        directorio_v8_original / "ultimo_checkpoint.pt"
    )

if not ruta_checkpoint_v8.exists():
    raise FileNotFoundError(
        "No se encontró el checkpoint final de V8."
    )

globals().pop("mejor_dqn_v8", None)
globals().pop("checkpoint_v8", None)

gc.collect()

if device.type == "mps":
    torch.mps.empty_cache()

print("Checkpoint inicial:", ruta_checkpoint_v8)
print("Entrenamiento desde 1,000,000 hasta 2,000,000 pasos")

resultado_v8_extendido = entrenar_dqn(
    config=config_v8_extendido,
    clase_modelo=DQN,
    device=device,
    usar_double_dqn=False,
    ruta_checkpoint_inicial=ruta_checkpoint_v8,
)

print("\nENTRENAMIENTO EXTENDIDO DE V8 FINALIZADO")
print(
    "Mejor promedio durante la extensión: "
    f"{resultado_v8_extendido['mejor_promedio_evaluacion']:.2f}"
)

Checkpoint inicial: ../models/v8_dqn_per_a06_5step/checkpoint_final.pt
Entrenamiento desde 1,000,000 hasta 2,000,000 pasos
Reanudando entrenamiento desde el paso 1,000,000 (checkpoint: ../models/v8_dqn_per_a06_5step/checkpoint_final.pt)
Replay buffer: priorizado | alpha=0.6 | beta inicial=0.4
Retorno utilizado: 5-step
Paso 1,010,000/2,000,000 | episodio=26 | epsilon=0.100 | loss=0.0714 | Q=4.895
Paso 1,011,000/2,000,000 | episodio=28 | epsilon=0.100 | loss=0.0274 | Q=4.426
Paso 1,012,000/2,000,000 | episodio=32 | epsilon=0.100 | loss=0.0294 | Q=5.167
Paso 1,013,000/2,000,000 | episodio=34 | epsilon=0.100 | loss=0.0430 | Q=5.041
Paso 1,014,000/2,000,000 | episodio=37 | epsilon=0.100 | loss=0.0075 | Q=4.991
Paso 1,015,000/2,000,000 | episodio=39 | epsilon=0.100 | loss=0.0172 | Q=4.800
Paso 1,016,000/2,000,000 | episodio=41 | epsilon=0.100 | loss=0.0097 | Q=5.049
Paso 1,017,000/2,000,000 | episodio=45 | epsilon=0.100 | loss=0.0320 | Q=4.523
Paso 1,018,000/2,000,000 | episodio=47 | epsilon=0.100 | loss=0.0060 | Q=4.623
Paso 1,019,000/2,000,000 | episodio=49 | epsilon=0.100 | loss=0.0135 | Q=4.434
Paso 1,020,000/2,000,000 | episodio=52 | epsilon=0.100 | loss=0.0120 | Q=4.755
Paso 1,021,000/2,000,000 | episodio=54 | epsilon=0.100 | loss=0.0094 | Q=4.788
Paso 1,022,000/2,000,000 | episodio=57 | epsilon=0.100 | loss=0.0026 | Q=4.889
Paso 1,023,000/2,000,000 | episodio=60 | epsilon=0.100 | loss=0.0273 | Q=4.540
Paso 1,024,000/2,000,000 | episodio=64 | epsilon=0.100 | loss=0.0075 | Q=4.364
Paso 1,025,000/2,000,000 | episodio=65 | epsilon=0.100 | loss=0.0043 | Q=5.299
Paso 1,026,000/2,000,000 | episodio=68 | epsilon=0.100 | loss=0.0169 | Q=4.851
Paso 1,027,000/2,000,000 | episodio=71 | epsilon=0.100 | loss=0.0438 | Q=4.558
Paso 1,028,000/2,000,000 | episodio=74 | epsilon=0.100 | loss=0.0030 | Q=4.568
Paso 1,029,000/2,000,000 | episodio=76 | epsilon=0.100 | loss=0.0055 | Q=4.885
Paso 1,030,000/2,000,000 | episodio=78 | epsilon=0.100 | loss=0.0161 | Q=4.205
Paso 1,031,000/2,000,000 | episodio=81 | epsilon=0.100 | loss=0.0051 | Q=4.348
Paso 1,032,000/2,000,000 | episodio=85 | epsilon=0.100 | loss=0.0099 | Q=5.100
Paso 1,033,000/2,000,000 | episodio=88 | epsilon=0.100 | loss=0.0197 | Q=4.314
Paso 1,034,000/2,000,000 | episodio=91 | epsilon=0.100 | loss=0.0209 | Q=4.280
Paso 1,035,000/2,000,000 | episodio=94 | epsilon=0.100 | loss=0.0135 | Q=4.778
Paso 1,036,000/2,000,000 | episodio=96 | epsilon=0.100 | loss=0.0230 | Q=4.641
Paso 1,037,000/2,000,000 | episodio=98 | epsilon=0.100 | loss=0.0030 | Q=4.780
Paso 1,038,000/2,000,000 | episodio=101 | epsilon=0.100 | loss=0.0237 | Q=4.976
Paso 1,039,000/2,000,000 | episodio=103 | epsilon=0.100 | loss=0.0306 | Q=4.876
Paso 1,040,000/2,000,000 | episodio=105 | epsilon=0.100 | loss=0.0270 | Q=4.501
Paso 1,041,000/2,000,000 | episodio=108 | epsilon=0.100 | loss=0.0159 | Q=4.293
Paso 1,042,000/2,000,000 | episodio=111 | epsilon=0.100 | loss=0.0130 | Q=4.822
Paso 1,043,000/2,000,000 | episodio=114 | epsilon=0.100 | loss=0.0160 | Q=4.446
Paso 1,044,000/2,000,000 | episodio=118 | epsilon=0.100 | loss=0.0085 | Q=4.679
Paso 1,045,000/2,000,000 | episodio=120 | epsilon=0.100 | loss=0.0085 | Q=4.350
Paso 1,046,000/2,000,000 | episodio=123 | epsilon=0.100 | loss=0.0099 | Q=4.621
Paso 1,047,000/2,000,000 | episodio=125 | epsilon=0.100 | loss=0.0047 | Q=4.750
Paso 1,048,000/2,000,000 | episodio=127 | epsilon=0.100 | loss=0.0257 | Q=4.813
Paso 1,049,000/2,000,000 | episodio=130 | epsilon=0.100 | loss=0.0052 | Q=4.996
Paso 1,050,000/2,000,000 | episodio=132 | epsilon=0.100 | loss=0.0177 | Q=4.562

EVALUACIÓN | paso=1,050,000 | promedio=467.00 | mediana=450.00 | máximo=585.00

Paso 1,051,000/2,000,000 | episodio=134 | epsilon=0.100 | loss=0.0115 | Q=4.533
Paso 1,052,000/2,000,000 | episodio=136 | epsilon=0.100 | loss=0.0073 | Q=4.831
Paso 1,053,000/2,000,000 | episodio=139 | epsilon=0.100 | loss=0.0301 | Q=4.468
Paso 1,054,000/2,000,000 | episodio=141 | epsilon=0.100 | loss=0.0062 | Q=4.772
Paso 1,055,000/2,000,000 | episodio=143 | epsilon=0.100 | loss=0.0054 | Q=4.644
Paso 1,056,000/2,000,000 | episodio=146 | epsilon=0.100 | loss=0.0248 | Q=4.192
Paso 1,057,000/2,000,000 | episodio=148 | epsilon=0.100 | loss=0.0134 | Q=4.936
Paso 1,058,000/2,000,000 | episodio=151 | epsilon=0.100 | loss=0.0093 | Q=4.395
Paso 1,059,000/2,000,000 | episodio=153 | epsilon=0.100 | loss=0.0098 | Q=4.584
Paso 1,060,000/2,000,000 | episodio=154 | epsilon=0.100 | loss=0.0122 | Q=4.549
Paso 1,061,000/2,000,000 | episodio=156 | epsilon=0.100 | loss=0.0110 | Q=4.785
Paso 1,062,000/2,000,000 | episodio=159 | epsilon=0.100 | loss=0.0084 | Q=4.607
Paso 1,063,000/2,000,000 | episodio=162 | epsilon=0.100 | loss=0.0123 | Q=4.561
Paso 1,064,000/2,000,000 | episodio=166 | epsilon=0.100 | loss=0.0197 | Q=4.387
Paso 1,065,000/2,000,000 | episodio=168 | epsilon=0.100 | loss=0.0144 | Q=4.394
Paso 1,066,000/2,000,000 | episodio=170 | epsilon=0.100 | loss=0.0136 | Q=4.458
Paso 1,067,000/2,000,000 | episodio=173 | epsilon=0.100 | loss=0.0090 | Q=4.930
Paso 1,068,000/2,000,000 | episodio=175 | epsilon=0.100 | loss=0.0301 | Q=4.682
Paso 1,069,000/2,000,000 | episodio=177 | epsilon=0.100 | loss=0.0164 | Q=4.597
Paso 1,070,000/2,000,000 | episodio=180 | epsilon=0.100 | loss=0.0054 | Q=4.763
Paso 1,071,000/2,000,000 | episodio=182 | epsilon=0.100 | loss=0.0077 | Q=5.280
Paso 1,072,000/2,000,000 | episodio=186 | epsilon=0.100 | loss=0.0078 | Q=4.897
Paso 1,073,000/2,000,000 | episodio=186 | epsilon=0.100 | loss=0.0182 | Q=4.398
Paso 1,074,000/2,000,000 | episodio=188 | epsilon=0.100 | loss=0.0241 | Q=5.013
Paso 1,075,000/2,000,000 | episodio=191 | epsilon=0.100 | loss=0.0104 | Q=4.671
Paso 1,076,000/2,000,000 | episodio=194 | epsilon=0.100 | loss=0.0387 | Q=4.522
Paso 1,077,000/2,000,000 | episodio=196 | epsilon=0.100 | loss=0.0066 | Q=4.699
Paso 1,078,000/2,000,000 | episodio=199 | epsilon=0.100 | loss=0.0175 | Q=4.270
Paso 1,079,000/2,000,000 | episodio=202 | epsilon=0.100 | loss=0.0057 | Q=4.694
Paso 1,080,000/2,000,000 | episodio=204 | epsilon=0.100 | loss=0.0089 | Q=5.073
Paso 1,081,000/2,000,000 | episodio=206 | epsilon=0.100 | loss=0.0160 | Q=4.719
Paso 1,082,000/2,000,000 | episodio=209 | epsilon=0.100 | loss=0.0068 | Q=5.226
Paso 1,083,000/2,000,000 | episodio=211 | epsilon=0.100 | loss=0.0149 | Q=4.445
Paso 1,084,000/2,000,000 | episodio=214 | epsilon=0.100 | loss=0.0154 | Q=4.791
Paso 1,085,000/2,000,000 | episodio=217 | epsilon=0.100 | loss=0.0188 | Q=4.237
Paso 1,086,000/2,000,000 | episodio=219 | epsilon=0.100 | loss=0.0144 | Q=4.253
Paso 1,087,000/2,000,000 | episodio=221 | epsilon=0.100 | loss=0.0069 | Q=4.745
Paso 1,088,000/2,000,000 | episodio=223 | epsilon=0.100 | loss=0.0056 | Q=4.703
Paso 1,089,000/2,000,000 | episodio=225 | epsilon=0.100 | loss=0.0157 | Q=4.946
Paso 1,090,000/2,000,000 | episodio=228 | epsilon=0.100 | loss=0.0104 | Q=4.857
Paso 1,091,000/2,000,000 | episodio=230 | epsilon=0.100 | loss=0.0163 | Q=4.570
Paso 1,092,000/2,000,000 | episodio=233 | epsilon=0.100 | loss=0.0087 | Q=5.140
Paso 1,093,000/2,000,000 | episodio=235 | epsilon=0.100 | loss=0.0053 | Q=4.279
Paso 1,094,000/2,000,000 | episodio=238 | epsilon=0.100 | loss=0.0067 | Q=4.387
Paso 1,095,000/2,000,000 | episodio=240 | epsilon=0.100 | loss=0.0336 | Q=4.451
Paso 1,096,000/2,000,000 | episodio=242 | epsilon=0.100 | loss=0.0182 | Q=4.666
Paso 1,097,000/2,000,000 | episodio=244 | epsilon=0.100 | loss=0.0375 | Q=4.755
Paso 1,098,000/2,000,000 | episodio=247 | epsilon=0.100 | loss=0.0118 | Q=5.263
Paso 1,099,000/2,000,000 | episodio=250 | epsilon=0.100 | loss=0.0339 | Q=4.707
Paso 1,100,000/2,000,000 | episodio=253 | epsilon=0.100 | loss=0.0152 | Q=4.960

EVALUACIÓN | paso=1,100,000 | promedio=394.00 | mediana=425.00 | máximo=490.00

Paso 1,101,000/2,000,000 | episodio=255 | epsilon=0.100 | loss=0.0042 | Q=4.891
Paso 1,102,000/2,000,000 | episodio=258 | epsilon=0.100 | loss=0.0126 | Q=5.300
Paso 1,103,000/2,000,000 | episodio=261 | epsilon=0.100 | loss=0.0125 | Q=4.487
Paso 1,104,000/2,000,000 | episodio=264 | epsilon=0.100 | loss=0.0076 | Q=4.969
Paso 1,105,000/2,000,000 | episodio=266 | epsilon=0.100 | loss=0.0078 | Q=4.616
Paso 1,106,000/2,000,000 | episodio=269 | epsilon=0.100 | loss=0.0092 | Q=5.013
Paso 1,107,000/2,000,000 | episodio=271 | epsilon=0.100 | loss=0.0292 | Q=4.067
Paso 1,108,000/2,000,000 | episodio=273 | epsilon=0.100 | loss=0.0180 | Q=4.964
Paso 1,109,000/2,000,000 | episodio=275 | epsilon=0.100 | loss=0.0039 | Q=4.474
Paso 1,110,000/2,000,000 | episodio=278 | epsilon=0.100 | loss=0.0141 | Q=4.925
Paso 1,111,000/2,000,000 | episodio=280 | epsilon=0.100 | loss=0.0102 | Q=5.011
Paso 1,112,000/2,000,000 | episodio=283 | epsilon=0.100 | loss=0.0113 | Q=4.860
Paso 1,113,000/2,000,000 | episodio=284 | epsilon=0.100 | loss=0.0289 | Q=4.686
Paso 1,114,000/2,000,000 | episodio=286 | epsilon=0.100 | loss=0.0125 | Q=4.228
Paso 1,115,000/2,000,000 | episodio=288 | epsilon=0.100 | loss=0.0134 | Q=5.310
Paso 1,116,000/2,000,000 | episodio=290 | epsilon=0.100 | loss=0.0053 | Q=5.181
Paso 1,117,000/2,000,000 | episodio=293 | epsilon=0.100 | loss=0.0118 | Q=5.118
Paso 1,118,000/2,000,000 | episodio=295 | epsilon=0.100 | loss=0.0214 | Q=4.792
Paso 1,119,000/2,000,000 | episodio=298 | epsilon=0.100 | loss=0.0189 | Q=4.757
Paso 1,120,000/2,000,000 | episodio=300 | epsilon=0.100 | loss=0.0368 | Q=5.003
Paso 1,121,000/2,000,000 | episodio=302 | epsilon=0.100 | loss=0.0043 | Q=4.741
Paso 1,122,000/2,000,000 | episodio=305 | epsilon=0.100 | loss=0.0091 | Q=4.341
Paso 1,123,000/2,000,000 | episodio=307 | epsilon=0.100 | loss=0.0074 | Q=4.539
Paso 1,124,000/2,000,000 | episodio=310 | epsilon=0.100 | loss=0.0123 | Q=4.884
Paso 1,125,000/2,000,000 | episodio=313 | epsilon=0.100 | loss=0.0182 | Q=4.957
Paso 1,126,000/2,000,000 | episodio=316 | epsilon=0.100 | loss=0.0135 | Q=4.531
Paso 1,127,000/2,000,000 | episodio=319 | epsilon=0.100 | loss=0.0168 | Q=4.927
Paso 1,128,000/2,000,000 | episodio=322 | epsilon=0.100 | loss=0.0152 | Q=4.914
Paso 1,129,000/2,000,000 | episodio=325 | epsilon=0.100 | loss=0.0168 | Q=5.005
Paso 1,130,000/2,000,000 | episodio=328 | epsilon=0.100 | loss=0.0090 | Q=4.989
Paso 1,131,000/2,000,000 | episodio=330 | epsilon=0.100 | loss=0.0046 | Q=4.688
Paso 1,132,000/2,000,000 | episodio=334 | epsilon=0.100 | loss=0.0364 | Q=3.876
Paso 1,133,000/2,000,000 | episodio=336 | epsilon=0.100 | loss=0.0348 | Q=5.202
Paso 1,134,000/2,000,000 | episodio=339 | epsilon=0.100 | loss=0.0085 | Q=4.652
Paso 1,135,000/2,000,000 | episodio=341 | epsilon=0.100 | loss=0.0181 | Q=5.111
Paso 1,136,000/2,000,000 | episodio=343 | epsilon=0.100 | loss=0.0130 | Q=4.637
Paso 1,137,000/2,000,000 | episodio=346 | epsilon=0.100 | loss=0.0146 | Q=4.902
Paso 1,138,000/2,000,000 | episodio=348 | epsilon=0.100 | loss=0.0265 | Q=4.404
Paso 1,139,000/2,000,000 | episodio=350 | epsilon=0.100 | loss=0.0074 | Q=4.944
Paso 1,140,000/2,000,000 | episodio=352 | epsilon=0.100 | loss=0.0075 | Q=4.639
Paso 1,141,000/2,000,000 | episodio=354 | epsilon=0.100 | loss=0.0078 | Q=4.572
Paso 1,142,000/2,000,000 | episodio=356 | epsilon=0.100 | loss=0.0185 | Q=4.945
Paso 1,143,000/2,000,000 | episodio=361 | epsilon=0.100 | loss=0.0100 | Q=5.067
Paso 1,144,000/2,000,000 | episodio=363 | epsilon=0.100 | loss=0.0105 | Q=4.499
Paso 1,145,000/2,000,000 | episodio=367 | epsilon=0.100 | loss=0.0467 | Q=4.357
Paso 1,146,000/2,000,000 | episodio=369 | epsilon=0.100 | loss=0.0225 | Q=4.587
Paso 1,147,000/2,000,000 | episodio=372 | epsilon=0.100 | loss=0.0309 | Q=4.555
Paso 1,148,000/2,000,000 | episodio=375 | epsilon=0.100 | loss=0.0190 | Q=4.985
Paso 1,149,000/2,000,000 | episodio=378 | epsilon=0.100 | loss=0.0264 | Q=5.197
Paso 1,150,000/2,000,000 | episodio=382 | epsilon=0.100 | loss=0.0348 | Q=4.405

EVALUACIÓN | paso=1,150,000 | promedio=421.00 | mediana=410.00 | máximo=695.00

Paso 1,151,000/2,000,000 | episodio=383 | epsilon=0.100 | loss=0.0175 | Q=4.946
Paso 1,152,000/2,000,000 | episodio=387 | epsilon=0.100 | loss=0.0281 | Q=4.773
Paso 1,153,000/2,000,000 | episodio=390 | epsilon=0.100 | loss=0.0125 | Q=4.131
Paso 1,154,000/2,000,000 | episodio=393 | epsilon=0.100 | loss=0.0200 | Q=4.199
Paso 1,155,000/2,000,000 | episodio=395 | epsilon=0.100 | loss=0.0070 | Q=4.424
Paso 1,156,000/2,000,000 | episodio=398 | epsilon=0.100 | loss=0.0134 | Q=4.518
Paso 1,157,000/2,000,000 | episodio=400 | epsilon=0.100 | loss=0.0156 | Q=4.757
Paso 1,158,000/2,000,000 | episodio=402 | epsilon=0.100 | loss=0.0169 | Q=4.818
Paso 1,159,000/2,000,000 | episodio=405 | epsilon=0.100 | loss=0.0045 | Q=4.720
Paso 1,160,000/2,000,000 | episodio=408 | epsilon=0.100 | loss=0.0170 | Q=4.384
Paso 1,161,000/2,000,000 | episodio=411 | epsilon=0.100 | loss=0.0130 | Q=4.372
Paso 1,162,000/2,000,000 | episodio=414 | epsilon=0.100 | loss=0.0230 | Q=4.444
Paso 1,163,000/2,000,000 | episodio=416 | epsilon=0.100 | loss=0.0068 | Q=4.834
Paso 1,164,000/2,000,000 | episodio=419 | epsilon=0.100 | loss=0.0114 | Q=4.917
Paso 1,165,000/2,000,000 | episodio=421 | epsilon=0.100 | loss=0.0196 | Q=4.521
Paso 1,166,000/2,000,000 | episodio=424 | epsilon=0.100 | loss=0.0280 | Q=5.082
Paso 1,167,000/2,000,000 | episodio=428 | epsilon=0.100 | loss=0.0066 | Q=5.238
Paso 1,168,000/2,000,000 | episodio=430 | epsilon=0.100 | loss=0.0155 | Q=4.801
Paso 1,169,000/2,000,000 | episodio=432 | epsilon=0.100 | loss=0.0274 | Q=4.312
Paso 1,170,000/2,000,000 | episodio=434 | epsilon=0.100 | loss=0.0337 | Q=4.437
Paso 1,171,000/2,000,000 | episodio=436 | epsilon=0.100 | loss=0.0307 | Q=4.643
Paso 1,172,000/2,000,000 | episodio=439 | epsilon=0.100 | loss=0.0186 | Q=3.809
Paso 1,173,000/2,000,000 | episodio=441 | epsilon=0.100 | loss=0.0186 | Q=4.685
Paso 1,174,000/2,000,000 | episodio=444 | epsilon=0.100 | loss=0.0113 | Q=5.267
Paso 1,175,000/2,000,000 | episodio=447 | epsilon=0.100 | loss=0.0088 | Q=4.280
Paso 1,176,000/2,000,000 | episodio=449 | epsilon=0.100 | loss=0.0143 | Q=5.122
Paso 1,177,000/2,000,000 | episodio=451 | epsilon=0.100 | loss=0.0045 | Q=4.520
Paso 1,178,000/2,000,000 | episodio=453 | epsilon=0.100 | loss=0.0094 | Q=5.240
Paso 1,179,000/2,000,000 | episodio=457 | epsilon=0.100 | loss=0.0054 | Q=4.806
Paso 1,180,000/2,000,000 | episodio=459 | epsilon=0.100 | loss=0.0211 | Q=5.044
Paso 1,181,000/2,000,000 | episodio=462 | epsilon=0.100 | loss=0.0087 | Q=4.093
Paso 1,182,000/2,000,000 | episodio=465 | epsilon=0.100 | loss=0.0065 | Q=5.000
Paso 1,183,000/2,000,000 | episodio=467 | epsilon=0.100 | loss=0.0036 | Q=4.371
Paso 1,184,000/2,000,000 | episodio=470 | epsilon=0.100 | loss=0.0179 | Q=4.277
Paso 1,185,000/2,000,000 | episodio=472 | epsilon=0.100 | loss=0.0049 | Q=4.321
Paso 1,186,000/2,000,000 | episodio=475 | epsilon=0.100 | loss=0.0266 | Q=4.781
Paso 1,187,000/2,000,000 | episodio=477 | epsilon=0.100 | loss=0.0175 | Q=5.172
Paso 1,188,000/2,000,000 | episodio=479 | epsilon=0.100 | loss=0.0102 | Q=5.042
Paso 1,189,000/2,000,000 | episodio=480 | epsilon=0.100 | loss=0.0225 | Q=4.407
Paso 1,190,000/2,000,000 | episodio=484 | epsilon=0.100 | loss=0.0115 | Q=4.640
Paso 1,191,000/2,000,000 | episodio=487 | epsilon=0.100 | loss=0.0115 | Q=4.406
Paso 1,192,000/2,000,000 | episodio=488 | epsilon=0.100 | loss=0.0140 | Q=4.357
Paso 1,193,000/2,000,000 | episodio=491 | epsilon=0.100 | loss=0.0044 | Q=5.118
Paso 1,194,000/2,000,000 | episodio=494 | epsilon=0.100 | loss=0.0059 | Q=4.856
Paso 1,195,000/2,000,000 | episodio=496 | epsilon=0.100 | loss=0.0212 | Q=4.901
Paso 1,196,000/2,000,000 | episodio=499 | epsilon=0.100 | loss=0.0174 | Q=4.884
Paso 1,197,000/2,000,000 | episodio=501 | epsilon=0.100 | loss=0.0112 | Q=4.791
Paso 1,198,000/2,000,000 | episodio=503 | epsilon=0.100 | loss=0.0089 | Q=4.517
Paso 1,199,000/2,000,000 | episodio=505 | epsilon=0.100 | loss=0.0084 | Q=4.274
Paso 1,200,000/2,000,000 | episodio=508 | epsilon=0.100 | loss=0.0162 | Q=4.954

EVALUACIÓN | paso=1,200,000 | promedio=528.00 | mediana=515.00 | máximo=600.00

Paso 1,201,000/2,000,000 | episodio=509 | epsilon=0.100 | loss=0.0114 | Q=4.957
Paso 1,202,000/2,000,000 | episodio=512 | epsilon=0.100 | loss=0.0182 | Q=5.135
Paso 1,203,000/2,000,000 | episodio=515 | epsilon=0.100 | loss=0.0090 | Q=4.740
Paso 1,204,000/2,000,000 | episodio=518 | epsilon=0.100 | loss=0.0145 | Q=4.907
Paso 1,205,000/2,000,000 | episodio=521 | epsilon=0.100 | loss=0.0025 | Q=4.409
Paso 1,206,000/2,000,000 | episodio=522 | epsilon=0.100 | loss=0.0073 | Q=5.261
Paso 1,207,000/2,000,000 | episodio=524 | epsilon=0.100 | loss=0.0110 | Q=4.627
Paso 1,208,000/2,000,000 | episodio=527 | epsilon=0.100 | loss=0.0152 | Q=5.221
Paso 1,209,000/2,000,000 | episodio=530 | epsilon=0.100 | loss=0.0103 | Q=4.373
Paso 1,210,000/2,000,000 | episodio=533 | epsilon=0.100 | loss=0.0117 | Q=4.914
Paso 1,211,000/2,000,000 | episodio=537 | epsilon=0.100 | loss=0.0145 | Q=5.045
Paso 1,212,000/2,000,000 | episodio=540 | epsilon=0.100 | loss=0.0134 | Q=4.860
Paso 1,213,000/2,000,000 | episodio=541 | epsilon=0.100 | loss=0.0114 | Q=4.722
Paso 1,214,000/2,000,000 | episodio=544 | epsilon=0.100 | loss=0.0190 | Q=4.765
Paso 1,215,000/2,000,000 | episodio=546 | epsilon=0.100 | loss=0.0049 | Q=4.755
Paso 1,216,000/2,000,000 | episodio=549 | epsilon=0.100 | loss=0.0062 | Q=4.492
Paso 1,217,000/2,000,000 | episodio=551 | epsilon=0.100 | loss=0.0187 | Q=4.586
Paso 1,218,000/2,000,000 | episodio=553 | epsilon=0.100 | loss=0.0094 | Q=4.784
Paso 1,219,000/2,000,000 | episodio=556 | epsilon=0.100 | loss=0.0099 | Q=4.889
Paso 1,220,000/2,000,000 | episodio=558 | epsilon=0.100 | loss=0.0093 | Q=4.910
Paso 1,221,000/2,000,000 | episodio=560 | epsilon=0.100 | loss=0.0259 | Q=4.767
Paso 1,222,000/2,000,000 | episodio=563 | epsilon=0.100 | loss=0.0123 | Q=4.730
Paso 1,223,000/2,000,000 | episodio=566 | epsilon=0.100 | loss=0.0042 | Q=4.356
Paso 1,224,000/2,000,000 | episodio=568 | epsilon=0.100 | loss=0.0042 | Q=4.841
Paso 1,225,000/2,000,000 | episodio=571 | epsilon=0.100 | loss=0.0091 | Q=4.824
Paso 1,226,000/2,000,000 | episodio=574 | epsilon=0.100 | loss=0.0086 | Q=4.538
Paso 1,227,000/2,000,000 | episodio=577 | epsilon=0.100 | loss=0.0068 | Q=4.707
Paso 1,228,000/2,000,000 | episodio=579 | epsilon=0.100 | loss=0.0071 | Q=4.783
Paso 1,229,000/2,000,000 | episodio=581 | epsilon=0.100 | loss=0.0148 | Q=4.846
Paso 1,230,000/2,000,000 | episodio=584 | epsilon=0.100 | loss=0.0059 | Q=4.935
Paso 1,231,000/2,000,000 | episodio=588 | epsilon=0.100 | loss=0.0011 | Q=4.912
Paso 1,232,000/2,000,000 | episodio=590 | epsilon=0.100 | loss=0.0105 | Q=4.867
Paso 1,233,000/2,000,000 | episodio=593 | epsilon=0.100 | loss=0.0047 | Q=4.945
Paso 1,234,000/2,000,000 | episodio=596 | epsilon=0.100 | loss=0.0111 | Q=4.723
Paso 1,235,000/2,000,000 | episodio=599 | epsilon=0.100 | loss=0.0067 | Q=5.273
Paso 1,236,000/2,000,000 | episodio=601 | epsilon=0.100 | loss=0.0085 | Q=4.905
Paso 1,237,000/2,000,000 | episodio=603 | epsilon=0.100 | loss=0.0104 | Q=4.636
Paso 1,238,000/2,000,000 | episodio=606 | epsilon=0.100 | loss=0.0131 | Q=5.110
Paso 1,239,000/2,000,000 | episodio=610 | epsilon=0.100 | loss=0.0184 | Q=4.615
Paso 1,240,000/2,000,000 | episodio=613 | epsilon=0.100 | loss=0.0093 | Q=4.293
Paso 1,241,000/2,000,000 | episodio=616 | epsilon=0.100 | loss=0.0191 | Q=4.927
Paso 1,242,000/2,000,000 | episodio=619 | epsilon=0.100 | loss=0.0241 | Q=4.670
Paso 1,243,000/2,000,000 | episodio=621 | epsilon=0.100 | loss=0.0053 | Q=4.654
Paso 1,244,000/2,000,000 | episodio=623 | epsilon=0.100 | loss=0.0169 | Q=4.689
Paso 1,245,000/2,000,000 | episodio=625 | epsilon=0.100 | loss=0.0092 | Q=5.095
Paso 1,246,000/2,000,000 | episodio=628 | epsilon=0.100 | loss=0.0114 | Q=5.087
Paso 1,247,000/2,000,000 | episodio=631 | epsilon=0.100 | loss=0.0151 | Q=5.041
Paso 1,248,000/2,000,000 | episodio=632 | epsilon=0.100 | loss=0.0261 | Q=4.816
Paso 1,249,000/2,000,000 | episodio=635 | epsilon=0.100 | loss=0.0191 | Q=4.818
Paso 1,250,000/2,000,000 | episodio=638 | epsilon=0.100 | loss=0.0159 | Q=4.311

EVALUACIÓN | paso=1,250,000 | promedio=523.00 | mediana=570.00 | máximo=740.00


In [18]:
from pathlib import Path
import pandas as pd
from IPython.display import display


RUTA_LOG_V8_EXTENDIDO = Path(
    "../logs/entrenamientos/"
    "v8_dqn_per_a06_5step_extendido/"
    "evaluaciones.csv"
)

RUTA_MEJOR_MODELO_V8_EXTENDIDO = Path(
    "../models/"
    "v8_dqn_per_a06_5step_extendido/"
    "mejor_modelo.pt"
)

df_evaluaciones_v8_extendido = pd.read_csv(
    RUTA_LOG_V8_EXTENDIDO
)

display(df_evaluaciones_v8_extendido)

mejor_fila_v8_extendido = (
    df_evaluaciones_v8_extendido.loc[
        df_evaluaciones_v8_extendido["promedio"].idxmax()
    ]
)

promedio_ultimas_tres_v8_extendido = (
    df_evaluaciones_v8_extendido["promedio"]
    .tail(3)
    .mean()
)

print("\nMEJOR EVALUACIÓN DE V8 EXTENDIDO")
print(
    f"Paso: "
    f"{int(mejor_fila_v8_extendido['paso_global']):,}"
)
print(
    f"Promedio: "
    f"{mejor_fila_v8_extendido['promedio']:.2f}"
)
print(
    f"Mediana: "
    f"{mejor_fila_v8_extendido['mediana']:.2f}"
)
print(
    f"Desviación: "
    f"{mejor_fila_v8_extendido['desviacion']:.2f}"
)
print(
    f"Mínimo: "
    f"{mejor_fila_v8_extendido['minimo']:.2f}"
)
print(
    f"Máximo: "
    f"{mejor_fila_v8_extendido['maximo']:.2f}"
)

print(
    "\nPromedio de las últimas tres evaluaciones: "
    f"{promedio_ultimas_tres_v8_extendido:.2f}"
)

print(
    "\nCheckpoint disponible:",
    (
        "OK"
        if RUTA_MEJOR_MODELO_V8_EXTENDIDO.exists()
        else "NO ENCONTRADO"
    ),
)

    paso_global  promedio  mediana  desviacion  minimo  maximo
0       1050000     467.0    450.0   98.315818   345.0   585.0
1       1100000     394.0    425.0   80.461171   280.0   490.0
2       1150000     421.0    410.0  159.417690   215.0   695.0
3       1200000     528.0    515.0   50.059964   465.0   600.0
4       1250000     523.0    570.0  149.251466   320.0   740.0
5       1300000     423.0    380.0   94.424573   320.0   570.0
6       1350000     368.0    365.0  124.120909   165.0   520.0
7       1400000     458.0    505.0  133.364163   250.0   600.0
8       1450000     264.0    275.0   50.833060   175.0   330.0
9       1500000     266.0    265.0   31.843367   220.0   310.0
10      1550000     452.0    440.0   98.823074   300.0   605.0
11      1600000     421.0    415.0   78.319857   320.0   555.0
12      1650000     576.0    660.0  234.059821   130.0   770.0
13      1700000     534.0    515.0  115.472941   340.0   655.0
14      1750000     549.0    530.0   86.740994   470.0   705.0
15      1800000     409.0    445.0  154.641521   175.0   610.0
16      1850000     503.0    500.0  209.370485   295.0   880.0
17      1900000     508.0    575.0   89.252451   380.0   590.0
18      1950000     563.0    575.0  131.855982   375.0   755.0
19      2000000     328.0    305.0  127.694949   175.0   490.0

MEJOR EVALUACIÓN DE V8 EXTENDIDO
Paso: 1,650,000
Promedio: 576.00
Mediana: 660.00
Desviación: 234.06
Mínimo: 130.00
Máximo: 770.00

Promedio de las últimas tres evaluaciones: 466.33

Checkpoint disponible: OK

In [19]:
import gc
from pathlib import Path

import torch

from models import DQN


RUTA_MEJOR_V8_EXTENDIDO = Path(
    "../models/"
    "v8_dqn_per_a06_5step_extendido/"
    "mejor_modelo.pt"
)

checkpoint_v8_extendido = torch.load(
    RUTA_MEJOR_V8_EXTENDIDO,
    map_location=device,
    weights_only=True,
)

mejor_v8_extendido = DQN(
    n_acciones=6
).to(device)

mejor_v8_extendido.load_state_dict(
    checkpoint_v8_extendido["modelo_online_state_dict"]
)

mejor_v8_extendido.eval()

print(
    "Checkpoint cargado desde el paso:",
    f"{checkpoint_v8_extendido['paso']:,}",
)

Checkpoint cargado desde el paso: 1,650,000

In [20]:
N_EPISODIOS_EVALUACION = 30
SEMILLA_BASE_EVALUACION = 42

print(
    "\nEvaluando V8 extendido durante "
    f"{N_EPISODIOS_EVALUACION} episodios...\n"
)

resultados_v8_extendido, resumen_v8_extendido = evaluar_modelo(
    modelo=mejor_v8_extendido,
    config=config_v8_extendido,
    device=device,
    n_episodios=N_EPISODIOS_EVALUACION,
    seed_base=SEMILLA_BASE_EVALUACION,
)

df_v8_extendido = pd.DataFrame(
    resultados_v8_extendido
)

df_v8_extendido["agente"] = (
    "DQN + PER a=0.6 + 5-step extendido"
)

df_v8_extendido = df_v8_extendido[
    [
        "agente",
        "episodio",
        "seed",
        "recompensa_total",
        "pasos",
        "terminated",
        "truncated",
    ]
]

print("RESUMEN DE 30 EPISODIOS")

for metrica, valor in resumen_v8_extendido.items():
    print(f"{metrica}: {valor:.2f}")

display(df_v8_extendido.head(10))

Evaluando V8 extendido durante 30 episodios...

RESUMEN DE 30 EPISODIOS
promedio: 455.33
mediana: 472.50
desviacion: 125.69
minimo: 190.00
maximo: 695.00

,agente,episodio,seed,recompensa_total,pasos,terminated,truncated
0,DQN + PER a=0.6 + 5-step extendido,0,42,190.0,483,True,False
1,DQN + PER a=0.6 + 5-step extendido,1,43,470.0,878,True,False
2,DQN + PER a=0.6 + 5-step extendido,2,44,525.0,1062,True,False
3,DQN + PER a=0.6 + 5-step extendido,3,45,335.0,732,True,False
4,DQN + PER a=0.6 + 5-step extendido,4,46,310.0,584,True,False
5,DQN + PER a=0.6 + 5-step extendido,5,47,350.0,643,True,False
6,DQN + PER a=0.6 + 5-step extendido,6,48,590.0,1035,True,False
7,DQN + PER a=0.6 + 5-step extendido,7,49,575.0,1029,True,False
8,DQN + PER a=0.6 + 5-step extendido,8,50,635.0,896,True,False
9,DQN + PER a=0.6 + 5-step extendido,9,51,475.0,683,True,False

In [21]:
from pathlib import Path

print("CARPETAS RELACIONADAS CON 3-STEP")

for ruta in sorted(Path("../models").glob("*3*step*")):
    print(ruta)

CARPETAS RELACIONADAS CON 3-STEP
../models/smoke_test_dqn_per_3step
../models/v6_dqn_per_3step
../models/v7_dqn_per_a04_3step
../models/v7_dqn_per_a04_3step_extendido

## Extención de la primera variación de hiperparámetros

In [22]:
import gc
from dataclasses import replace
from pathlib import Path

import torch

from train import entrenar_dqn
from models import DQN


RUTA_CHECKPOINT_V6 = Path(
    "../models/v6_dqn_per_3step/mejor_modelo.pt"
)

if not RUTA_CHECKPOINT_V6.exists():
    raise FileNotFoundError(
        f"No se encontró el checkpoint: {RUTA_CHECKPOINT_V6}"
    )

config_v6_extendido = replace(
    config_per_alpha06_5step,
    nombre_experimento="v6_dqn_per_3step_extendido",
    total_pasos=2_000_000,
    n_step=3,
)

objetos_temporales = [
    "mejor_v8_extendido",
    "checkpoint_v8_extendido",
    "resultado_v8_extendido",
]

for nombre in objetos_temporales:
    globals().pop(nombre, None)

gc.collect()

if device.type == "mps":
    torch.mps.empty_cache()

print("Checkpoint inicial:", RUTA_CHECKPOINT_V6)
print("Configuración: PER alpha=0.6 | retorno 3-step")
print("Entrenamiento desde 700,000 hasta 2,000,000 pasos")

resultado_v6_extendido = entrenar_dqn(
    config=config_v6_extendido,
    clase_modelo=DQN,
    device=device,
    usar_double_dqn=False,
    ruta_checkpoint_inicial=RUTA_CHECKPOINT_V6,
)

print("\nENTRENAMIENTO EXTENDIDO DE V6 FINALIZADO")
print(
    "Mejor promedio durante la extensión: "
    f"{resultado_v6_extendido['mejor_promedio_evaluacion']:.2f}"
)

Checkpoint inicial: ../models/v6_dqn_per_3step/mejor_modelo.pt
Configuración: PER alpha=0.6 | retorno 3-step
Entrenamiento desde 700,000 hasta 2,000,000 pasos
Reanudando entrenamiento desde el paso 700,000 (checkpoint: ../models/v6_dqn_per_3step/mejor_modelo.pt)
Replay buffer: priorizado | alpha=0.6 | beta inicial=0.4
Retorno utilizado: 3-step
Paso 710,000/2,000,000 | episodio=27 | epsilon=0.100 | loss=0.1023 | Q=4.689
Paso 711,000/2,000,000 | episodio=29 | epsilon=0.100 | loss=0.0189 | Q=4.360
Paso 712,000/2,000,000 | episodio=33 | epsilon=0.100 | loss=0.0084 | Q=4.269
Paso 713,000/2,000,000 | episodio=36 | epsilon=0.100 | loss=0.0189 | Q=4.730
Paso 714,000/2,000,000 | episodio=40 | epsilon=0.100 | loss=0.0112 | Q=4.355
Paso 715,000/2,000,000 | episodio=41 | epsilon=0.100 | loss=0.0072 | Q=4.891
Paso 716,000/2,000,000 | episodio=43 | epsilon=0.100 | loss=0.0054 | Q=4.495
Paso 717,000/2,000,000 | episodio=46 | epsilon=0.100 | loss=0.0151 | Q=4.454
Paso 718,000/2,000,000 | episodio=49 | epsilon=0.100 | loss=0.0161 | Q=4.403
Paso 719,000/2,000,000 | episodio=51 | epsilon=0.100 | loss=0.0125 | Q=4.226
Paso 720,000/2,000,000 | episodio=54 | epsilon=0.100 | loss=0.0094 | Q=4.583
Paso 721,000/2,000,000 | episodio=57 | epsilon=0.100 | loss=0.0120 | Q=4.742
Paso 722,000/2,000,000 | episodio=59 | epsilon=0.100 | loss=0.0148 | Q=4.463
Paso 723,000/2,000,000 | episodio=61 | epsilon=0.100 | loss=0.0121 | Q=4.403
Paso 724,000/2,000,000 | episodio=63 | epsilon=0.100 | loss=0.0091 | Q=4.579
Paso 725,000/2,000,000 | episodio=65 | epsilon=0.100 | loss=0.0179 | Q=4.176
Paso 726,000/2,000,000 | episodio=67 | epsilon=0.100 | loss=0.0060 | Q=4.476
Paso 727,000/2,000,000 | episodio=70 | epsilon=0.100 | loss=0.0109 | Q=4.333
Paso 728,000/2,000,000 | episodio=72 | epsilon=0.100 | loss=0.0067 | Q=4.691
Paso 729,000/2,000,000 | episodio=74 | epsilon=0.100 | loss=0.0133 | Q=4.370
Paso 730,000/2,000,000 | episodio=76 | epsilon=0.100 | loss=0.0083 | Q=4.592
Paso 731,000/2,000,000 | episodio=79 | epsilon=0.100 | loss=0.0114 | Q=4.265
Paso 732,000/2,000,000 | episodio=82 | epsilon=0.100 | loss=0.0123 | Q=4.445
Paso 733,000/2,000,000 | episodio=84 | epsilon=0.100 | loss=0.0038 | Q=4.669
Paso 734,000/2,000,000 | episodio=86 | epsilon=0.100 | loss=0.0092 | Q=4.435
Paso 735,000/2,000,000 | episodio=89 | epsilon=0.100 | loss=0.0105 | Q=4.449
Paso 736,000/2,000,000 | episodio=92 | epsilon=0.100 | loss=0.0038 | Q=5.001
Paso 737,000/2,000,000 | episodio=95 | epsilon=0.100 | loss=0.0113 | Q=4.136
Paso 738,000/2,000,000 | episodio=97 | epsilon=0.100 | loss=0.0118 | Q=4.452
Paso 739,000/2,000,000 | episodio=101 | epsilon=0.100 | loss=0.0025 | Q=4.423
Paso 740,000/2,000,000 | episodio=103 | epsilon=0.100 | loss=0.0148 | Q=4.960
Paso 741,000/2,000,000 | episodio=108 | epsilon=0.100 | loss=0.0075 | Q=4.648
Paso 742,000/2,000,000 | episodio=110 | epsilon=0.100 | loss=0.0136 | Q=4.916
Paso 743,000/2,000,000 | episodio=112 | epsilon=0.100 | loss=0.0097 | Q=4.592
Paso 744,000/2,000,000 | episodio=115 | epsilon=0.100 | loss=0.0108 | Q=4.871
Paso 745,000/2,000,000 | episodio=118 | epsilon=0.100 | loss=0.0090 | Q=4.786
Paso 746,000/2,000,000 | episodio=120 | epsilon=0.100 | loss=0.0087 | Q=4.312
Paso 747,000/2,000,000 | episodio=122 | epsilon=0.100 | loss=0.0137 | Q=4.032
Paso 748,000/2,000,000 | episodio=126 | epsilon=0.100 | loss=0.0050 | Q=4.473
Paso 749,000/2,000,000 | episodio=128 | epsilon=0.100 | loss=0.0091 | Q=4.570
Paso 750,000/2,000,000 | episodio=131 | epsilon=0.100 | loss=0.0080 | Q=4.639

EVALUACIÓN | paso=750,000 | promedio=403.00 | mediana=425.00 | máximo=455.00

Paso 751,000/2,000,000 | episodio=134 | epsilon=0.100 | loss=0.0361 | Q=4.456
Paso 752,000/2,000,000 | episodio=136 | epsilon=0.100 | loss=0.0222 | Q=4.284
Paso 753,000/2,000,000 | episodio=140 | epsilon=0.100 | loss=0.0203 | Q=4.566
Paso 754,000/2,000,000 | episodio=144 | epsilon=0.100 | loss=0.0301 | Q=4.609
Paso 755,000/2,000,000 | episodio=146 | epsilon=0.100 | loss=0.0131 | Q=4.735
Paso 756,000/2,000,000 | episodio=148 | epsilon=0.100 | loss=0.0208 | Q=4.848
Paso 757,000/2,000,000 | episodio=151 | epsilon=0.100 | loss=0.0101 | Q=4.719
Paso 758,000/2,000,000 | episodio=154 | epsilon=0.100 | loss=0.0126 | Q=4.975
Paso 759,000/2,000,000 | episodio=156 | epsilon=0.100 | loss=0.0107 | Q=4.960
Paso 760,000/2,000,000 | episodio=159 | epsilon=0.100 | loss=0.0124 | Q=4.987
Paso 761,000/2,000,000 | episodio=161 | epsilon=0.100 | loss=0.0139 | Q=5.084
Paso 762,000/2,000,000 | episodio=163 | epsilon=0.100 | loss=0.0075 | Q=4.968
Paso 763,000/2,000,000 | episodio=165 | epsilon=0.100 | loss=0.0119 | Q=4.921
Paso 764,000/2,000,000 | episodio=167 | epsilon=0.100 | loss=0.0106 | Q=4.865
Paso 765,000/2,000,000 | episodio=169 | epsilon=0.100 | loss=0.0070 | Q=4.650
Paso 766,000/2,000,000 | episodio=173 | epsilon=0.100 | loss=0.0042 | Q=4.388
Paso 767,000/2,000,000 | episodio=176 | epsilon=0.100 | loss=0.0140 | Q=4.377
Paso 768,000/2,000,000 | episodio=178 | epsilon=0.100 | loss=0.0152 | Q=4.892
Paso 769,000/2,000,000 | episodio=180 | epsilon=0.100 | loss=0.0091 | Q=4.406
Paso 770,000/2,000,000 | episodio=181 | epsilon=0.100 | loss=0.0092 | Q=5.101
Paso 771,000/2,000,000 | episodio=183 | epsilon=0.100 | loss=0.0093 | Q=4.913
Paso 772,000/2,000,000 | episodio=186 | epsilon=0.100 | loss=0.0066 | Q=4.574
Paso 773,000/2,000,000 | episodio=188 | epsilon=0.100 | loss=0.0077 | Q=4.924
Paso 774,000/2,000,000 | episodio=190 | epsilon=0.100 | loss=0.0111 | Q=5.010
Paso 775,000/2,000,000 | episodio=192 | epsilon=0.100 | loss=0.0054 | Q=4.383
Paso 776,000/2,000,000 | episodio=194 | epsilon=0.100 | loss=0.0067 | Q=4.178
Paso 777,000/2,000,000 | episodio=196 | epsilon=0.100 | loss=0.0136 | Q=4.846
Paso 778,000/2,000,000 | episodio=198 | epsilon=0.100 | loss=0.0106 | Q=4.500
Paso 779,000/2,000,000 | episodio=201 | epsilon=0.100 | loss=0.0118 | Q=5.124
Paso 780,000/2,000,000 | episodio=203 | epsilon=0.100 | loss=0.0105 | Q=4.266
Paso 781,000/2,000,000 | episodio=205 | epsilon=0.100 | loss=0.0155 | Q=4.650
Paso 782,000/2,000,000 | episodio=208 | epsilon=0.100 | loss=0.0032 | Q=4.490
Paso 783,000/2,000,000 | episodio=211 | epsilon=0.100 | loss=0.0086 | Q=4.643
Paso 784,000/2,000,000 | episodio=214 | epsilon=0.100 | loss=0.0092 | Q=4.997
Paso 785,000/2,000,000 | episodio=216 | epsilon=0.100 | loss=0.0063 | Q=4.763
Paso 786,000/2,000,000 | episodio=218 | epsilon=0.100 | loss=0.0158 | Q=4.740
Paso 787,000/2,000,000 | episodio=221 | epsilon=0.100 | loss=0.0068 | Q=4.496
Paso 788,000/2,000,000 | episodio=223 | epsilon=0.100 | loss=0.0022 | Q=4.545
Paso 789,000/2,000,000 | episodio=225 | epsilon=0.100 | loss=0.0070 | Q=4.628
Paso 790,000/2,000,000 | episodio=227 | epsilon=0.100 | loss=0.0050 | Q=4.463
Paso 791,000/2,000,000 | episodio=230 | epsilon=0.100 | loss=0.0055 | Q=4.703
Paso 792,000/2,000,000 | episodio=232 | epsilon=0.100 | loss=0.0065 | Q=4.915
Paso 793,000/2,000,000 | episodio=235 | epsilon=0.100 | loss=0.0056 | Q=5.081
Paso 794,000/2,000,000 | episodio=239 | epsilon=0.100 | loss=0.0068 | Q=5.201
Paso 795,000/2,000,000 | episodio=241 | epsilon=0.100 | loss=0.0101 | Q=5.346
Paso 796,000/2,000,000 | episodio=244 | epsilon=0.100 | loss=0.0110 | Q=4.737
Paso 797,000/2,000,000 | episodio=246 | epsilon=0.100 | loss=0.0062 | Q=5.031
Paso 798,000/2,000,000 | episodio=249 | epsilon=0.100 | loss=0.0086 | Q=5.175
Paso 799,000/2,000,000 | episodio=251 | epsilon=0.100 | loss=0.0032 | Q=4.997
Paso 800,000/2,000,000 | episodio=254 | epsilon=0.100 | loss=0.0203 | Q=4.746

EVALUACIÓN | paso=800,000 | promedio=366.00 | mediana=380.00 | máximo=435.00

Paso 801,000/2,000,000 | episodio=256 | epsilon=0.100 | loss=0.0144 | Q=4.905
Paso 802,000/2,000,000 | episodio=260 | epsilon=0.100 | loss=0.0081 | Q=4.932
Paso 803,000/2,000,000 | episodio=264 | epsilon=0.100 | loss=0.0160 | Q=4.614
Paso 804,000/2,000,000 | episodio=266 | epsilon=0.100 | loss=0.0145 | Q=4.774
Paso 805,000/2,000,000 | episodio=268 | epsilon=0.100 | loss=0.0174 | Q=4.837
Paso 806,000/2,000,000 | episodio=270 | epsilon=0.100 | loss=0.0021 | Q=5.163
Paso 807,000/2,000,000 | episodio=274 | epsilon=0.100 | loss=0.0062 | Q=5.058
Paso 808,000/2,000,000 | episodio=276 | epsilon=0.100 | loss=0.0070 | Q=5.225
Paso 809,000/2,000,000 | episodio=278 | epsilon=0.100 | loss=0.0065 | Q=4.730
Paso 810,000/2,000,000 | episodio=281 | epsilon=0.100 | loss=0.0058 | Q=5.377
Paso 811,000/2,000,000 | episodio=283 | epsilon=0.100 | loss=0.0092 | Q=5.013
Paso 812,000/2,000,000 | episodio=286 | epsilon=0.100 | loss=0.0074 | Q=4.982
Paso 813,000/2,000,000 | episodio=289 | epsilon=0.100 | loss=0.0091 | Q=5.078
Paso 814,000/2,000,000 | episodio=292 | epsilon=0.100 | loss=0.0075 | Q=5.636
Paso 815,000/2,000,000 | episodio=294 | epsilon=0.100 | loss=0.0171 | Q=4.837
Paso 816,000/2,000,000 | episodio=297 | epsilon=0.100 | loss=0.0102 | Q=5.215
Paso 817,000/2,000,000 | episodio=300 | epsilon=0.100 | loss=0.0071 | Q=5.511
Paso 818,000/2,000,000 | episodio=302 | epsilon=0.100 | loss=0.0060 | Q=5.350
Paso 819,000/2,000,000 | episodio=304 | epsilon=0.100 | loss=0.0134 | Q=4.816
Paso 820,000/2,000,000 | episodio=307 | epsilon=0.100 | loss=0.0083 | Q=5.062
Paso 821,000/2,000,000 | episodio=309 | epsilon=0.100 | loss=0.0135 | Q=5.374
Paso 822,000/2,000,000 | episodio=311 | epsilon=0.100 | loss=0.0144 | Q=4.816
Paso 823,000/2,000,000 | episodio=313 | epsilon=0.100 | loss=0.0096 | Q=4.530
Paso 824,000/2,000,000 | episodio=316 | epsilon=0.100 | loss=0.0185 | Q=5.026
Paso 825,000/2,000,000 | episodio=319 | epsilon=0.100 | loss=0.0037 | Q=5.276
Paso 826,000/2,000,000 | episodio=321 | epsilon=0.100 | loss=0.0069 | Q=5.033
Paso 827,000/2,000,000 | episodio=324 | epsilon=0.100 | loss=0.0084 | Q=4.925
Paso 828,000/2,000,000 | episodio=325 | epsilon=0.100 | loss=0.0090 | Q=5.032
Paso 829,000/2,000,000 | episodio=329 | epsilon=0.100 | loss=0.0193 | Q=4.757
Paso 830,000/2,000,000 | episodio=331 | epsilon=0.100 | loss=0.0015 | Q=4.984
Paso 831,000/2,000,000 | episodio=334 | epsilon=0.100 | loss=0.0274 | Q=4.535
Paso 832,000/2,000,000 | episodio=336 | epsilon=0.100 | loss=0.0118 | Q=4.937
Paso 833,000/2,000,000 | episodio=339 | epsilon=0.100 | loss=0.0163 | Q=4.875
Paso 834,000/2,000,000 | episodio=343 | epsilon=0.100 | loss=0.0034 | Q=5.348
Paso 835,000/2,000,000 | episodio=344 | epsilon=0.100 | loss=0.0132 | Q=5.130
Paso 836,000/2,000,000 | episodio=346 | epsilon=0.100 | loss=0.0051 | Q=4.911
Paso 837,000/2,000,000 | episodio=349 | epsilon=0.100 | loss=0.0119 | Q=4.738
Paso 838,000/2,000,000 | episodio=351 | epsilon=0.100 | loss=0.0168 | Q=4.745
Paso 839,000/2,000,000 | episodio=353 | epsilon=0.100 | loss=0.0173 | Q=4.494
Paso 840,000/2,000,000 | episodio=357 | epsilon=0.100 | loss=0.0068 | Q=4.876
Paso 841,000/2,000,000 | episodio=360 | epsilon=0.100 | loss=0.0094 | Q=4.674
Paso 842,000/2,000,000 | episodio=362 | epsilon=0.100 | loss=0.0148 | Q=4.809
Paso 843,000/2,000,000 | episodio=364 | epsilon=0.100 | loss=0.0191 | Q=4.625
Paso 844,000/2,000,000 | episodio=366 | epsilon=0.100 | loss=0.0116 | Q=4.770
Paso 845,000/2,000,000 | episodio=369 | epsilon=0.100 | loss=0.0060 | Q=5.057
Paso 846,000/2,000,000 | episodio=372 | epsilon=0.100 | loss=0.0065 | Q=4.773
Paso 847,000/2,000,000 | episodio=373 | epsilon=0.100 | loss=0.0152 | Q=4.823
Paso 848,000/2,000,000 | episodio=376 | epsilon=0.100 | loss=0.0232 | Q=4.696
Paso 849,000/2,000,000 | episodio=380 | epsilon=0.100 | loss=0.0053 | Q=4.625
Paso 850,000/2,000,000 | episodio=382 | epsilon=0.100 | loss=0.0128 | Q=4.953

EVALUACIÓN | paso=850,000 | promedio=433.00 | mediana=395.00 | máximo=645.00

Paso 851,000/2,000,000 | episodio=384 | epsilon=0.100 | loss=0.0147 | Q=5.038
Paso 852,000/2,000,000 | episodio=386 | epsilon=0.100 | loss=0.0156 | Q=4.958
Paso 853,000/2,000,000 | episodio=389 | epsilon=0.100 | loss=0.0089 | Q=5.321
Paso 854,000/2,000,000 | episodio=391 | epsilon=0.100 | loss=0.0042 | Q=4.713
Paso 855,000/2,000,000 | episodio=393 | epsilon=0.100 | loss=0.0043 | Q=4.515
Paso 856,000/2,000,000 | episodio=396 | epsilon=0.100 | loss=0.0204 | Q=4.758
Paso 857,000/2,000,000 | episodio=400 | epsilon=0.100 | loss=0.0275 | Q=4.450
Paso 858,000/2,000,000 | episodio=402 | epsilon=0.100 | loss=0.0143 | Q=4.543
Paso 859,000/2,000,000 | episodio=404 | epsilon=0.100 | loss=0.0167 | Q=4.904
Paso 860,000/2,000,000 | episodio=408 | epsilon=0.100 | loss=0.0040 | Q=5.263
Paso 861,000/2,000,000 | episodio=411 | epsilon=0.100 | loss=0.0103 | Q=5.173
Paso 862,000/2,000,000 | episodio=414 | epsilon=0.100 | loss=0.0182 | Q=4.885
Paso 863,000/2,000,000 | episodio=416 | epsilon=0.100 | loss=0.0150 | Q=4.709
Paso 864,000/2,000,000 | episodio=419 | epsilon=0.100 | loss=0.0096 | Q=4.783
Paso 865,000/2,000,000 | episodio=421 | epsilon=0.100 | loss=0.0027 | Q=4.739
Paso 866,000/2,000,000 | episodio=424 | epsilon=0.100 | loss=0.0077 | Q=5.282
Paso 867,000/2,000,000 | episodio=426 | epsilon=0.100 | loss=0.0067 | Q=5.208
Paso 868,000/2,000,000 | episodio=429 | epsilon=0.100 | loss=0.0075 | Q=4.946
Paso 869,000/2,000,000 | episodio=431 | epsilon=0.100 | loss=0.0088 | Q=5.301
Paso 870,000/2,000,000 | episodio=435 | epsilon=0.100 | loss=0.0114 | Q=4.448
Paso 871,000/2,000,000 | episodio=437 | epsilon=0.100 | loss=0.0096 | Q=5.154
Paso 872,000/2,000,000 | episodio=440 | epsilon=0.100 | loss=0.0128 | Q=4.862
Paso 873,000/2,000,000 | episodio=442 | epsilon=0.100 | loss=0.0175 | Q=5.221
Paso 874,000/2,000,000 | episodio=444 | epsilon=0.100 | loss=0.0072 | Q=5.197
Paso 875,000/2,000,000 | episodio=448 | epsilon=0.100 | loss=0.0192 | Q=4.805
Paso 876,000/2,000,000 | episodio=449 | epsilon=0.100 | loss=0.0118 | Q=4.570
Paso 877,000/2,000,000 | episodio=451 | epsilon=0.100 | loss=0.0283 | Q=4.717
Paso 878,000/2,000,000 | episodio=454 | epsilon=0.100 | loss=0.0076 | Q=4.416
Paso 879,000/2,000,000 | episodio=456 | epsilon=0.100 | loss=0.0103 | Q=5.051
Paso 880,000/2,000,000 | episodio=459 | epsilon=0.100 | loss=0.0095 | Q=4.680
Paso 881,000/2,000,000 | episodio=462 | epsilon=0.100 | loss=0.0157 | Q=4.921
Paso 882,000/2,000,000 | episodio=467 | epsilon=0.100 | loss=0.0159 | Q=4.786
Paso 883,000/2,000,000 | episodio=470 | epsilon=0.100 | loss=0.0122 | Q=4.947
Paso 884,000/2,000,000 | episodio=473 | epsilon=0.100 | loss=0.0056 | Q=4.915
Paso 885,000/2,000,000 | episodio=476 | epsilon=0.100 | loss=0.0096 | Q=4.909
Paso 886,000/2,000,000 | episodio=478 | epsilon=0.100 | loss=0.0068 | Q=5.475
Paso 887,000/2,000,000 | episodio=481 | epsilon=0.100 | loss=0.0130 | Q=5.039
Paso 888,000/2,000,000 | episodio=485 | epsilon=0.100 | loss=0.0041 | Q=5.132
Paso 889,000/2,000,000 | episodio=487 | epsilon=0.100 | loss=0.0113 | Q=4.968
Paso 890,000/2,000,000 | episodio=489 | epsilon=0.100 | loss=0.0055 | Q=5.044
Paso 891,000/2,000,000 | episodio=491 | epsilon=0.100 | loss=0.0111 | Q=5.400
Paso 892,000/2,000,000 | episodio=494 | epsilon=0.100 | loss=0.0076 | Q=4.788
Paso 893,000/2,000,000 | episodio=497 | epsilon=0.100 | loss=0.0029 | Q=4.982
Paso 894,000/2,000,000 | episodio=500 | epsilon=0.100 | loss=0.0082 | Q=5.232
Paso 895,000/2,000,000 | episodio=503 | epsilon=0.100 | loss=0.0106 | Q=5.025
Paso 896,000/2,000,000 | episodio=506 | epsilon=0.100 | loss=0.0114 | Q=5.028
Paso 897,000/2,000,000 | episodio=509 | epsilon=0.100 | loss=0.0082 | Q=5.472
Paso 898,000/2,000,000 | episodio=511 | epsilon=0.100 | loss=0.0185 | Q=4.866
Paso 899,000/2,000,000 | episodio=514 | epsilon=0.100 | loss=0.0047 | Q=4.783
Paso 900,000/2,000,000 | episodio=515 | epsilon=0.100 | loss=0.0240 | Q=4.738

EVALUACIÓN | paso=900,000 | promedio=414.00 | mediana=410.00 | máximo=515.00

Paso 901,000/2,000,000 | episodio=517 | epsilon=0.100 | loss=0.0071 | Q=5.668
Paso 902,000/2,000,000 | episodio=520 | epsilon=0.100 | loss=0.0105 | Q=5.128
Paso 903,000/2,000,000 | episodio=522 | epsilon=0.100 | loss=0.0155 | Q=5.167
Paso 904,000/2,000,000 | episodio=525 | epsilon=0.100 | loss=0.0213 | Q=5.020
Paso 905,000/2,000,000 | episodio=527 | epsilon=0.100 | loss=0.0047 | Q=5.656
Paso 906,000/2,000,000 | episodio=530 | epsilon=0.100 | loss=0.0121 | Q=4.755
Paso 907,000/2,000,000 | episodio=532 | epsilon=0.100 | loss=0.0044 | Q=5.286
Paso 908,000/2,000,000 | episodio=535 | epsilon=0.100 | loss=0.0114 | Q=4.927
Paso 909,000/2,000,000 | episodio=538 | epsilon=0.100 | loss=0.0191 | Q=5.115
Paso 910,000/2,000,000 | episodio=539 | epsilon=0.100 | loss=0.0087 | Q=4.677
Paso 911,000/2,000,000 | episodio=542 | epsilon=0.100 | loss=0.0041 | Q=5.142
Paso 912,000/2,000,000 | episodio=544 | epsilon=0.100 | loss=0.0232 | Q=4.746
Paso 913,000/2,000,000 | episodio=547 | epsilon=0.100 | loss=0.0037 | Q=5.541
Paso 914,000/2,000,000 | episodio=550 | epsilon=0.100 | loss=0.0111 | Q=4.795
Paso 915,000/2,000,000 | episodio=552 | epsilon=0.100 | loss=0.0181 | Q=4.326
Paso 916,000/2,000,000 | episodio=556 | epsilon=0.100 | loss=0.0144 | Q=4.616
Paso 917,000/2,000,000 | episodio=560 | epsilon=0.100 | loss=0.0042 | Q=4.955
Paso 918,000/2,000,000 | episodio=563 | epsilon=0.100 | loss=0.0211 | Q=5.216
Paso 919,000/2,000,000 | episodio=566 | epsilon=0.100 | loss=0.0101 | Q=5.184
Paso 920,000/2,000,000 | episodio=570 | epsilon=0.100 | loss=0.0047 | Q=5.156
Paso 921,000/2,000,000 | episodio=573 | epsilon=0.100 | loss=0.0154 | Q=4.688
Paso 922,000/2,000,000 | episodio=576 | epsilon=0.100 | loss=0.0087 | Q=5.782
Paso 923,000/2,000,000 | episodio=579 | epsilon=0.100 | loss=0.0076 | Q=5.010
Paso 924,000/2,000,000 | episodio=582 | epsilon=0.100 | loss=0.0107 | Q=5.679
Paso 925,000/2,000,000 | episodio=584 | epsilon=0.100 | loss=0.0100 | Q=5.470
Paso 926,000/2,000,000 | episodio=586 | epsilon=0.100 | loss=0.0065 | Q=5.713
Paso 927,000/2,000,000 | episodio=587 | epsilon=0.100 | loss=0.0135 | Q=5.130
Paso 928,000/2,000,000 | episodio=592 | epsilon=0.100 | loss=0.0167 | Q=5.343
Paso 929,000/2,000,000 | episodio=595 | epsilon=0.100 | loss=0.0079 | Q=4.793
Paso 930,000/2,000,000 | episodio=597 | epsilon=0.100 | loss=0.0061 | Q=5.145
Paso 931,000/2,000,000 | episodio=600 | epsilon=0.100 | loss=0.0056 | Q=5.374
Paso 932,000/2,000,000 | episodio=603 | epsilon=0.100 | loss=0.0072 | Q=4.847
Paso 933,000/2,000,000 | episodio=605 | epsilon=0.100 | loss=0.0288 | Q=5.256
Paso 934,000/2,000,000 | episodio=608 | epsilon=0.100 | loss=0.0087 | Q=5.385
Paso 935,000/2,000,000 | episodio=611 | epsilon=0.100 | loss=0.0074 | Q=5.305
Paso 936,000/2,000,000 | episodio=614 | epsilon=0.100 | loss=0.0090 | Q=4.726
Paso 937,000/2,000,000 | episodio=616 | epsilon=0.100 | loss=0.0251 | Q=4.856
Paso 938,000/2,000,000 | episodio=618 | epsilon=0.100 | loss=0.0063 | Q=5.556
Paso 939,000/2,000,000 | episodio=622 | epsilon=0.100 | loss=0.0145 | Q=4.863
Paso 940,000/2,000,000 | episodio=624 | epsilon=0.100 | loss=0.0223 | Q=4.783
Paso 941,000/2,000,000 | episodio=626 | epsilon=0.100 | loss=0.0026 | Q=4.767
Paso 942,000/2,000,000 | episodio=628 | epsilon=0.100 | loss=0.0118 | Q=5.182
Paso 943,000/2,000,000 | episodio=630 | epsilon=0.100 | loss=0.0090 | Q=4.827
Paso 944,000/2,000,000 | episodio=632 | epsilon=0.100 | loss=0.0151 | Q=5.453
Paso 945,000/2,000,000 | episodio=635 | epsilon=0.100 | loss=0.0068 | Q=5.360
Paso 946,000/2,000,000 | episodio=639 | epsilon=0.100 | loss=0.0363 | Q=5.336
Paso 947,000/2,000,000 | episodio=640 | epsilon=0.100 | loss=0.0278 | Q=4.622
Paso 948,000/2,000,000 | episodio=644 | epsilon=0.100 | loss=0.0140 | Q=5.040
Paso 949,000/2,000,000 | episodio=646 | epsilon=0.100 | loss=0.0099 | Q=4.829
Paso 950,000/2,000,000 | episodio=649 | epsilon=0.100 | loss=0.0213 | Q=4.405

EVALUACIÓN | paso=950,000 | promedio=501.00 | mediana=495.00 | máximo=650.00

Paso 951,000/2,000,000 | episodio=651 | epsilon=0.100 | loss=0.0213 | Q=5.453
Paso 952,000/2,000,000 | episodio=654 | epsilon=0.100 | loss=0.0242 | Q=4.679
Paso 953,000/2,000,000 | episodio=657 | epsilon=0.100 | loss=0.0019 | Q=4.985
Paso 954,000/2,000,000 | episodio=660 | epsilon=0.100 | loss=0.0033 | Q=5.533
Paso 955,000/2,000,000 | episodio=664 | epsilon=0.100 | loss=0.0104 | Q=5.116
Paso 956,000/2,000,000 | episodio=667 | epsilon=0.100 | loss=0.0061 | Q=5.464

In [23]:
from pathlib import Path
import pandas as pd
from IPython.display import display


RUTA_LOG_V6_EXTENDIDO = Path(
    "../logs/entrenamientos/"
    "v6_dqn_per_3step_extendido/"
    "evaluaciones.csv"
)

RUTA_MEJOR_MODELO_V6_EXTENDIDO = Path(
    "../models/"
    "v6_dqn_per_3step_extendido/"
    "mejor_modelo.pt"
)

df_evaluaciones_v6_extendido = pd.read_csv(
    RUTA_LOG_V6_EXTENDIDO
)

display(df_evaluaciones_v6_extendido)

mejor_fila_v6_extendido = (
    df_evaluaciones_v6_extendido.loc[
        df_evaluaciones_v6_extendido["promedio"].idxmax()
    ]
)

promedio_ultimas_tres_v6_extendido = (
    df_evaluaciones_v6_extendido["promedio"]
    .tail(3)
    .mean()
)

print("\nMEJOR EVALUACIÓN DE V6 EXTENDIDO")
print(
    f"Paso: "
    f"{int(mejor_fila_v6_extendido['paso_global']):,}"
)
print(
    f"Promedio: "
    f"{mejor_fila_v6_extendido['promedio']:.2f}"
)
print(
    f"Mediana: "
    f"{mejor_fila_v6_extendido['mediana']:.2f}"
)
print(
    f"Desviación: "
    f"{mejor_fila_v6_extendido['desviacion']:.2f}"
)
print(
    f"Mínimo: "
    f"{mejor_fila_v6_extendido['minimo']:.2f}"
)
print(
    f"Máximo: "
    f"{mejor_fila_v6_extendido['maximo']:.2f}"
)

print(
    "\nPromedio de las últimas tres evaluaciones: "
    f"{promedio_ultimas_tres_v6_extendido:.2f}"
)

print(
    "\nCheckpoint disponible:",
    (
        "OK"
        if RUTA_MEJOR_MODELO_V6_EXTENDIDO.exists()
        else "NO ENCONTRADO"
    ),
)

    paso_global  promedio  mediana  desviacion  minimo  maximo
0        750000     403.0    425.0   55.641711   295.0   455.0
1        800000     366.0    380.0   59.782941   270.0   435.0
2        850000     433.0    395.0  111.651243   315.0   645.0
3        900000     414.0    410.0   58.000000   335.0   515.0
4        950000     501.0    495.0   83.390647   420.0   650.0
5       1000000     454.0    440.0   47.895720   405.0   545.0
6       1050000     418.0    475.0  127.734099   185.0   555.0
7       1100000     408.0    390.0  112.986725   250.0   545.0
8       1150000     386.0    370.0   96.405394   265.0   545.0
9       1200000     434.0    515.0  129.938447   210.0   555.0
10      1250000     509.0    515.0  209.508950   155.0   800.0
11      1300000     439.0    455.0   80.833162   305.0   535.0
12      1350000     488.0    475.0  104.048066   360.0   670.0
13      1400000     393.0    370.0   77.239886   305.0   515.0
14      1450000     380.0    310.0  189.868375   215.0   750.0
15      1500000     383.0    350.0  117.243337   255.0   605.0
16      1550000     487.0    465.0  149.886624   275.0   730.0
17      1600000     387.0    380.0   53.814496   305.0   470.0
18      1650000     451.0    500.0  157.905035   185.0   635.0
19      1700000     252.0    260.0   39.319207   180.0   300.0
20      1750000     468.0    545.0  120.066648   315.0   595.0
21      1800000     426.0    415.0   64.218377   355.0   525.0
22      1850000     397.0    365.0   70.753092   300.0   495.0
23      1900000     498.0    510.0   31.874755   440.0   530.0
24      1950000     398.0    340.0  103.566404   300.0   545.0
25      2000000     514.0    480.0   80.894994   440.0   650.0

MEJOR EVALUACIÓN DE V6 EXTENDIDO
Paso: 2,000,000
Promedio: 514.00
Mediana: 480.00
Desviación: 80.89
Mínimo: 440.00
Máximo: 650.00

Promedio de las últimas tres evaluaciones: 470.00

Checkpoint disponible: OK

In [24]:
import gc
from pathlib import Path

import torch

from models import DQN


RUTA_MEJOR_V6_EXTENDIDO = Path(
    "../models/"
    "v6_dqn_per_3step_extendido/"
    "mejor_modelo.pt"
)

checkpoint_v6_extendido = torch.load(
    RUTA_MEJOR_V6_EXTENDIDO,
    map_location=device,
    weights_only=True,
)

mejor_v6_extendido = DQN(
    n_acciones=6
).to(device)

mejor_v6_extendido.load_state_dict(
    checkpoint_v6_extendido["modelo_online_state_dict"]
)

mejor_v6_extendido.eval()

print(
    "Checkpoint cargado desde el paso:",
    f"{checkpoint_v6_extendido['paso']:,}",
)

Checkpoint cargado desde el paso: 2,000,000

In [25]:
N_EPISODIOS_EVALUACION = 30
SEMILLA_BASE_EVALUACION = 42

print(
    "\nEvaluando V6 extendido durante "
    f"{N_EPISODIOS_EVALUACION} episodios...\n"
)

resultados_v6_extendido, resumen_v6_extendido = evaluar_modelo(
    modelo=mejor_v6_extendido,
    config=config_v6_extendido,
    device=device,
    n_episodios=N_EPISODIOS_EVALUACION,
    seed_base=SEMILLA_BASE_EVALUACION,
)

df_v6_extendido = pd.DataFrame(
    resultados_v6_extendido
)

df_v6_extendido["agente"] = (
    "DQN + PER a=0.6 + 3-step extendido"
)

df_v6_extendido = df_v6_extendido[
    [
        "agente",
        "episodio",
        "seed",
        "recompensa_total",
        "pasos",
        "terminated",
        "truncated",
    ]
]

print("RESUMEN DE 30 EPISODIOS")

for metrica, valor in resumen_v6_extendido.items():
    print(f"{metrica}: {valor:.2f}")

display(df_v6_extendido.head(10))

Evaluando V6 extendido durante 30 episodios...

RESUMEN DE 30 EPISODIOS
promedio: 509.17
mediana: 497.50
desviacion: 113.39
minimo: 360.00
maximo: 910.00

,agente,episodio,seed,recompensa_total,pasos,terminated,truncated
0,DQN + PER a=0.6 + 3-step extendido,0,42,470.0,708,True,False
1,DQN + PER a=0.6 + 3-step extendido,1,43,360.0,598,True,False
2,DQN + PER a=0.6 + 3-step extendido,2,44,555.0,981,True,False
3,DQN + PER a=0.6 + 3-step extendido,3,45,615.0,803,True,False
4,DQN + PER a=0.6 + 3-step extendido,4,46,555.0,1134,True,False
5,DQN + PER a=0.6 + 3-step extendido,5,47,580.0,631,True,False
6,DQN + PER a=0.6 + 3-step extendido,6,48,385.0,732,True,False
7,DQN + PER a=0.6 + 3-step extendido,7,49,605.0,718,True,False
8,DQN + PER a=0.6 + 3-step extendido,8,50,460.0,613,True,False
9,DQN + PER a=0.6 + 3-step extendido,9,51,400.0,785,True,False

In [26]:
import gc
from dataclasses import replace
from pathlib import Path

import torch

from train import entrenar_dqn
from models import DQN


RUTA_CHECKPOINT_V6_2M = Path(
    "../models/"
    "v6_dqn_per_3step_extendido/"
    "mejor_modelo.pt"
)

if not RUTA_CHECKPOINT_V6_2M.exists():
    raise FileNotFoundError(
        f"No se encontró: {RUTA_CHECKPOINT_V6_2M}"
    )

config_v6_3m = replace(
    config_v6_extendido,
    nombre_experimento="v6_dqn_per_3step_3m",
    total_pasos=3_000_000,
)

objetos_temporales = [
    "mejor_v6_extendido",
    "checkpoint_v6_extendido",
    "resultado_v6_extendido",
]

for nombre in objetos_temporales:
    globals().pop(nombre, None)

gc.collect()

if device.type == "mps":
    torch.mps.empty_cache()

print("Checkpoint inicial:", RUTA_CHECKPOINT_V6_2M)
print("Continuación desde 2,000,000 hasta 3,000,000 pasos")
print("Modelo actual de 2M preservado en su carpeta original")

resultado_v6_3m = entrenar_dqn(
    config=config_v6_3m,
    clase_modelo=DQN,
    device=device,
    usar_double_dqn=False,
    ruta_checkpoint_inicial=RUTA_CHECKPOINT_V6_2M,
)

print("\nENTRENAMIENTO HASTA 3M FINALIZADO")
print(
    "Mejor promedio durante esta extensión: "
    f"{resultado_v6_3m['mejor_promedio_evaluacion']:.2f}"
)

Checkpoint inicial: ../models/v6_dqn_per_3step_extendido/mejor_modelo.pt
Continuación desde 2,000,000 hasta 3,000,000 pasos
Modelo actual de 2M preservado en su carpeta original
Reanudando entrenamiento desde el paso 2,000,000 (checkpoint: ../models/v6_dqn_per_3step_extendido/mejor_modelo.pt)
Replay buffer: priorizado | alpha=0.6 | beta inicial=0.4
Retorno utilizado: 3-step
Paso 2,010,000/3,000,000 | episodio=22 | epsilon=0.100 | loss=0.0383 | Q=5.368
Paso 2,011,000/3,000,000 | episodio=25 | epsilon=0.100 | loss=0.0444 | Q=5.422
Paso 2,012,000/3,000,000 | episodio=27 | epsilon=0.100 | loss=0.0096 | Q=5.946
Paso 2,013,000/3,000,000 | episodio=30 | epsilon=0.100 | loss=0.0182 | Q=5.690
Paso 2,014,000/3,000,000 | episodio=31 | epsilon=0.100 | loss=0.0111 | Q=5.254
Paso 2,015,000/3,000,000 | episodio=34 | epsilon=0.100 | loss=0.0024 | Q=5.801
Paso 2,016,000/3,000,000 | episodio=36 | epsilon=0.100 | loss=0.0051 | Q=5.841
Paso 2,017,000/3,000,000 | episodio=39 | epsilon=0.100 | loss=0.0192 | Q=5.320
Paso 2,018,000/3,000,000 | episodio=42 | epsilon=0.100 | loss=0.0083 | Q=5.864
Paso 2,019,000/3,000,000 | episodio=44 | epsilon=0.100 | loss=0.0183 | Q=5.581
Paso 2,020,000/3,000,000 | episodio=46 | epsilon=0.100 | loss=0.0164 | Q=5.607
Paso 2,021,000/3,000,000 | episodio=49 | epsilon=0.100 | loss=0.0162 | Q=5.673
Paso 2,022,000/3,000,000 | episodio=52 | epsilon=0.100 | loss=0.0135 | Q=4.993
Paso 2,023,000/3,000,000 | episodio=54 | epsilon=0.100 | loss=0.0089 | Q=5.508
Paso 2,024,000/3,000,000 | episodio=56 | epsilon=0.100 | loss=0.0056 | Q=5.637
Paso 2,025,000/3,000,000 | episodio=59 | epsilon=0.100 | loss=0.0134 | Q=6.004
Paso 2,026,000/3,000,000 | episodio=62 | epsilon=0.100 | loss=0.0060 | Q=5.090
Paso 2,027,000/3,000,000 | episodio=64 | epsilon=0.100 | loss=0.0053 | Q=6.079
Paso 2,028,000/3,000,000 | episodio=67 | epsilon=0.100 | loss=0.0133 | Q=5.845
Paso 2,029,000/3,000,000 | episodio=69 | epsilon=0.100 | loss=0.0185 | Q=5.907
Paso 2,030,000/3,000,000 | episodio=72 | epsilon=0.100 | loss=0.0018 | Q=6.055
Paso 2,031,000/3,000,000 | episodio=74 | epsilon=0.100 | loss=0.0077 | Q=5.707
Paso 2,032,000/3,000,000 | episodio=76 | epsilon=0.100 | loss=0.0088 | Q=5.394
Paso 2,033,000/3,000,000 | episodio=79 | epsilon=0.100 | loss=0.0023 | Q=6.075
Paso 2,034,000/3,000,000 | episodio=82 | epsilon=0.100 | loss=0.0104 | Q=5.690
Paso 2,035,000/3,000,000 | episodio=85 | epsilon=0.100 | loss=0.0072 | Q=5.377
Paso 2,036,000/3,000,000 | episodio=88 | epsilon=0.100 | loss=0.0108 | Q=5.786
Paso 2,037,000/3,000,000 | episodio=90 | epsilon=0.100 | loss=0.0123 | Q=4.934
Paso 2,038,000/3,000,000 | episodio=92 | epsilon=0.100 | loss=0.0101 | Q=6.053
Paso 2,039,000/3,000,000 | episodio=94 | epsilon=0.100 | loss=0.0130 | Q=5.452
Paso 2,040,000/3,000,000 | episodio=97 | epsilon=0.100 | loss=0.0065 | Q=6.022
Paso 2,041,000/3,000,000 | episodio=98 | epsilon=0.100 | loss=0.0051 | Q=5.653
Paso 2,042,000/3,000,000 | episodio=101 | epsilon=0.100 | loss=0.0229 | Q=5.792
Paso 2,043,000/3,000,000 | episodio=103 | epsilon=0.100 | loss=0.0058 | Q=5.495
Paso 2,044,000/3,000,000 | episodio=105 | epsilon=0.100 | loss=0.0038 | Q=5.475
Paso 2,045,000/3,000,000 | episodio=109 | epsilon=0.100 | loss=0.0109 | Q=5.341
Paso 2,046,000/3,000,000 | episodio=112 | epsilon=0.100 | loss=0.0508 | Q=5.456
Paso 2,047,000/3,000,000 | episodio=114 | epsilon=0.100 | loss=0.0061 | Q=5.990
Paso 2,048,000/3,000,000 | episodio=115 | epsilon=0.100 | loss=0.0101 | Q=5.519
Paso 2,049,000/3,000,000 | episodio=117 | epsilon=0.100 | loss=0.0025 | Q=5.551
Paso 2,050,000/3,000,000 | episodio=120 | epsilon=0.100 | loss=0.0064 | Q=5.873

EVALUACIÓN | paso=2,050,000 | promedio=571.00 | mediana=650.00 | máximo=690.00

Paso 2,051,000/3,000,000 | episodio=123 | epsilon=0.100 | loss=0.0042 | Q=5.542
Paso 2,052,000/3,000,000 | episodio=125 | epsilon=0.100 | loss=0.0078 | Q=5.577
Paso 2,053,000/3,000,000 | episodio=128 | epsilon=0.100 | loss=0.0030 | Q=5.105
Paso 2,054,000/3,000,000 | episodio=131 | epsilon=0.100 | loss=0.0041 | Q=5.569
Paso 2,055,000/3,000,000 | episodio=133 | epsilon=0.100 | loss=0.0055 | Q=5.728
Paso 2,056,000/3,000,000 | episodio=135 | epsilon=0.100 | loss=0.0222 | Q=5.360
Paso 2,057,000/3,000,000 | episodio=137 | epsilon=0.100 | loss=0.0071 | Q=5.808
Paso 2,058,000/3,000,000 | episodio=140 | epsilon=0.100 | loss=0.0030 | Q=5.177
Paso 2,059,000/3,000,000 | episodio=144 | epsilon=0.100 | loss=0.0060 | Q=5.129
Paso 2,060,000/3,000,000 | episodio=146 | epsilon=0.100 | loss=0.0031 | Q=5.656
Paso 2,061,000/3,000,000 | episodio=148 | epsilon=0.100 | loss=0.0077 | Q=5.884
Paso 2,062,000/3,000,000 | episodio=150 | epsilon=0.100 | loss=0.0050 | Q=5.774
Paso 2,063,000/3,000,000 | episodio=152 | epsilon=0.100 | loss=0.0072 | Q=5.515
Paso 2,064,000/3,000,000 | episodio=154 | epsilon=0.100 | loss=0.0103 | Q=5.347
Paso 2,065,000/3,000,000 | episodio=158 | epsilon=0.100 | loss=0.0048 | Q=5.539
Paso 2,066,000/3,000,000 | episodio=160 | epsilon=0.100 | loss=0.0063 | Q=5.320
Paso 2,067,000/3,000,000 | episodio=163 | epsilon=0.100 | loss=0.0137 | Q=5.534
Paso 2,068,000/3,000,000 | episodio=166 | epsilon=0.100 | loss=0.0125 | Q=5.462
Paso 2,069,000/3,000,000 | episodio=168 | epsilon=0.100 | loss=0.0066 | Q=5.688
Paso 2,070,000/3,000,000 | episodio=170 | epsilon=0.100 | loss=0.0059 | Q=5.737
Paso 2,071,000/3,000,000 | episodio=173 | epsilon=0.100 | loss=0.0121 | Q=5.621
Paso 2,072,000/3,000,000 | episodio=176 | epsilon=0.100 | loss=0.0062 | Q=5.261
Paso 2,073,000/3,000,000 | episodio=178 | epsilon=0.100 | loss=0.0179 | Q=5.308
Paso 2,074,000/3,000,000 | episodio=181 | epsilon=0.100 | loss=0.0074 | Q=5.917
Paso 2,075,000/3,000,000 | episodio=184 | epsilon=0.100 | loss=0.0172 | Q=5.750
Paso 2,076,000/3,000,000 | episodio=186 | epsilon=0.100 | loss=0.0101 | Q=5.565
Paso 2,077,000/3,000,000 | episodio=188 | epsilon=0.100 | loss=0.0078 | Q=5.914
Paso 2,078,000/3,000,000 | episodio=191 | epsilon=0.100 | loss=0.0064 | Q=5.743
Paso 2,079,000/3,000,000 | episodio=193 | epsilon=0.100 | loss=0.0006 | Q=5.343
Paso 2,080,000/3,000,000 | episodio=195 | epsilon=0.100 | loss=0.0150 | Q=4.855
Paso 2,081,000/3,000,000 | episodio=198 | epsilon=0.100 | loss=0.0087 | Q=5.036
Paso 2,082,000/3,000,000 | episodio=200 | epsilon=0.100 | loss=0.0014 | Q=5.597
Paso 2,083,000/3,000,000 | episodio=202 | epsilon=0.100 | loss=0.0054 | Q=5.656
Paso 2,084,000/3,000,000 | episodio=205 | epsilon=0.100 | loss=0.0057 | Q=5.617
Paso 2,085,000/3,000,000 | episodio=209 | epsilon=0.100 | loss=0.0167 | Q=5.083
Paso 2,086,000/3,000,000 | episodio=212 | epsilon=0.100 | loss=0.0042 | Q=5.758
Paso 2,087,000/3,000,000 | episodio=215 | epsilon=0.100 | loss=0.0148 | Q=5.397
Paso 2,088,000/3,000,000 | episodio=216 | epsilon=0.100 | loss=0.0102 | Q=5.379
Paso 2,089,000/3,000,000 | episodio=218 | epsilon=0.100 | loss=0.0067 | Q=5.773
Paso 2,090,000/3,000,000 | episodio=222 | epsilon=0.100 | loss=0.0150 | Q=5.534
Paso 2,091,000/3,000,000 | episodio=223 | epsilon=0.100 | loss=0.0062 | Q=5.252
Paso 2,092,000/3,000,000 | episodio=226 | epsilon=0.100 | loss=0.0109 | Q=5.636
Paso 2,093,000/3,000,000 | episodio=229 | epsilon=0.100 | loss=0.0177 | Q=5.712
Paso 2,094,000/3,000,000 | episodio=231 | epsilon=0.100 | loss=0.0064 | Q=5.336
Paso 2,095,000/3,000,000 | episodio=233 | epsilon=0.100 | loss=0.0041 | Q=5.668
Paso 2,096,000/3,000,000 | episodio=235 | epsilon=0.100 | loss=0.0073 | Q=5.520
Paso 2,097,000/3,000,000 | episodio=239 | epsilon=0.100 | loss=0.0134 | Q=4.825
Paso 2,098,000/3,000,000 | episodio=240 | epsilon=0.100 | loss=0.0024 | Q=5.112
Paso 2,099,000/3,000,000 | episodio=243 | epsilon=0.100 | loss=0.0071 | Q=5.402
Paso 2,100,000/3,000,000 | episodio=245 | epsilon=0.100 | loss=0.0338 | Q=5.231

EVALUACIÓN | paso=2,100,000 | promedio=424.00 | mediana=410.00 | máximo=525.00

Paso 2,101,000/3,000,000 | episodio=248 | epsilon=0.100 | loss=0.0121 | Q=5.267
Paso 2,102,000/3,000,000 | episodio=250 | epsilon=0.100 | loss=0.0017 | Q=5.666
Paso 2,103,000/3,000,000 | episodio=253 | epsilon=0.100 | loss=0.0076 | Q=5.914
Paso 2,104,000/3,000,000 | episodio=256 | epsilon=0.100 | loss=0.0048 | Q=5.022
Paso 2,105,000/3,000,000 | episodio=259 | epsilon=0.100 | loss=0.0146 | Q=5.863
Paso 2,106,000/3,000,000 | episodio=261 | epsilon=0.100 | loss=0.0145 | Q=4.908
Paso 2,107,000/3,000,000 | episodio=263 | epsilon=0.100 | loss=0.0035 | Q=5.012
Paso 2,108,000/3,000,000 | episodio=266 | epsilon=0.100 | loss=0.0122 | Q=4.991
Paso 2,109,000/3,000,000 | episodio=267 | epsilon=0.100 | loss=0.0125 | Q=5.360
Paso 2,110,000/3,000,000 | episodio=269 | epsilon=0.100 | loss=0.0034 | Q=5.112
Paso 2,111,000/3,000,000 | episodio=271 | epsilon=0.100 | loss=0.0194 | Q=4.679
Paso 2,112,000/3,000,000 | episodio=274 | epsilon=0.100 | loss=0.0310 | Q=5.347
Paso 2,113,000/3,000,000 | episodio=275 | epsilon=0.100 | loss=0.0145 | Q=4.779
Paso 2,114,000/3,000,000 | episodio=277 | epsilon=0.100 | loss=0.0019 | Q=5.401
Paso 2,115,000/3,000,000 | episodio=280 | epsilon=0.100 | loss=0.0064 | Q=5.987
Paso 2,116,000/3,000,000 | episodio=282 | epsilon=0.100 | loss=0.0082 | Q=5.293
Paso 2,117,000/3,000,000 | episodio=285 | epsilon=0.100 | loss=0.0152 | Q=5.344
Paso 2,118,000/3,000,000 | episodio=287 | epsilon=0.100 | loss=0.0082 | Q=5.514
Paso 2,119,000/3,000,000 | episodio=290 | epsilon=0.100 | loss=0.0033 | Q=5.388
Paso 2,120,000/3,000,000 | episodio=292 | epsilon=0.100 | loss=0.0162 | Q=5.478
Paso 2,121,000/3,000,000 | episodio=295 | epsilon=0.100 | loss=0.0123 | Q=5.094
Paso 2,122,000/3,000,000 | episodio=297 | epsilon=0.100 | loss=0.0100 | Q=5.370
Paso 2,123,000/3,000,000 | episodio=300 | epsilon=0.100 | loss=0.0084 | Q=5.950
Paso 2,124,000/3,000,000 | episodio=303 | epsilon=0.100 | loss=0.0080 | Q=5.505
Paso 2,125,000/3,000,000 | episodio=305 | epsilon=0.100 | loss=0.0082 | Q=5.410
Paso 2,126,000/3,000,000 | episodio=307 | epsilon=0.100 | loss=0.0057 | Q=5.878
Paso 2,127,000/3,000,000 | episodio=310 | epsilon=0.100 | loss=0.0050 | Q=5.651
Paso 2,128,000/3,000,000 | episodio=313 | epsilon=0.100 | loss=0.0061 | Q=5.412
Paso 2,129,000/3,000,000 | episodio=316 | epsilon=0.100 | loss=0.0130 | Q=4.774
Paso 2,130,000/3,000,000 | episodio=318 | epsilon=0.100 | loss=0.0036 | Q=5.397
Paso 2,131,000/3,000,000 | episodio=320 | epsilon=0.100 | loss=0.0168 | Q=5.766
Paso 2,132,000/3,000,000 | episodio=323 | epsilon=0.100 | loss=0.0063 | Q=6.506
Paso 2,133,000/3,000,000 | episodio=325 | epsilon=0.100 | loss=0.0054 | Q=5.955
Paso 2,134,000/3,000,000 | episodio=327 | epsilon=0.100 | loss=0.0274 | Q=5.155
Paso 2,135,000/3,000,000 | episodio=329 | epsilon=0.100 | loss=0.0095 | Q=5.718
Paso 2,136,000/3,000,000 | episodio=331 | epsilon=0.100 | loss=0.0213 | Q=5.013
Paso 2,137,000/3,000,000 | episodio=333 | epsilon=0.100 | loss=0.0161 | Q=5.417
Paso 2,138,000/3,000,000 | episodio=335 | epsilon=0.100 | loss=0.0048 | Q=5.278
Paso 2,139,000/3,000,000 | episodio=338 | epsilon=0.100 | loss=0.0027 | Q=5.410
Paso 2,140,000/3,000,000 | episodio=340 | epsilon=0.100 | loss=0.0071 | Q=4.896
Paso 2,141,000/3,000,000 | episodio=343 | epsilon=0.100 | loss=0.0076 | Q=6.043
Paso 2,142,000/3,000,000 | episodio=345 | epsilon=0.100 | loss=0.0044 | Q=4.848
Paso 2,143,000/3,000,000 | episodio=348 | epsilon=0.100 | loss=0.0085 | Q=5.494
Paso 2,144,000/3,000,000 | episodio=349 | epsilon=0.100 | loss=0.0366 | Q=4.894
Paso 2,145,000/3,000,000 | episodio=351 | epsilon=0.100 | loss=0.0102 | Q=5.198
Paso 2,146,000/3,000,000 | episodio=353 | epsilon=0.100 | loss=0.0056 | Q=4.478
Paso 2,147,000/3,000,000 | episodio=357 | epsilon=0.100 | loss=0.0036 | Q=5.047
Paso 2,148,000/3,000,000 | episodio=359 | epsilon=0.100 | loss=0.0149 | Q=6.152
Paso 2,149,000/3,000,000 | episodio=362 | epsilon=0.100 | loss=0.0056 | Q=5.424
Paso 2,150,000/3,000,000 | episodio=364 | epsilon=0.100 | loss=0.0101 | Q=4.747

EVALUACIÓN | paso=2,150,000 | promedio=407.00 | mediana=380.00 | máximo=505.00

Paso 2,151,000/3,000,000 | episodio=367 | epsilon=0.100 | loss=0.0362 | Q=5.303
Paso 2,152,000/3,000,000 | episodio=369 | epsilon=0.100 | loss=0.0038 | Q=5.163
Paso 2,153,000/3,000,000 | episodio=372 | epsilon=0.100 | loss=0.0137 | Q=5.631
Paso 2,154,000/3,000,000 | episodio=373 | epsilon=0.100 | loss=0.0081 | Q=5.577
Paso 2,155,000/3,000,000 | episodio=376 | epsilon=0.100 | loss=0.0087 | Q=5.419
Paso 2,156,000/3,000,000 | episodio=379 | epsilon=0.100 | loss=0.0065 | Q=5.587
Paso 2,157,000/3,000,000 | episodio=382 | epsilon=0.100 | loss=0.0149 | Q=5.101
Paso 2,158,000/3,000,000 | episodio=383 | epsilon=0.100 | loss=0.0130 | Q=5.813
Paso 2,159,000/3,000,000 | episodio=385 | epsilon=0.100 | loss=0.0138 | Q=5.729
Paso 2,160,000/3,000,000 | episodio=386 | epsilon=0.100 | loss=0.0032 | Q=5.302
Paso 2,161,000/3,000,000 | episodio=389 | epsilon=0.100 | loss=0.0132 | Q=4.941
Paso 2,162,000/3,000,000 | episodio=392 | epsilon=0.100 | loss=0.0175 | Q=5.371
Paso 2,163,000/3,000,000 | episodio=394 | epsilon=0.100 | loss=0.0088 | Q=5.087
Paso 2,164,000/3,000,000 | episodio=396 | epsilon=0.100 | loss=0.0132 | Q=4.999
Paso 2,165,000/3,000,000 | episodio=397 | epsilon=0.100 | loss=0.0155 | Q=4.983
Paso 2,166,000/3,000,000 | episodio=399 | epsilon=0.100 | loss=0.0046 | Q=5.676
Paso 2,167,000/3,000,000 | episodio=401 | epsilon=0.100 | loss=0.0068 | Q=5.276
Paso 2,168,000/3,000,000 | episodio=404 | epsilon=0.100 | loss=0.0152 | Q=5.144
Paso 2,169,000/3,000,000 | episodio=406 | epsilon=0.100 | loss=0.0126 | Q=5.058
Paso 2,170,000/3,000,000 | episodio=408 | epsilon=0.100 | loss=0.0136 | Q=5.295
Paso 2,171,000/3,000,000 | episodio=411 | epsilon=0.100 | loss=0.0155 | Q=5.444
Paso 2,172,000/3,000,000 | episodio=413 | epsilon=0.100 | loss=0.0125 | Q=5.045
Paso 2,173,000/3,000,000 | episodio=415 | epsilon=0.100 | loss=0.0116 | Q=5.053
Paso 2,174,000/3,000,000 | episodio=417 | epsilon=0.100 | loss=0.0089 | Q=5.831
Paso 2,175,000/3,000,000 | episodio=420 | epsilon=0.100 | loss=0.0059 | Q=5.453
Paso 2,176,000/3,000,000 | episodio=422 | epsilon=0.100 | loss=0.0053 | Q=5.181
Paso 2,177,000/3,000,000 | episodio=424 | epsilon=0.100 | loss=0.0097 | Q=5.472
Paso 2,178,000/3,000,000 | episodio=425 | epsilon=0.100 | loss=0.0026 | Q=5.198
Paso 2,179,000/3,000,000 | episodio=427 | epsilon=0.100 | loss=0.0116 | Q=5.317
Paso 2,180,000/3,000,000 | episodio=430 | epsilon=0.100 | loss=0.0071 | Q=5.476
Paso 2,181,000/3,000,000 | episodio=432 | epsilon=0.100 | loss=0.0153 | Q=5.498
Paso 2,182,000/3,000,000 | episodio=434 | epsilon=0.100 | loss=0.0115 | Q=5.465
Paso 2,183,000/3,000,000 | episodio=436 | epsilon=0.100 | loss=0.0082 | Q=5.669
Paso 2,184,000/3,000,000 | episodio=438 | epsilon=0.100 | loss=0.0140 | Q=5.295
Paso 2,185,000/3,000,000 | episodio=442 | epsilon=0.100 | loss=0.0147 | Q=5.068
Paso 2,186,000/3,000,000 | episodio=443 | epsilon=0.100 | loss=0.0039 | Q=5.290
Paso 2,187,000/3,000,000 | episodio=446 | epsilon=0.100 | loss=0.0199 | Q=5.234
Paso 2,188,000/3,000,000 | episodio=448 | epsilon=0.100 | loss=0.0092 | Q=5.546
Paso 2,189,000/3,000,000 | episodio=450 | epsilon=0.100 | loss=0.0309 | Q=4.809
Paso 2,190,000/3,000,000 | episodio=451 | epsilon=0.100 | loss=0.0160 | Q=5.367
Paso 2,191,000/3,000,000 | episodio=453 | epsilon=0.100 | loss=0.0096 | Q=5.065
Paso 2,192,000/3,000,000 | episodio=454 | epsilon=0.100 | loss=0.0036 | Q=4.993
Paso 2,193,000/3,000,000 | episodio=457 | epsilon=0.100 | loss=0.0057 | Q=5.487
Paso 2,194,000/3,000,000 | episodio=460 | epsilon=0.100 | loss=0.0028 | Q=5.288
Paso 2,195,000/3,000,000 | episodio=462 | epsilon=0.100 | loss=0.0179 | Q=5.054
Paso 2,196,000/3,000,000 | episodio=464 | epsilon=0.100 | loss=0.0086 | Q=5.243
Paso 2,197,000/3,000,000 | episodio=466 | epsilon=0.100 | loss=0.0137 | Q=5.637
Paso 2,198,000/3,000,000 | episodio=468 | epsilon=0.100 | loss=0.0110 | Q=5.808
Paso 2,199,000/3,000,000 | episodio=471 | epsilon=0.100 | loss=0.0031 | Q=5.987
Paso 2,200,000/3,000,000 | episodio=474 | epsilon=0.100 | loss=0.0046 | Q=5.333

EVALUACIÓN | paso=2,200,000 | promedio=470.00 | mediana=450.00 | máximo=550.00

Paso 2,201,000/3,000,000 | episodio=475 | epsilon=0.100 | loss=0.0031 | Q=5.022
Paso 2,202,000/3,000,000 | episodio=477 | epsilon=0.100 | loss=0.0050 | Q=4.979
Paso 2,203,000/3,000,000 | episodio=478 | epsilon=0.100 | loss=0.0069 | Q=4.941
Paso 2,204,000/3,000,000 | episodio=481 | epsilon=0.100 | loss=0.0098 | Q=4.735
Paso 2,205,000/3,000,000 | episodio=483 | epsilon=0.100 | loss=0.0025 | Q=5.193
Paso 2,206,000/3,000,000 | episodio=485 | epsilon=0.100 | loss=0.0117 | Q=4.596
Paso 2,207,000/3,000,000 | episodio=488 | epsilon=0.100 | loss=0.0019 | Q=5.525
Paso 2,208,000/3,000,000 | episodio=489 | epsilon=0.100 | loss=0.0130 | Q=4.854
Paso 2,209,000/3,000,000 | episodio=491 | epsilon=0.100 | loss=0.0076 | Q=4.903
Paso 2,210,000/3,000,000 | episodio=494 | epsilon=0.100 | loss=0.0120 | Q=5.646
Paso 2,211,000/3,000,000 | episodio=496 | epsilon=0.100 | loss=0.0126 | Q=5.140
Paso 2,212,000/3,000,000 | episodio=497 | epsilon=0.100 | loss=0.0057 | Q=5.216
Paso 2,213,000/3,000,000 | episodio=499 | epsilon=0.100 | loss=0.0098 | Q=5.184
Paso 2,214,000/3,000,000 | episodio=502 | epsilon=0.100 | loss=0.0126 | Q=5.015
Paso 2,215,000/3,000,000 | episodio=505 | epsilon=0.100 | loss=0.0167 | Q=4.786
Paso 2,216,000/3,000,000 | episodio=507 | epsilon=0.100 | loss=0.0060 | Q=4.988
Paso 2,217,000/3,000,000 | episodio=509 | epsilon=0.100 | loss=0.0097 | Q=5.378
Paso 2,218,000/3,000,000 | episodio=512 | epsilon=0.100 | loss=0.0118 | Q=5.005
Paso 2,219,000/3,000,000 | episodio=514 | epsilon=0.100 | loss=0.0060 | Q=5.417
Paso 2,220,000/3,000,000 | episodio=516 | epsilon=0.100 | loss=0.0064 | Q=5.300
Paso 2,221,000/3,000,000 | episodio=519 | epsilon=0.100 | loss=0.0145 | Q=5.430
Paso 2,222,000/3,000,000 | episodio=522 | epsilon=0.100 | loss=0.0084 | Q=5.073
Paso 2,223,000/3,000,000 | episodio=525 | epsilon=0.100 | loss=0.0073 | Q=5.121
Paso 2,224,000/3,000,000 | episodio=528 | epsilon=0.100 | loss=0.0036 | Q=5.122
Paso 2,225,000/3,000,000 | episodio=531 | epsilon=0.100 | loss=0.0215 | Q=5.245
Paso 2,226,000/3,000,000 | episodio=533 | epsilon=0.100 | loss=0.0096 | Q=5.722
Paso 2,227,000/3,000,000 | episodio=536 | epsilon=0.100 | loss=0.0061 | Q=5.546
Paso 2,228,000/3,000,000 | episodio=537 | epsilon=0.100 | loss=0.0030 | Q=5.551
Paso 2,229,000/3,000,000 | episodio=540 | epsilon=0.100 | loss=0.0235 | Q=5.500
Paso 2,230,000/3,000,000 | episodio=542 | epsilon=0.100 | loss=0.0039 | Q=5.381
Paso 2,231,000/3,000,000 | episodio=544 | epsilon=0.100 | loss=0.0128 | Q=5.289
Paso 2,232,000/3,000,000 | episodio=547 | epsilon=0.100 | loss=0.0096 | Q=5.483
Paso 2,233,000/3,000,000 | episodio=549 | epsilon=0.100 | loss=0.0095 | Q=5.134
Paso 2,234,000/3,000,000 | episodio=551 | epsilon=0.100 | loss=0.0085 | Q=5.703
Paso 2,235,000/3,000,000 | episodio=554 | epsilon=0.100 | loss=0.0152 | Q=5.838
Paso 2,236,000/3,000,000 | episodio=557 | epsilon=0.100 | loss=0.0062 | Q=5.773
Paso 2,237,000/3,000,000 | episodio=559 | epsilon=0.100 | loss=0.0086 | Q=5.643
Paso 2,238,000/3,000,000 | episodio=561 | epsilon=0.100 | loss=0.0097 | Q=5.965
Paso 2,239,000/3,000,000 | episodio=562 | epsilon=0.100 | loss=0.0040 | Q=5.213
Paso 2,240,000/3,000,000 | episodio=566 | epsilon=0.100 | loss=0.0158 | Q=5.407
Paso 2,241,000/3,000,000 | episodio=568 | epsilon=0.100 | loss=0.0205 | Q=5.031
Paso 2,242,000/3,000,000 | episodio=570 | epsilon=0.100 | loss=0.0138 | Q=6.066
Paso 2,243,000/3,000,000 | episodio=573 | epsilon=0.100 | loss=0.0054 | Q=5.808
Paso 2,244,000/3,000,000 | episodio=575 | epsilon=0.100 | loss=0.0018 | Q=5.488
Paso 2,245,000/3,000,000 | episodio=578 | epsilon=0.100 | loss=0.0072 | Q=4.905
Paso 2,246,000/3,000,000 | episodio=581 | epsilon=0.100 | loss=0.0045 | Q=5.523
Paso 2,247,000/3,000,000 | episodio=583 | epsilon=0.100 | loss=0.0025 | Q=5.327
Paso 2,248,000/3,000,000 | episodio=585 | epsilon=0.100 | loss=0.0052 | Q=5.724
Paso 2,249,000/3,000,000 | episodio=587 | epsilon=0.100 | loss=0.0088 | Q=6.079
Paso 2,250,000/3,000,000 | episodio=589 | epsilon=0.100 | loss=0.0100 | Q=4.946


In [27]:
from pathlib import Path
import pandas as pd
from IPython.display import display


RUTA_LOG_V6_3M = Path(
    "../logs/entrenamientos/"
    "v6_dqn_per_3step_3m/"
    "evaluaciones.csv"
)

RUTA_MEJOR_MODELO_V6_3M = Path(
    "../models/"
    "v6_dqn_per_3step_3m/"
    "mejor_modelo.pt"
)

df_evaluaciones_v6_3m = pd.read_csv(
    RUTA_LOG_V6_3M
)

display(df_evaluaciones_v6_3m)

mejor_fila_v6_3m = df_evaluaciones_v6_3m.loc[
    df_evaluaciones_v6_3m["promedio"].idxmax()
]

promedio_ultimas_tres_v6_3m = (
    df_evaluaciones_v6_3m["promedio"]
    .tail(3)
    .mean()
)

print("\nMEJOR EVALUACIÓN ENTRE 2M Y 3M")
print(
    f"Paso: {int(mejor_fila_v6_3m['paso_global']):,}"
)
print(
    f"Promedio: {mejor_fila_v6_3m['promedio']:.2f}"
)
print(
    f"Mediana: {mejor_fila_v6_3m['mediana']:.2f}"
)
print(
    f"Desviación: {mejor_fila_v6_3m['desviacion']:.2f}"
)
print(
    f"Mínimo: {mejor_fila_v6_3m['minimo']:.2f}"
)
print(
    f"Máximo: {mejor_fila_v6_3m['maximo']:.2f}"
)

print(
    "\nPromedio de las últimas tres evaluaciones: "
    f"{promedio_ultimas_tres_v6_3m:.2f}"
)

print(
    "\nCheckpoint disponible:",
    (
        "OK"
        if RUTA_MEJOR_MODELO_V6_3M.exists()
        else "NO ENCONTRADO"
    ),
)

    paso_global  promedio  mediana  desviacion  minimo  maximo
0       2050000     571.0    650.0  150.512458   285.0   690.0
1       2100000     424.0    410.0   73.579889   330.0   525.0
2       2150000     407.0    380.0   81.523003   305.0   505.0
3       2200000     470.0    450.0   63.560994   400.0   550.0
4       2250000     426.0    400.0   81.141851   335.0   575.0
5       2300000     482.0    475.0  137.971011   310.0   715.0
6       2350000     524.0    470.0   82.668011   435.0   645.0
7       2400000     362.0    330.0  114.830310   225.0   570.0
8       2450000     522.0    490.0  113.692568   350.0   685.0
9       2500000     625.0    600.0  103.730420   520.0   800.0
10      2550000     383.0    385.0   38.807216   320.0   430.0
11      2600000     445.0    400.0   90.719347   340.0   585.0
12      2650000     431.0    435.0   80.212219   315.0   520.0
13      2700000     635.0    740.0  146.321564   375.0   745.0
14      2750000     420.0    420.0   34.205263   380.0   480.0
15      2800000     385.0    380.0   72.732386   305.0   470.0
16      2850000     485.0    450.0  140.000000   340.0   720.0
17      2900000     554.0    515.0   80.274529   485.0   710.0
18      2950000     556.0    545.0  198.579959   240.0   810.0
19      3000000     547.0    490.0  150.386170   405.0   800.0

MEJOR EVALUACIÓN ENTRE 2M Y 3M
Paso: 2,700,000
Promedio: 635.00
Mediana: 740.00
Desviación: 146.32
Mínimo: 375.00
Máximo: 745.00

Promedio de las últimas tres evaluaciones: 552.33

Checkpoint disponible: OK

In [28]:
from pathlib import Path

import torch

from models import DQN


RUTA_MEJOR_V6_3M = Path(
    "../models/"
    "v6_dqn_per_3step_3m/"
    "mejor_modelo.pt"
)

checkpoint_v6_3m = torch.load(
    RUTA_MEJOR_V6_3M,
    map_location=device,
    weights_only=True,
)

mejor_v6_3m = DQN(
    n_acciones=6
).to(device)

mejor_v6_3m.load_state_dict(
    checkpoint_v6_3m["modelo_online_state_dict"]
)

mejor_v6_3m.eval()

print(
    "Checkpoint cargado desde el paso:",
    f"{checkpoint_v6_3m['paso']:,}",
)

Checkpoint cargado desde el paso: 2,700,000

In [29]:
N_EPISODIOS_EVALUACION = 30
SEMILLA_BASE_EVALUACION = 42

print(
    "\nEvaluando V6 entrenado hasta 3M "
    "(checkpoint de 2.7M) durante "
    f"{N_EPISODIOS_EVALUACION} episodios...\n"
)

resultados_v6_3m, resumen_v6_3m = evaluar_modelo(
    modelo=mejor_v6_3m,
    config=config_v6_3m,
    device=device,
    n_episodios=N_EPISODIOS_EVALUACION,
    seed_base=SEMILLA_BASE_EVALUACION,
)

df_v6_3m = pd.DataFrame(
    resultados_v6_3m
)

df_v6_3m["agente"] = (
    "DQN + PER a=0.6 + 3-step (2.7M)"
)

df_v6_3m = df_v6_3m[
    [
        "agente",
        "episodio",
        "seed",
        "recompensa_total",
        "pasos",
        "terminated",
        "truncated",
    ]
]

print("RESUMEN DE 30 EPISODIOS")

for metrica, valor in resumen_v6_3m.items():
    print(f"{metrica}: {valor:.2f}")

display(df_v6_3m.head(10))

Evaluando V6 entrenado hasta 3M (checkpoint de 2.7M) durante 30 episodios...

RESUMEN DE 30 EPISODIOS
promedio: 510.67
mediana: 480.00
desviacion: 137.43
minimo: 325.00
maximo: 920.00

,agente,episodio,seed,recompensa_total,pasos,terminated,truncated
0,DQN + PER a=0.6 + 3-step (2.7M),0,42,330.0,615,True,False
1,DQN + PER a=0.6 + 3-step (2.7M),1,43,410.0,711,True,False
2,DQN + PER a=0.6 + 3-step (2.7M),2,44,600.0,909,True,False
3,DQN + PER a=0.6 + 3-step (2.7M),3,45,570.0,1003,True,False
4,DQN + PER a=0.6 + 3-step (2.7M),4,46,735.0,768,True,False
5,DQN + PER a=0.6 + 3-step (2.7M),5,47,530.0,866,True,False
6,DQN + PER a=0.6 + 3-step (2.7M),6,48,920.0,1079,True,False
7,DQN + PER a=0.6 + 3-step (2.7M),7,49,605.0,819,True,False
8,DQN + PER a=0.6 + 3-step (2.7M),8,50,470.0,831,True,False
9,DQN + PER a=0.6 + 3-step (2.7M),9,51,325.0,618,True,False

In [30]:
import numpy as np
import pandas as pd
from IPython.display import display


comparacion_checkpoints = (
    df_v6_extendido[
        ["seed", "recompensa_total"]
    ]
    .rename(
        columns={
            "recompensa_total": "V6 2.0M"
        }
    )
    .merge(
        df_v6_3m[
            ["seed", "recompensa_total"]
        ].rename(
            columns={
                "recompensa_total": "V6 2.7M"
            }
        ),
        on="seed",
        how="inner",
        validate="one_to_one",
    )
)

diferencia = (
    comparacion_checkpoints["V6 2.7M"]
    - comparacion_checkpoints["V6 2.0M"]
)

print("COMPARACIÓN PAREADA")
print(
    "Victorias del checkpoint 2.0M:",
    int((diferencia < 0).sum()),
)
print(
    "Victorias del checkpoint 2.7M:",
    int((diferencia > 0).sum()),
)
print(
    "Empates:",
    int((diferencia == 0).sum()),
)
print(
    "Diferencia promedio a favor de 2.7M:",
    f"{diferencia.mean():.2f} puntos",
)

df_bloques_checkpoints = pd.concat(
    [
        df_v6_extendido.assign(
            agente="V6 checkpoint 2.0M"
        ),
        df_v6_3m.assign(
            agente="V6 checkpoint 2.7M"
        ),
    ],
    ignore_index=True,
)

df_bloques_checkpoints["bloque_de_5"] = (
    df_bloques_checkpoints
    .groupby("agente")
    .cumcount()
    .floordiv(5)
    .add(1)
)

mejores_por_bloque = (
    df_bloques_checkpoints
    .groupby(
        ["agente", "bloque_de_5"],
        as_index=False,
    )
    .agg(
        mejor_recompensa=(
            "recompensa_total",
            "max",
        ),
        promedio_bloque=(
            "recompensa_total",
            "mean",
        ),
    )
)

resumen_mejor_de_5 = (
    mejores_por_bloque
    .groupby("agente", as_index=False)
    .agg(
        mejor_de_5_promedio=(
            "mejor_recompensa",
            "mean",
        ),
        mejor_de_5_mediana=(
            "mejor_recompensa",
            "median",
        ),
        menor_mejor_de_5=(
            "mejor_recompensa",
            "min",
        ),
        mayor_mejor_de_5=(
            "mejor_recompensa",
            "max",
        ),
    )
)

print("\nRESULTADOS POR BLOQUE")
display(mejores_por_bloque)

print("\nRESUMEN DEL MEJOR DE CINCO")
display(resumen_mejor_de_5)

COMPARACIÓN PAREADA
Victorias del checkpoint 2.0M: 16
Victorias del checkpoint 2.7M: 13
Empates: 1
Diferencia promedio a favor de 2.7M: 1.50 puntos

RESULTADOS POR BLOQUE

                agente  bloque_de_5  mejor_recompensa  promedio_bloque
0   V6 checkpoint 2.0M            1             615.0            511.0
1   V6 checkpoint 2.0M            2             605.0            486.0
2   V6 checkpoint 2.0M            3             610.0            511.0
3   V6 checkpoint 2.0M            4             700.0            516.0
4   V6 checkpoint 2.0M            5             570.0            492.0
5   V6 checkpoint 2.0M            6             910.0            539.0
6   V6 checkpoint 2.7M            1             735.0            529.0
7   V6 checkpoint 2.7M            2             920.0            570.0
8   V6 checkpoint 2.7M            3             690.0            539.0
9   V6 checkpoint 2.7M            4             715.0            517.0
10  V6 checkpoint 2.7M            5             500.0            465.0
11  V6 checkpoint 2.7M            6             570.0            444.0

RESUMEN DEL MEJOR DE CINCO

,agente,mejor_de_5_promedio,mejor_de_5_mediana,menor_mejor_de_5,mayor_mejor_de_5
0,V6 checkpoint 2.0M,668.333333,612.5,570.0,910.0
1,V6 checkpoint 2.7M,688.333333,702.5,500.0,920.0

### Selección del modelo final

El modelo seleccionado fue **DQN con Prioritized Experience Replay
($\alpha=0.6$) y retornos de 3 pasos**, utilizando el checkpoint obtenido
en el paso **2,700,000**.

En una evaluación greedy de 30 episodios alcanzó un promedio de
**510.67 puntos**, una mediana de **480 puntos** y un máximo de
**920 puntos**.

Su rendimiento promedio fue prácticamente equivalente al checkpoint de
2,000,000 pasos. Sin embargo, obtuvo mejores resultados bajo el criterio
de mejor episodio en bloques de cinco: su mejor-de-cinco promedio fue
**688.33**, frente a **668.33** del checkpoint de 2,000,000 pasos.

Aunque el checkpoint de 2,000,000 ganó más comparaciones pareadas y
presentó menor variabilidad, se eligió el de 2,700,000 porque el criterio
de evaluación de la competencia favorece el mejor desempeño obtenido
durante cinco episodios. El checkpoint de 2,000,000 se conservó como
modelo de respaldo por su mayor estabilidad.

In [31]:
from pathlib import Path

DIRECTORIO_RESULTADOS = Path("../logs/resultados_finales")
DIRECTORIO_RESULTADOS.mkdir(
    parents=True,
    exist_ok=True,
)

RUTA_EVALUACION_FINAL = (
    DIRECTORIO_RESULTADOS
    / "evaluacion_modelo_final_2_7m.csv"
)

RUTA_COMPARACION_CHECKPOINTS = (
    DIRECTORIO_RESULTADOS
    / "comparacion_checkpoints_2m_vs_2_7m.csv"
)

RUTA_MEJOR_DE_CINCO = (
    DIRECTORIO_RESULTADOS
    / "mejor_de_cinco_2m_vs_2_7m.csv"
)

df_v6_3m.to_csv(
    RUTA_EVALUACION_FINAL,
    index=False,
)

comparacion_checkpoints.to_csv(
    RUTA_COMPARACION_CHECKPOINTS,
    index=False,
)

resumen_mejor_de_5.to_csv(
    RUTA_MEJOR_DE_CINCO,
    index=False,
)

print("ARCHIVOS GUARDADOS")

for ruta in [
    RUTA_EVALUACION_FINAL,
    RUTA_COMPARACION_CHECKPOINTS,
    RUTA_MEJOR_DE_CINCO,
]:
    print(f"{ruta}: {'OK' if ruta.exists() else 'ERROR'}")

ARCHIVOS GUARDADOS
../logs/resultados_finales/evaluacion_modelo_final_2_7m.csv: OK
../logs/resultados_finales/comparacion_checkpoints_2m_vs_2_7m.csv: OK
../logs/resultados_finales/mejor_de_cinco_2m_vs_2_7m.csv: OK

In [32]:
import numpy as np
import torch

from ale_utils import generar_video_agente


def agente_greedy_final(observacion, env):
    observacion_np = np.asarray(
        observacion,
        dtype=np.uint8,
    )

    observacion_tensor = torch.as_tensor(
        observacion_np,
        device=device,
    ).unsqueeze(0)

    with torch.no_grad():
        valores_q = mejor_v6_3m(
            observacion_tensor
        )

    accion = valores_q.argmax(
        dim=1
    ).item()

    return accion


print("Agente greedy final preparado.")

Agente greedy final preparado.

In [41]:
from pathlib import Path
import shutil
import pandas as pd


DIRECTORIO_VIDEOS = Path(
    "../videos/candidatos_modelo_final"
)

resultado_videos_finales = generar_video_agente(
    nombre_entorno="ALE/SpaceInvaders-v5",
    funcion_agente=agente_greedy_final,
    video_folder=str(DIRECTORIO_VIDEOS),
    name_prefix="dqn_per_3step_2_7m",
    n_episodios=5,
    max_steps=10_000,

    aplicar_preprocesamiento=True,
    frame_skip=4,
    screen_size=84,
    grayscale=True,
    stack_size=4,

    # Evaluación de la partida completa
    terminal_on_life_loss=False,
    clip_reward=False,
    noop_max=30,

    full_action_space=False,
)

df_videos_finales = pd.DataFrame(
    resultado_videos_finales["metricas"]
)

df_videos_finales["ruta_video"] = (
    resultado_videos_finales["videos"]
)

display(df_videos_finales)

indice_mejor_video = (
    df_videos_finales["recompensa_total"].idxmax()
)

mejor_video = Path(
    df_videos_finales.loc[
        indice_mejor_video,
        "ruta_video",
    ]
)

DIRECTORIO_FINAL = Path("../videos")
DIRECTORIO_FINAL.mkdir(
    parents=True,
    exist_ok=True,
)

RUTA_VIDEO_ENTREGABLE = (
    DIRECTORIO_FINAL
    / "space_invaders_modelo_final.mp4"
)

shutil.copy2(
    mejor_video,
    RUTA_VIDEO_ENTREGABLE,
)

print("\nVIDEO SELECCIONADO")
print(
    "Episodio:",
    int(
        df_videos_finales.loc[
            indice_mejor_video,
            "episodio",
        ]
    ),
)
print(
    "Puntuación:",
    df_videos_finales.loc[
        indice_mejor_video,
        "recompensa_total",
    ],
)
print(
    "Pasos:",
    int(
        df_videos_finales.loc[
            indice_mejor_video,
            "pasos",
        ]
    ),
)
print("Archivo:", RUTA_VIDEO_ENTREGABLE)
print(
    "Existe:",
    RUTA_VIDEO_ENTREGABLE.exists(),
)

/Users/Camila/Desktop/CAMILA UNIVERSIDAD/8SEMESTRE/DeepLearning/Proyecto2-DL/.venv/lib/python3.12/site-packages/gymnasium/wrappers/rendering.py:283: UserWarning: WARN: Overwriting existing videos at /Users/Camila/Desktop/CAMILA UNIVERSIDAD/8SEMESTRE/DeepLearning/Proyecto2-DL/videos/candidatos_modelo_final folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(

,pasos,recompensa_total,terminated,truncated,seed,episodio,ruta_video
0,823,465.0,True,False,None,0,../videos/candidatos_modelo_final/dqn_per_3ste...
1,1009,600.0,True,False,None,1,../videos/candidatos_modelo_final/dqn_per_3ste...
2,690,350.0,True,False,None,2,../videos/candidatos_modelo_final/dqn_per_3ste...
3,683,285.0,True,False,None,3,../videos/candidatos_modelo_final/dqn_per_3ste...
4,999,775.0,True,False,None,4,../videos/candidatos_modelo_final/dqn_per_3ste...

VIDEO SELECCIONADO
Episodio: 4
Puntuación: 775.0
Pasos: 999
Archivo: ../videos/space_invaders_modelo_final.mp4
Existe: True

In [42]:
from pathlib import Path
import shutil
import pandas as pd
from IPython.display import display


# Carpeta independiente para evitar mezclar ambas tandas
DIRECTORIO_VIDEOS_TANDA_2 = Path(
    "../videos/candidatos_modelo_final_tanda_2"
)

resultado_videos_tanda_2 = generar_video_agente(
    nombre_entorno="ALE/SpaceInvaders-v5",
    funcion_agente=agente_greedy_final,
    video_folder=str(DIRECTORIO_VIDEOS_TANDA_2),
    name_prefix="dqn_per_3step_2_7m_tanda_2",
    n_episodios=5,
    max_steps=10_000,

    aplicar_preprocesamiento=True,
    frame_skip=4,
    screen_size=84,
    grayscale=True,
    stack_size=4,

    # Partida completa con puntuación real
    terminal_on_life_loss=False,
    clip_reward=False,
    noop_max=30,

    full_action_space=False,
)

df_videos_tanda_2 = pd.DataFrame(
    resultado_videos_tanda_2["metricas"]
)

df_videos_tanda_2["ruta_video"] = (
    resultado_videos_tanda_2["videos"]
)

display(df_videos_tanda_2)

# Seleccionar el episodio con mayor puntuación
indice_mejor_tanda_2 = (
    df_videos_tanda_2["recompensa_total"].idxmax()
)

mejor_fila_tanda_2 = df_videos_tanda_2.loc[
    indice_mejor_tanda_2
]

mejor_video_tanda_2 = Path(
    mejor_fila_tanda_2["ruta_video"]
)

DIRECTORIO_FINAL = Path("../videos")
DIRECTORIO_FINAL.mkdir(
    parents=True,
    exist_ok=True,
)

# Guardarlo por separado para no sobrescribir todavía
RUTA_VIDEO_TANDA_2 = (
    DIRECTORIO_FINAL
    / "space_invaders_modelo_final_tanda_2.mp4"
)

shutil.copy2(
    mejor_video_tanda_2,
    RUTA_VIDEO_TANDA_2,
)

puntuacion_tanda_1 = 775.0
puntuacion_tanda_2 = float(
    mejor_fila_tanda_2["recompensa_total"]
)

print("\nMEJOR VIDEO DE LA SEGUNDA TANDA")
print(
    "Episodio:",
    int(mejor_fila_tanda_2["episodio"]),
)
print(
    "Puntuación:",
    puntuacion_tanda_2,
)
print(
    "Pasos:",
    int(mejor_fila_tanda_2["pasos"]),
)
print(
    "Terminated:",
    bool(mejor_fila_tanda_2["terminated"]),
)
print(
    "Truncated:",
    bool(mejor_fila_tanda_2["truncated"]),
)
print(
    "Archivo:",
    RUTA_VIDEO_TANDA_2,
)
print(
    "Existe:",
    RUTA_VIDEO_TANDA_2.exists(),
)

print("\nCOMPARACIÓN CON LA PRIMERA TANDA")
print(
    f"Primera tanda: {puntuacion_tanda_1:.0f} puntos"
)
print(
    f"Segunda tanda: {puntuacion_tanda_2:.0f} puntos"
)

if puntuacion_tanda_2 > puntuacion_tanda_1:
    print(
        "La segunda tanda obtuvo un video mejor."
    )
else:
    print(
        "Se conserva el video de la primera tanda."
    )

/Users/Camila/Desktop/CAMILA UNIVERSIDAD/8SEMESTRE/DeepLearning/Proyecto2-DL/.venv/lib/python3.12/site-packages/gymnasium/wrappers/rendering.py:283: UserWarning: WARN: Overwriting existing videos at /Users/Camila/Desktop/CAMILA UNIVERSIDAD/8SEMESTRE/DeepLearning/Proyecto2-DL/videos/candidatos_modelo_final_tanda_2 folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(

,pasos,recompensa_total,terminated,truncated,seed,episodio,ruta_video
0,623,330.0,True,False,None,0,../videos/candidatos_modelo_final_tanda_2/dqn_...
1,1138,800.0,True,False,None,1,../videos/candidatos_modelo_final_tanda_2/dqn_...
2,727,420.0,True,False,None,2,../videos/candidatos_modelo_final_tanda_2/dqn_...
3,626,535.0,True,False,None,3,../videos/candidatos_modelo_final_tanda_2/dqn_...
4,744,495.0,True,False,None,4,../videos/candidatos_modelo_final_tanda_2/dqn_...

MEJOR VIDEO DE LA SEGUNDA TANDA
Episodio: 1
Puntuación: 800.0
Pasos: 1138
Terminated: True
Truncated: False
Archivo: ../videos/space_invaders_modelo_final_tanda_2.mp4
Existe: True

COMPARACIÓN CON LA PRIMERA TANDA
Primera tanda: 775 puntos
Segunda tanda: 800 puntos
La segunda tanda obtuvo un video mejor.

In [43]:
from pathlib import Path
import shutil
from IPython.display import Video, display


RUTA_VIDEO_ANTERIOR = Path(
    "../videos/space_invaders_modelo_final.mp4"
)

RUTA_RESPALDO_775 = Path(
    "../videos/space_invaders_respaldo_775_puntos.mp4"
)

RUTA_VIDEO_800 = Path(
    "../videos/space_invaders_modelo_final_tanda_2.mp4"
)

RUTA_VIDEO_FINAL = Path(
    "../videos/space_invaders_modelo_final.mp4"
)

# Conservar el video anterior como respaldo
if (
    RUTA_VIDEO_ANTERIOR.exists()
    and not RUTA_RESPALDO_775.exists()
):
    shutil.copy2(
        RUTA_VIDEO_ANTERIOR,
        RUTA_RESPALDO_775,
    )

# Establecer el video de 800 puntos como entregable
shutil.copy2(
    RUTA_VIDEO_800,
    RUTA_VIDEO_FINAL,
)

tamano_mb = (
    RUTA_VIDEO_FINAL.stat().st_size
    / (1024 ** 2)
)

print("VIDEO FINAL ACTUALIZADO")
print("Puntuación: 800 puntos")
print("Pasos: 1,138")
print("Terminated: True")
print("Truncated: False")
print("Archivo:", RUTA_VIDEO_FINAL)
print(f"Tamaño: {tamano_mb:.2f} MB")
print("Respaldo de 775:", RUTA_RESPALDO_775.exists())

display(
    Video(
        str(RUTA_VIDEO_FINAL),
        embed=True,
    )
)

VIDEO FINAL ACTUALIZADO
Puntuación: 800 puntos
Pasos: 1,138
Terminated: True
Truncated: False
Archivo: ../videos/space_invaders_modelo_final.mp4
Tamaño: 0.48 MB
Respaldo de 775: True